# Generated by Django 5.1.2 on 2025-06-18 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_migrate_to_supabase_storage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='resume_content_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='resume_file_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='resume_original_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterModelTable(
            name='department',
            table='jobs_department',
        ),
        migrations.AlterModelTable(
            name='jobapplication',
            table='jobs_jobapplication',
        ),
        migrations.AlterModelTable(
            name='jobposition',
            table='jobs_jobposition',
        ),
    ]
