# Generated by Django 5.1.2 on 2024-12-25 21:32

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('username', models.CharField(db_index=True, max_length=255, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('birthday', models.DateField(null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True)),
                ('is_active', models.BooleanField(default=1)),
                ('is_subscribed', models.BooleanField(default=0)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('bio', models.TextField(blank=True, max_length=500, null=True)),
                ('native_language', models.CharField(choices=[('EN', 'English'), ('FR', 'French'), ('NL', 'Dutch'), ('DE', 'German'), ('ES', 'Spanish'), ('IT', 'Italian'), ('PT', 'Portuguese')], default='EN', help_text='Your native language', max_length=20)),
                ('target_language', models.CharField(choices=[('EN', 'English'), ('FR', 'French'), ('NL', 'Dutch'), ('DE', 'German'), ('ES', 'Spanish'), ('IT', 'Italian'), ('PT', 'Portuguese')], default='EN', help_text='The language you want to learn', max_length=20)),
                ('language_level', models.CharField(choices=[('A1', 'Beginner'), ('A2', 'Elementary'), ('B1', 'Intermediate'), ('B2', 'Upper Intermediate'), ('C1', 'Advanced'), ('C2', 'Proficiency')], default='A1', help_text='Your language level', max_length=2)),
                ('objectives', models.CharField(choices=[('Travel', 'Travel'), ('Business', 'Business'), ('Live Abroad', 'Live Abroad'), ('Exam', 'Exam'), ('For Fun', 'For Fun'), ('Work', 'Work'), ('School', 'School'), ('Study', 'Study'), ('Personal', 'Personal')], default='Travel', help_text='Your learning objectives', max_length=20)),
                ('is_coach', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CoachProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coaching_languages', models.CharField(choices=[('EN', 'English'), ('FR', 'French'), ('NL', 'Dutch'), ('DE', 'German'), ('ES', 'Spanish'), ('IT', 'Italian'), ('PT', 'Portuguese')], default='EN', max_length=20)),
                ('price_per_hour', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('availability', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('bio', models.TextField(blank=True, max_length=500, null=True)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='Commission rate taken by Linguify (in %).', max_digits=5)),
                ('commission_override', models.DecimalField(blank=True, decimal_places=2, help_text='Override the default commission rate.', max_digits=5, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coach_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('comment', models.TextField(blank=True, max_length=500, null=True)),
                ('review_date', models.DateTimeField(auto_now_add=True)),
                ('coach', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='authentication.coachprofile')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike')], default='like', max_length=10)),
                ('feedback_content', models.TextField(blank=True, null=True)),
                ('feedback_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
