# Generated by Django 5.1.2 on 2024-11-28 17:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachprofile',
            name='current_students',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='max_students',
            field=models.PositiveIntegerField(default=20, help_text='Maximum number of students per session.'),
        ),
        migrations.CreateModel(
            name='FavoriteCoach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='authentication.coachprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_coaches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'coach'), name='unique_favorite_coach')],
            },
        ),
    ]
