# Generated by Django 5.1.2 on 2024-12-23 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_coachprofile_current_students_and_more'),
        ('authentication', '0002_remove_user_age_user_birthday'),
    ]

    operations = [
    ]
