# Generated by Django 5.1.2 on 2025-05-26 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='jobposition',
            new_name='jobs_jobpos_is_acti_cddb7b_idx',
            old_name='jobs_jobpos_is_acti_0e6e85_idx',
        ),
        migrations.RenameIndex(
            model_name='jobposition',
            new_name='jobs_jobpos_departm_740367_idx',
            old_name='jobs_jobpos_departm_c44ba0_idx',
        ),
    ]
