# Generated by Django 5.1.2 on 2025-05-26 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_rename_jobs_jobpos_is_acti_0e6e85_idx_jobs_jobpos_is_acti_cddb7b_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='resume_file',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='cover_letter',
            field=models.TextField(blank=True),
        ),
    ]
