# Generated by Django 5.1.2 on 2025-06-18 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_allow_spontaneous_applications'),
        ('jobs', '0005_alter_jobapplication_resume_content_type_and_more'),
    ]

    operations = [
    ]
