# Generated by Django 5.0.3 on 2025-10-03 22:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'jobs_department',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='JobPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('employment_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('internship', 'Internship'), ('remote', 'Remote')], default='full_time', max_length=20)),
                ('experience_level', models.CharField(choices=[('entry', 'Entry Level'), ('mid', 'Mid Level'), ('senior', 'Senior Level'), ('lead', 'Lead'), ('manager', 'Manager')], default='mid', max_length=20)),
                ('description', models.TextField()),
                ('requirements', models.TextField()),
                ('responsibilities', models.TextField()),
                ('benefits', models.TextField(blank=True)),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salary_currency', models.CharField(default='EUR', max_length=3)),
                ('application_email', models.EmailField(max_length=254)),
                ('application_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('posted_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('closing_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='jobs.department')),
            ],
            options={
                'db_table': 'jobs_jobposition',
                'ordering': ['-posted_date', '-is_featured'],
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('cover_letter', models.TextField(blank=True)),
                ('resume_file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('resume_original_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('resume_content_type', models.CharField(blank=True, max_length=100, null=True)),
                ('resume_url', models.URLField(blank=True)),
                ('portfolio_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('reviewed', 'Under Review'), ('interview', 'Interview Stage'), ('offer', 'Offer Extended'), ('hired', 'Hired'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='submitted', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('applied_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.jobposition')),
            ],
            options={
                'db_table': 'jobs_jobapplication',
                'ordering': ['-applied_at'],
            },
        ),
        migrations.AddIndex(
            model_name='jobposition',
            index=models.Index(fields=['is_active', 'posted_date'], name='jobs_jobpos_is_acti_cddb7b_idx'),
        ),
        migrations.AddIndex(
            model_name='jobposition',
            index=models.Index(fields=['department', 'is_active'], name='jobs_jobpos_departm_740367_idx'),
        ),
    ]
