# Generated by Django 5.1.2 on 2024-11-25 23:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('flashcard_id', models.AutoField(primary_key=True, serialize=False)),
                ('flashcard_title', models.CharField(max_length=100)),
                ('image_flashcard', models.ImageField(blank=True, null=True, upload_to='flashcard_images/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to=settings.AUTH_USER_MODEL)),
                ('vocabulary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='course.vocabulary')),
            ],
        ),
        migrations.CreateModel(
            name='UserFlashcardProgress',
            fields=[
                ('user_flashcard_progress_id', models.AutoField(primary_key=True, serialize=False)),
                ('statut', models.CharField(choices=[('Not started', 'Not started'), ('In progress', 'In progress'), ('Completed', 'Completed')], default='Not started', max_length=20)),
                ('percentage_completion', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('score_flashcard', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('time_study', models.PositiveIntegerField(default=0, help_text='Time spent studying in minutes', validators=[django.core.validators.MinValueValidator(0)])),
                ('flashcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='flashcard.flashcard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcard_progress', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
