# Generated by Django 5.1.10 on 2025-09-14 23:39

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('default_project_view', models.CharField(choices=[('list', 'List'), ('kanban', 'Kanban'), ('calendar', 'Calendar'), ('timeline', 'Timeline')], default='list', max_length=20)),
                ('default_task_view', models.CharField(choices=[('list', 'List'), ('priority', 'Priority'), ('due_date', 'Due Date'), ('project', 'Project')], default='list', max_length=20)),
                ('auto_archive_completed', models.BooleanField(default=False)),
                ('auto_archive_days', models.PositiveIntegerField(default=30, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(90)])),
                ('auto_delete_archived', models.BooleanField(default=False)),
                ('auto_delete_archive_days', models.PositiveIntegerField(default=30, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(90)])),
                ('show_subtask_count', models.BooleanField(default=True)),
                ('show_progress_bars', models.BooleanField(default=True)),
                ('enable_reminders', models.BooleanField(default=True)),
                ('reminder_minutes_before', models.PositiveIntegerField(default=15, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1440)])),
                ('daily_digest', models.BooleanField(default=True)),
                ('daily_digest_time', models.TimeField(default='09:00:00')),
                ('overdue_notifications', models.BooleanField(default=True)),
                ('enable_time_tracking', models.BooleanField(default=False)),
                ('pomodoro_timer', models.BooleanField(default=False)),
                ('pomodoro_duration', models.PositiveIntegerField(default=25, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(60)])),
                ('break_duration', models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)])),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('auto', 'Auto')], default='auto', max_length=10)),
                ('compact_mode', models.BooleanField(default=False)),
                ('show_completed_tasks', models.BooleanField(default=True)),
                ('quick_add_shortcut', models.BooleanField(default=True)),
                ('default_task_priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('default_reminder_time', models.TimeField(default='09:00:00')),
                ('allow_task_sharing', models.BooleanField(default=True)),
                ('allow_project_sharing', models.BooleanField(default=True)),
                ('public_templates', models.BooleanField(default=False)),
                ('backup_frequency', models.CharField(choices=[('never', 'Never'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='weekly', max_length=10)),
                ('include_completed_in_exports', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='todo_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Todo Settings',
                'verbose_name_plural': 'Todo Settings',
            },
        ),
    ]
