# Generated by Django 5.1.10 on 2025-08-18 00:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['state', '-priority', 'due_date', 'sequence', 'id'], 'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
        migrations.AddField(
            model_name='task',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='task',
            name='color',
            field=models.IntegerField(default=0, help_text='Color index for kanban cards (0-11)'),
        ),
        migrations.AddField(
            model_name='task',
            name='sequence',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='task',
            name='state',
            field=models.CharField(choices=[('1_draft', 'Draft'), ('1_todo', 'To Do'), ('1_in_progress', 'In Progress'), ('1_done', 'Done'), ('1_canceled', 'Canceled')], default='1_todo', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('0', 'Normal'), ('1', 'Starred')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='PersonalStageType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('sequence', models.IntegerField(default=10)),
                ('fold', models.BooleanField(default=False, help_text='Fold this stage in kanban view')),
                ('color', models.CharField(default='#6c757d', max_length=7)),
                ('is_closed', models.BooleanField(default=False, help_text='Tasks in this stage are considered closed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_stages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Personal Stage',
                'verbose_name_plural': 'Personal Stages',
                'ordering': ['sequence', 'name'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.AddField(
            model_name='task',
            name='personal_stage_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='todo.personalstagetype'),
        ),
    ]
