# Generated by Django 5.1.10 on 2025-09-15 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todosettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todosettings',
            name='default_project_view',
            field=models.CharField(choices=[('list', 'List'), ('kanban', 'Kanban'), ('activity', 'Activity')], default='kanban', max_length=20),
        ),
    ]
