# Generated by Django 5.0.3 on 2025-10-04 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0001_initial'),
        ('todo', '0003_update_default_view_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='source_note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_tasks', to='notebook.note'),
        ),
    ]
