# Generated by Django 5.1.10 on 2025-09-04 23:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description du groupe', null=True)),
                ('avatar', models.ImageField(blank=True, help_text='Avatar du groupe', null=True, upload_to='groups/avatars/')),
                ('language', models.CharField(choices=[('EN', 'English'), ('FR', 'French'), ('ES', 'Spanish'), ('DE', 'German'), ('IT', 'Italian'), ('PT', 'Portuguese'), ('NL', 'Dutch')], default='EN', help_text='Primary language for this group', max_length=10)),
                ('level', models.CharField(choices=[('beginner', 'Beginner (A1-A2)'), ('intermediate', 'Intermediate (B1-B2)'), ('advanced', 'Advanced (C1-C2)'), ('mixed', 'Mixed Levels')], default='mixed', max_length=20)),
                ('group_type', models.CharField(choices=[('conversation', 'Conversation Practice'), ('grammar', 'Grammar Study'), ('vocabulary', 'Vocabulary Building'), ('reading', 'Reading Club'), ('writing', 'Writing Practice'), ('pronunciation', 'Pronunciation Practice'), ('culture', 'Cultural Exchange'), ('general', 'General Study')], default='general', max_length=20)),
                ('max_members', models.PositiveIntegerField(default=20, help_text='Maximum number of members')),
                ('is_private', models.BooleanField(default=False, help_text='Private groups require invitation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rules', models.TextField(blank=True, help_text='Group rules and guidelines', null=True)),
                ('activity_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('native_speakers_only', models.BooleanField(default=False, help_text='Only allow native speakers')),
                ('requires_language_exchange', models.BooleanField(default=False, help_text='Members must offer language exchange')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'pending'), ('accepted', 'accepted'), ('rejected', 'rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('content', models.TextField(help_text='Post content', max_length=5000, verbose_name='Post Content')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='likes_posts', to=settings.AUTH_USER_MODEL)),
                ('reposts', models.ManyToManyField(blank=True, related_name='reposts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='likes_comments', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='community.post')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, help_text="Brève description de l'utilisateur", null=True)),
                ('learning_languages', models.JSONField(blank=True, help_text="Langues que l'utilisateur souhaite apprendre, exemple : ['French', 'Spanish']", null=True)),
                ('teaching_languages', models.JSONField(blank=True, help_text="Langues que l'utilisateur peut enseigner, exemple : ['English', 'German']", null=True)),
                ('avatar', models.ImageField(blank=True, help_text='Photo de profil', null=True, upload_to='avatars/')),
                ('is_online', models.BooleanField(default=False, help_text="Statut en ligne de l'utilisateur")),
                ('blocked_users', models.ManyToManyField(blank=True, related_name='blocked_by', to='community.profile')),
                ('friends', models.ManyToManyField(blank=True, related_name='friends_with', to='community.profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='community.profile')),
            ],
        ),
        migrations.CreateModel(
            name='LanguageExchangeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_language', models.CharField(default='EN', help_text='Language being taught/practiced', max_length=10)),
                ('secondary_language', models.CharField(default='FR', help_text='Language being learned', max_length=10)),
                ('session_type', models.CharField(choices=[('conversation', 'Conversation Practice'), ('correction', 'Text Correction'), ('pronunciation', 'Pronunciation Help'), ('cultural', 'Cultural Exchange'), ('mixed', 'Mixed Practice')], default='conversation', max_length=20)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('session_notes', models.TextField(blank=True, help_text='Notes from the session')),
                ('teacher_rating', models.PositiveIntegerField(blank=True, help_text='Rating for the teacher (1-5)', null=True)),
                ('learner_rating', models.PositiveIntegerField(blank=True, help_text='Rating for the learner (1-5)', null=True)),
                ('participants', models.ManyToManyField(related_name='exchange_sessions', to='community.profile')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='community.group')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.profile')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_groups', to='community.profile'),
        ),
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='groups', to='community.profile'),
        ),
        migrations.AddField(
            model_name='group',
            name='moderators',
            field=models.ManyToManyField(blank=True, related_name='moderated_groups', to='community.profile'),
        ),
        migrations.CreateModel(
            name='FriendList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('friends', models.ManyToManyField(related_name='listed_in', to='community.profile')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_lists', to='community.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_message', models.DateTimeField(auto_now=True)),
                ('participants', models.ManyToManyField(related_name='conversations', to='community.profile')),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('media', models.FileField(blank=True, null=True, upload_to='chat/media/')),
                ('is_read', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='community.conversation')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='community.profile')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='community.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.ImageField(upload_to='badges/icons/')),
                ('awarded_users', models.ManyToManyField(blank=True, related_name='badges', to='community.profile')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('post', 'Post'), ('comment', 'Comment'), ('like', 'Like'), ('lesson_completed', 'Lesson Completed'), ('friend_added', 'Friend Added'), ('group_joined', 'Group Joined'), ('achievement', 'Achievement Earned'), ('language_exchange', 'Language Exchange Session'), ('study_session', 'Study Session')], max_length=50)),
                ('activity_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_feeds', to='community.profile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, help_text='Raison pour cette recommandation', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='community.profile')),
                ('suggested_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggested_to', to='community.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_filed', to='community.profile')),
                ('reported_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_received', to='community.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Reputation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('level', models.CharField(default='Beginner', max_length=50)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reputation', to='community.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video')], max_length=10)),
                ('content', models.TextField(blank=True, null=True)),
                ('media', models.FileField(blank=True, null=True, upload_to='stories/media/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='community.profile')),
            ],
        ),
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('scheduled_at', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('max_participants', models.PositiveIntegerField(default=10)),
                ('topics', models.JSONField(default=list, help_text='List of topics to cover')),
                ('materials', models.JSONField(default=list, help_text='Study materials and resources')),
                ('is_cancelled', models.BooleanField(default=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_study_sessions', to='community.profile')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_sessions', to='community.group')),
                ('participants', models.ManyToManyField(blank=True, related_name='study_sessions', to='community.profile')),
            ],
            options={
                'ordering': ['scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='UserStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_friends', models.IntegerField(default=0)),
                ('total_messages', models.IntegerField(default=0)),
                ('total_help_sessions', models.IntegerField(default=0)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='community.profile')),
            ],
        ),
        migrations.CreateModel(
            name='LanguagePartnerMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester_teaches', models.CharField(default='EN', help_text='Language requester can teach', max_length=10)),
                ('requester_learns', models.CharField(default='FR', help_text='Language requester wants to learn', max_length=10)),
                ('partner_teaches', models.CharField(default='FR', help_text='Language partner can teach', max_length=10)),
                ('partner_learns', models.CharField(default='EN', help_text='Language partner wants to learn', max_length=10)),
                ('compatibility_score', models.PositiveIntegerField(default=0, help_text='Match quality score (0-100)')),
                ('is_mutual', models.BooleanField(default=False, help_text='Both users can help each other')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('active', 'Active'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_interaction', models.DateTimeField(auto_now=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_matches', to='community.profile')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_requests', to='community.profile')),
            ],
            options={
                'ordering': ['-compatibility_score', '-created_at'],
                'unique_together': {('requester', 'partner')},
            },
        ),
    ]
