# Generated by Django 5.1.10 on 2025-08-15 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_alter_activityfeed_options_alter_group_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Avatar du groupe', null=True, upload_to='groups/avatars/'),
        ),
    ]
