# Generated by Django 5.1.2 on 2024-11-09 16:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('linguify', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('flashcard_id', models.AutoField(primary_key=True, serialize=False)),
                ('flashcard_title', models.CharField(max_length=100)),
                ('image_flashcard', models.ImageField(blank=True, null=True, upload_to='flashcard_images/')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='linguify.theme')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vocabulary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='linguify.vocabulary')),
            ],
        ),
        migrations.CreateModel(
            name='UserFlashcardProgress',
            fields=[
                ('user_flashcard_progress_id', models.AutoField(primary_key=True, serialize=False)),
                ('statut', models.CharField(choices=[('Not started', 'Not started'), ('In progress', 'In progress'), ('Completed', 'Completed')], max_length=100)),
                ('percentage_completion', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('score_flashcard', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('time_study', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('flashcard_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flashcard.flashcard')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
