# Generated by Django 5.1.2 on 2024-11-09 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userflashcardprogress',
            old_name='flashcard_id',
            new_name='flashcard',
        ),
        migrations.RenameField(
            model_name='userflashcardprogress',
            old_name='user_id',
            new_name='user',
        ),
    ]
