# Generated by Django 5.1.2 on 2024-12-25 21:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Grammar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('example', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GrammarModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('is_locked', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_type', models.CharField(choices=[('theory', 'Theory'), ('vocabulary', 'Vocabulary'), ('grammar', 'Grammar'), ('test', 'Test')], max_length=100)),
                ('title_en', models.CharField(max_length=255)),
                ('title_fr', models.CharField(max_length=255)),
                ('title_es', models.CharField(max_length=255)),
                ('title_nl', models.CharField(max_length=255)),
                ('description_en', models.TextField()),
                ('description_fr', models.TextField()),
                ('description_es', models.TextField()),
                ('description_nl', models.TextField()),
                ('estimated_duration', models.IntegerField(help_text='In minutes')),
                ('order', models.PositiveIntegerField(default=1)),
                ('is_complete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('A1', 'Beginner'), ('A2', 'Elementary'), ('B1', 'Intermediate'), ('B2', 'Upper Intermediate'), ('C1', 'Advanced'), ('C2', 'Proficiency')], max_length=100)),
                ('order', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Writing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GrammarRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('grammar_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.grammarmodule')),
            ],
        ),
        migrations.CreateModel(
            name='GrammarRuleContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theory', models.TextField()),
                ('example', models.TextField()),
                ('example_fr', models.TextField()),
                ('example_es', models.TextField()),
                ('example_de', models.TextField()),
                ('example_it', models.TextField()),
                ('example_translation', models.TextField()),
                ('example_translation_fr', models.TextField()),
                ('example_translation_es', models.TextField()),
                ('example_translation_de', models.TextField()),
                ('example_translation_it', models.TextField()),
                ('grammar_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.grammarrule')),
            ],
        ),
        migrations.CreateModel(
            name='GrammarRuleExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('correct_answer', models.CharField(max_length=100)),
                ('incorrect_answers', models.TextField(help_text='Separate the answers with a comma.')),
                ('passing_score', models.FloatField(default=0.8)),
                ('grammar_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.grammarrule')),
            ],
        ),
        migrations.CreateModel(
            name='GrammarRulePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('rule', models.TextField()),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.lesson')),
            ],
        ),
        migrations.AddField(
            model_name='grammarmodule',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.lesson'),
        ),
        migrations.CreateModel(
            name='ExerciseVocabularyMultipleChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(help_text='Question based on example sentence')),
                ('correct_answer', models.CharField(help_text='Correct answer from vocabulary', max_length=255)),
                ('incorrect_answers', models.JSONField(help_text='List of incorrect answers')),
                ('explanation', models.TextField(blank=True, help_text='Explanation for the correct answer', null=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseVocabularyFillBlank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence_fill_blank_en', models.TextField(help_text='Sentence with a blank space')),
                ('sentence_fill_blank_fr', models.TextField(help_text='Sentence with a blank space')),
                ('sentence_fill_blank_es', models.TextField(help_text='Sentence with a blank space')),
                ('sentence_fill_blank_nl', models.TextField(help_text='Sentence with a blank space')),
                ('correct_answer_en', models.CharField(help_text='Correct answer for the blank space', max_length=255)),
                ('correct_answer_fr', models.CharField(max_length=255)),
                ('correct_answer_es', models.CharField(max_length=255)),
                ('correct_answer_nl', models.CharField(max_length=255)),
                ('explanation_en', models.TextField(blank=True, null=True)),
                ('explanation_fr', models.TextField(blank=True, null=True)),
                ('explanation_es', models.TextField(blank=True, null=True)),
                ('explanation_nl', models.TextField(blank=True, null=True)),
                ('hint_en', models.TextField(blank=True, null=True)),
                ('hint_fr', models.TextField(blank=True, null=True)),
                ('hint_es', models.TextField(blank=True, null=True)),
                ('hint_nl', models.TextField(blank=True, null=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseGrammarReordering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence_en', models.TextField(help_text='Sentence to reorder')),
                ('sentence_fr', models.TextField(help_text='Sentence to reorder')),
                ('sentence_es', models.TextField(help_text='Sentence to reorder')),
                ('sentence_nl', models.TextField(help_text='Sentence to reorder')),
                ('correct_order', models.JSONField(help_text='List of words in the correct order')),
                ('explanation', models.TextField(blank=True, help_text='Explanation for the correct order', null=True)),
                ('hint', models.TextField(blank=True, help_text='Hint to help the user', null=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_type', models.CharField(choices=[('Multiple choice', 'Multiple choice'), ('Reordering', 'Reordering'), ('Matching', 'Matching'), ('Question and answer', 'Question and answer'), ('fill_blank', 'Fill in the blanks'), ('True or False', 'True or False')], max_length=100)),
                ('instruction_en', models.TextField(default='Text of the instruction')),
                ('instruction_fr', models.TextField(default='Text of the instruction')),
                ('instruction_es', models.TextField(default='Text of the instruction')),
                ('instruction_nl', models.TextField(default='Text of the instruction')),
                ('order', models.PositiveIntegerField(default=1)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='LearningPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_language', models.CharField(default='EN', max_length=2)),
                ('learning_path', models.CharField(default='Learning Path', max_length=100, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_level', models.ForeignKey(default='A1', on_delete=django.db.models.deletion.CASCADE, to='course.level')),
            ],
        ),
        migrations.CreateModel(
            name='TestRecap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('question', models.TextField()),
                ('correct_answer', models.CharField(max_length=100)),
                ('incorrect_answers', models.TextField(help_text='Separate the answers with a comma.')),
                ('passing_score', models.FloatField(default=0.8)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='TestRecapAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('attempt_date', models.DateTimeField(auto_now_add=True)),
                ('test_recap_passed', models.BooleanField()),
                ('test_recap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.testrecap')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TestRecapExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1)),
                ('test_recap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.testrecap')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=100)),
                ('title_fr', models.CharField(max_length=100)),
                ('title_es', models.CharField(max_length=100)),
                ('title_nl', models.CharField(max_length=100)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('description_fr', models.TextField(blank=True, null=True)),
                ('description_es', models.TextField(blank=True, null=True)),
                ('description_nl', models.TextField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('is_unlocked', models.BooleanField(default=False)),
                ('progress', models.FloatField(default=0.0)),
                ('learning_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.learningpath')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.level')),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.unit'),
        ),
        migrations.CreateModel(
            name='VocabularyList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_en', models.CharField(max_length=100)),
                ('word_fr', models.CharField(max_length=100)),
                ('word_es', models.CharField(max_length=100)),
                ('word_nl', models.CharField(max_length=100)),
                ('definition_en', models.TextField()),
                ('definition_fr', models.TextField()),
                ('definition_es', models.TextField()),
                ('definition_nl', models.TextField()),
                ('example_sentence_en', models.TextField(blank=True, null=True)),
                ('example_sentence_fr', models.TextField(blank=True, null=True)),
                ('example_sentence_es', models.TextField(blank=True, null=True)),
                ('example_sentence_nl', models.TextField(blank=True, null=True)),
                ('word_type_en', models.CharField(max_length=100)),
                ('word_type_fr', models.CharField(max_length=100)),
                ('word_type_es', models.CharField(max_length=100)),
                ('word_type_nl', models.CharField(max_length=100)),
                ('lesson', models.OneToOneField(limit_choices_to={'lesson_type': 'vocabulary'}, on_delete=django.db.models.deletion.CASCADE, related_name='vocabulary_list', to='course.lesson')),
            ],
        ),
    ]
