# Generated by Django 5.1.2 on 2024-12-25 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='learning_path',
        ),
        migrations.AlterField(
            model_name='unit',
            name='level',
            field=models.CharField(choices=[('A1', 'Beginner'), ('A2', 'Elementary'), ('B1', 'Intermediate'), ('B2', 'Upper Intermediate'), ('C1', 'Advanced'), ('C2', 'Proficiency')], max_length=2),
        ),
        migrations.RemoveField(
            model_name='testrecapattempt',
            name='user',
        ),
        migrations.DeleteModel(
            name='LearningPath',
        ),
        migrations.DeleteModel(
            name='Level',
        ),
    ]
