# Generated by Django 5.1.2 on 2024-11-22 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=2, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LessonType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Theory', 'Theory'), ('Vocabulary', 'Vocabulary'), ('Grammar', 'Grammar'), ('Listening', 'Listening'), ('Speaking', 'Speaking'), ('Reading', 'Reading'), ('Writing', 'Writing'), ('Test', 'Test')], default='Theory', max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='activity',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='writing',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='speaking',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='reading',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='vocabulary',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='listening',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='grammar',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='learningpath',
            name='name',
        ),
        migrations.AddField(
            model_name='learningpath',
            name='learning_path',
            field=models.CharField(default='Learning Path', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='learningpath',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lesson',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='unit',
            name='is_unlocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unit',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='example_translation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='lesson',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='course.lesson'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='vocabulary',
            name='example_sentence',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_type', models.CharField(choices=[('Multiple choice', 'Multiple choice'), ('Reordering', 'Reordering'), ('Matching', 'Matching'), ('Question and answer', 'Question and answer'), ('Fill in the blank', 'Fill in the blank'), ('True or False', 'True or False')], max_length=100)),
                ('instruction', models.TextField(default='Text of the instruction')),
                ('order', models.PositiveIntegerField(default=1)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='GrammarRulePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('rule', models.TextField()),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.lesson')),
            ],
        ),
        migrations.AddField(
            model_name='learningpath',
            name='language',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='course.language'),
        ),
        migrations.AddField(
            model_name='grammar',
            name='lesson_type',
            field=models.ForeignKey(default='Grammar', on_delete=django.db.models.deletion.CASCADE, to='course.lessontype'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='lesson_type',
            field=models.ForeignKey(default='Theory', on_delete=django.db.models.deletion.CASCADE, to='course.lessontype'),
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('A1', 'Beginner'), ('A2', 'Elementary'), ('B1', 'Intermediate'), ('B2', 'Upper Intermediate'), ('C1', 'Advanced'), ('C2', 'Proficiency')], max_length=100)),
                ('order', models.PositiveIntegerField(default=1)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.language')),
            ],
        ),
        migrations.AlterField(
            model_name='unit',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.level'),
        ),
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TestRecap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('question', models.TextField()),
                ('correct_answer', models.CharField(max_length=100)),
                ('incorrect_answers', models.TextField(help_text='Separate the answers with a comma.')),
                ('passing_score', models.FloatField(default=0.8)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='TestRecapAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('attempt_date', models.DateTimeField(auto_now_add=True)),
                ('test_recap_passed', models.BooleanField()),
                ('test_recap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.testrecap')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TestRecapExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1)),
                ('test_recap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.testrecap')),
            ],
        ),
        migrations.CreateModel(
            name='VocabularyList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.lesson')),
            ],
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='vocabulary_list',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='course.vocabularylist'),
        ),
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.DeleteModel(
            name='Speaking',
        ),
        migrations.DeleteModel(
            name='Listening',
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
    ]
