# Generated by Django 5.1.2 on 2024-12-26 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_remove_unit_learning_path_alter_unit_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='is_complete',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='is_unlocked',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='progress',
        ),
        migrations.AlterField(
            model_name='unit',
            name='level',
            field=models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], max_length=2),
        ),
    ]
