# Generated by Django 5.1.2 on 2025-01-09 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_remove_lesson_is_complete_remove_unit_is_unlocked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(choices=[('theory', 'Theory'), ('vocabulary', 'Vocabulary'), ('grammar', 'Grammar'), ('pronunciation', 'Pronunciation'), ('listening', 'Listening'), ('speaking', 'Speaking'), ('reading', 'Reading'), ('writing', 'Writing'), ('test', 'Test')], max_length=100),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='course.unit'),
        ),
    ]
