# Generated by Django 5.1.2 on 2025-05-10 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0002_note_difficulty_note_example_sentences_note_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
    ]
