# Generated by Django 5.1.10 on 2025-08-01 21:38

import apps.notebook.models.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0005_alter_note_example_sentences_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='example_sentences',
            field=models.JSONField(blank=True, default=apps.notebook.models.models.default_list),
        ),
        migrations.AlterField(
            model_name='note',
            name='related_words',
            field=models.JSONField(blank=True, default=apps.notebook.models.models.default_list),
        ),
    ]
