# Generated by Django 5.1.10 on 2025-07-06 00:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(help_text="Numero d'etudiant unique", max_length=20, unique=True)),
                ('academic_year', models.CharField(choices=[('1', 'Premiere annee'), ('2', 'Deuxieme annee'), ('3', 'Troisieme annee'), ('4', 'Quatrieme annee'), ('5', 'Cinquieme annee'), ('graduate', 'Etudes superieures'), ('phd', 'Doctorat')], default='1', max_length=10)),
                ('program', models.CharField(help_text='Ex: Informatique, Droit, Medecine...', max_length=100)),
                ('specialization', models.CharField(blank=True, help_text='Specialisation ou concentration', max_length=100)),
                ('enrollment_date', models.DateField(help_text="Date d'inscription")),
                ('expected_graduation', models.DateField(blank=True, help_text='Date de diplome prevue', null=True)),
                ('status', models.CharField(choices=[('active', 'Actif'), ('suspended', 'Suspendu'), ('graduated', 'Diplome'), ('withdrawn', 'Retire')], default='active', max_length=20)),
                ('study_mode', models.CharField(choices=[('full_time', 'Temps plein'), ('part_time', 'Temps partiel'), ('distance', 'A distance')], default='full_time', max_length=20)),
                ('gpa', models.DecimalField(blank=True, decimal_places=2, help_text='Moyenne generale (ex: 3.75)', max_digits=4, null=True)),
                ('credits_earned', models.PositiveIntegerField(default=0, help_text='Credits obtenus')),
                ('credits_required', models.PositiveIntegerField(default=120, help_text='Credits requis pour le diplome')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20)),
                ('emergency_contact_relation', models.CharField(blank=True, help_text='Ex: Parent, Conjoint, Ami...', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='tenants.organization')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil Etudiant',
                'verbose_name_plural': 'Profils Etudiants',
                'ordering': ['student_id'],
            },
        ),
        migrations.CreateModel(
            name='CourseEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(help_text='ID du cours (en attendant le modele Course)', max_length=50)),
                ('course_name', models.CharField(help_text='Nom du cours', max_length=200)),
                ('status', models.CharField(choices=[('enrolled', 'Inscrit'), ('completed', 'Termine'), ('dropped', 'Abandonne'), ('failed', 'Echoue'), ('audit', 'Auditeur')], default='enrolled', max_length=20)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('final_grade', models.CharField(blank=True, help_text='Note finale (A, B, C, D, F ou numerique)', max_length=5)),
                ('credits', models.PositiveIntegerField(default=3)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='students.studentprofile')),
            ],
            options={
                'verbose_name': 'Inscription au Cours',
                'verbose_name_plural': 'Inscriptions aux Cours',
                'unique_together': {('student', 'course_id')},
            },
        ),
    ]
