# Generated by Django 5.1.10 on 2025-07-06 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='organization',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='organization_id',
            field=models.CharField(default='unknown', help_text="ID de l'organisation (automatiquement defini)", max_length=50),
        ),
    ]
