# Generated by Django 5.1.2 on 2025-04-01 11:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('course', '0010_matchingexercise_delete_exercisevocabularyfillblank_and_more'),
        ('progress', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usercontentlessonprogress',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='usercourseprogress',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='userlessonprogress',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='userunitprogress',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='usercontentlessonprogress',
            name='language_code',
            field=models.CharField(default='en', max_length=10),
        ),
        migrations.AddField(
            model_name='usercourseprogress',
            name='language_code',
            field=models.CharField(default='en', max_length=10),
        ),
        migrations.AddField(
            model_name='userlessonprogress',
            name='language_code',
            field=models.CharField(default='en', max_length=10),
        ),
        migrations.AddField(
            model_name='userunitprogress',
            name='language_code',
            field=models.CharField(default='en', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='usercontentlessonprogress',
            unique_together={('user', 'content_lesson', 'language_code')},
        ),
        migrations.AlterUniqueTogether(
            name='usercourseprogress',
            unique_together={('user', 'content_type', 'object_id', 'language_code')},
        ),
        migrations.AlterUniqueTogether(
            name='userlessonprogress',
            unique_together={('user', 'lesson', 'language_code')},
        ),
        migrations.AlterUniqueTogether(
            name='userunitprogress',
            unique_together={('user', 'unit', 'language_code')},
        ),
        migrations.AddIndex(
            model_name='usercontentlessonprogress',
            index=models.Index(fields=['user', 'language_code'], name='progress_us_user_id_268050_idx'),
        ),
        migrations.AddIndex(
            model_name='usercourseprogress',
            index=models.Index(fields=['user', 'language_code'], name='progress_us_user_id_2d75d2_idx'),
        ),
        migrations.AddIndex(
            model_name='userlessonprogress',
            index=models.Index(fields=['user', 'language_code'], name='progress_us_user_id_2d93eb_idx'),
        ),
        migrations.AddIndex(
            model_name='userunitprogress',
            index=models.Index(fields=['user', 'language_code'], name='progress_us_user_id_452f05_idx'),
        ),
    ]
