# Generated by Django 5.1.2 on 2025-04-09 11:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0014_theorycontent_available_languages_and_more'),
        ('progress', '0002_alter_usercontentlessonprogress_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='userlessonprogress',
            name='progress_us_user_id_927d89_idx',
        ),
        migrations.RemoveIndex(
            model_name='userlessonprogress',
            name='progress_us_user_id_e9eb22_idx',
        ),
        migrations.RemoveIndex(
            model_name='userlessonprogress',
            name='progress_us_user_id_2d93eb_idx',
        ),
        migrations.RemoveIndex(
            model_name='userunitprogress',
            name='progress_us_user_id_269a99_idx',
        ),
        migrations.RemoveIndex(
            model_name='userunitprogress',
            name='progress_us_user_id_452f05_idx',
        ),
        migrations.AddIndex(
            model_name='userlessonprogress',
            index=models.Index(fields=['user', 'status', 'language_code'], name='progress_us_user_id_ba2b57_idx'),
        ),
        migrations.AddIndex(
            model_name='userlessonprogress',
            index=models.Index(fields=['user', 'lesson', 'language_code'], name='progress_us_user_id_969d73_idx'),
        ),
        migrations.AddIndex(
            model_name='userunitprogress',
            index=models.Index(fields=['user', 'status', 'language_code'], name='progress_us_user_id_04a8b5_idx'),
        ),
    ]
