# Generated by Django 5.1.2 on 2024-11-17 15:10

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('revision_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('know', models.BooleanField(default=False)),
                ('last_reviewed', models.DateTimeField(default=django.utils.timezone.now)),
                ('word', models.CharField(max_length=100)),
                ('translation', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Revision',
                'verbose_name_plural': 'Revisions',
                'indexes': [models.Index(fields=['word'], name='revision_re_word_f0763d_idx'), models.Index(fields=['translation'], name='revision_re_transla_cad9e9_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserRevisionProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('Not started', 'Not started'), ('In progress', 'In progress'), ('Completed', 'Completed')], default='Not started', max_length=20)),
                ('percentage_completion', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('time_study', models.IntegerField(default=0, help_text='Time studied in minutes', validators=[django.core.validators.MinValueValidator(0)])),
                ('score_revision', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('words_succeeded', models.IntegerField(default=0)),
                ('words_failed', models.IntegerField(default=0)),
                ('words_to_review', models.IntegerField(default=0)),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='revision.revision')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Revision Progress',
                'verbose_name_plural': 'User Revision Progresses',
                'indexes': [models.Index(fields=['user', 'revision'], name='revision_us_user_id_831143_idx')],
            },
        ),
    ]
