# Generated by Django 5.1.2 on 2025-05-31 18:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('learning', 'Learning'), ('memory', 'Memory'), ('notes', 'Notes'), ('conversation_ai', 'Conversation AI')], help_text='Technical code of the application', max_length=50, unique=True)),
                ('display_name', models.CharField(help_text='Name displayed in the user interface', max_length=100)),
                ('description', models.TextField(help_text='Description of the application for users')),
                ('icon_name', models.CharField(help_text='Icon name (Lucide React)', max_length=50)),
                ('color', models.CharField(default='#3B82F6', help_text='Hexadecimal color for the app (#RRGGBB)', max_length=7)),
                ('route_path', models.CharField(help_text='Frontend routing path (e.g., /learning)', max_length=100)),
                ('is_enabled', models.BooleanField(default=True, help_text='Application available on the platform')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order in the interface')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
                'ordering': ['order', 'display_name'],
            },
        ),
        migrations.CreateModel(
            name='UserAppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enabled_apps', models.ManyToManyField(blank=True, help_text='Applications enabled by this user', related_name='enabled_users', to='app_manager.app')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='app_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User App Settings',
                'verbose_name_plural': 'User App Settings',
            },
        ),
    ]
