# Generated by Django 5.0.3 on 2025-10-08 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='last_sync',
        ),
        migrations.RemoveField(
            model_name='coursecontent',
            name='last_sync',
        ),
        migrations.RemoveField(
            model_name='courselesson',
            name='last_sync',
        ),
        migrations.RemoveField(
            model_name='coursesection',
            name='last_sync',
        ),
        migrations.AddField(
            model_name='course',
            name='last_sync_attempt',
            field=models.DateTimeField(blank=True, help_text='Last time a sync was attempted', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='last_sync_success',
            field=models.DateTimeField(blank=True, help_text='Last time a sync succeeded', null=True),
        ),
        migrations.AddField(
            model_name='coursecontent',
            name='last_sync_attempt',
            field=models.DateTimeField(blank=True, help_text='Last time a sync was attempted', null=True),
        ),
        migrations.AddField(
            model_name='coursecontent',
            name='last_sync_success',
            field=models.DateTimeField(blank=True, help_text='Last time a sync succeeded', null=True),
        ),
        migrations.AddField(
            model_name='courselesson',
            name='language',
            field=models.CharField(default='en', help_text='ISO language code (e.g., en, fr, es, nl)', max_length=10),
        ),
        migrations.AddField(
            model_name='courselesson',
            name='last_sync_attempt',
            field=models.DateTimeField(blank=True, help_text='Last time a sync was attempted', null=True),
        ),
        migrations.AddField(
            model_name='courselesson',
            name='last_sync_success',
            field=models.DateTimeField(blank=True, help_text='Last time a sync succeeded', null=True),
        ),
        migrations.AddField(
            model_name='coursesection',
            name='language',
            field=models.CharField(default='en', help_text='ISO language code (e.g., en, fr, es, nl)', max_length=10),
        ),
        migrations.AddField(
            model_name='coursesection',
            name='last_sync_attempt',
            field=models.DateTimeField(blank=True, help_text='Last time a sync was attempted', null=True),
        ),
        migrations.AddField(
            model_name='coursesection',
            name='last_sync_success',
            field=models.DateTimeField(blank=True, help_text='Last time a sync succeeded', null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='backend_id',
            field=models.CharField(blank=True, help_text='ID of this object in the backend system', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='sync_error',
            field=models.TextField(blank=True, help_text='Last sync error message if sync failed', null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='sync_status',
            field=models.CharField(choices=[('pending', 'Pending Sync'), ('synced', 'Synced'), ('failed', 'Sync Failed'), ('manual', 'Manual Entry')], default='pending', help_text='Current synchronization status with backend', max_length=20),
        ),
        migrations.AlterField(
            model_name='coursecategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='coursecontent',
            name='backend_id',
            field=models.CharField(blank=True, help_text='ID of this object in the backend system', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='coursecontent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='coursecontent',
            name='sync_error',
            field=models.TextField(blank=True, help_text='Last sync error message if sync failed', null=True),
        ),
        migrations.AlterField(
            model_name='coursecontent',
            name='sync_status',
            field=models.CharField(choices=[('pending', 'Pending Sync'), ('synced', 'Synced'), ('failed', 'Sync Failed'), ('manual', 'Manual Entry')], default='pending', help_text='Current synchronization status with backend', max_length=20),
        ),
        migrations.AlterField(
            model_name='coursediscount',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='courseenrollment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='courselesson',
            name='backend_id',
            field=models.CharField(blank=True, help_text='ID of this object in the backend system', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='courselesson',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='courselesson',
            name='sync_error',
            field=models.TextField(blank=True, help_text='Last sync error message if sync failed', null=True),
        ),
        migrations.AlterField(
            model_name='courselesson',
            name='sync_status',
            field=models.CharField(choices=[('pending', 'Pending Sync'), ('synced', 'Synced'), ('failed', 'Sync Failed'), ('manual', 'Manual Entry')], default='pending', help_text='Current synchronization status with backend', max_length=20),
        ),
        migrations.AlterField(
            model_name='coursepricing',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='courseresource',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='coursereview',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='coursesection',
            name='backend_id',
            field=models.CharField(blank=True, help_text='ID of this object in the backend system', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='coursesection',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='coursesection',
            name='sync_error',
            field=models.TextField(blank=True, help_text='Last sync error message if sync failed', null=True),
        ),
        migrations.AlterField(
            model_name='coursesection',
            name='sync_status',
            field=models.CharField(choices=[('pending', 'Pending Sync'), ('synced', 'Synced'), ('failed', 'Sync Failed'), ('manual', 'Manual Entry')], default='pending', help_text='Current synchronization status with backend', max_length=20),
        ),
        migrations.AlterField(
            model_name='coursetag',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
