# Generated by Django 5.1.2 on 2025-06-21 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_profanityword'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='profanityword',
            new_name='blog_profan_word_f8a968_idx',
            old_name='blog_profanityword_word_lang_idx',
        ),
        migrations.RenameIndex(
            model_name='profanityword',
            new_name='blog_profan_is_acti_db13dd_idx',
            old_name='blog_profanityword_is_active_idx',
        ),
        migrations.RenameIndex(
            model_name='profanityword',
            new_name='blog_profan_severit_4869ff_idx',
            old_name='blog_profanityword_severity_idx',
        ),
    ]
