# Generated by Django 5.0.4 on 2024-07-03 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_categorie', models.CharField(max_length=100)),
                ('image_categorie', models.ImageField(blank=True, default='images/default.jpg', null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_lesson', models.CharField(max_length=100)),
                ('image_lesson', models.ImageField(blank=True, default='images/default.jpg', null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_activity', models.CharField(choices=[('Vocabulaire', 'Vocabulaire'), ('Video', 'Video'), ('Exercice', 'Exercice'), ('Test', 'Test')], default='Vocabulaire', max_length=100)),
                ('icon_activity', models.ImageField(blank=True, default='images/default.jpg', null=True, upload_to='images/')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platforme.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='Sous_categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_sous_categorie', models.CharField(max_length=100)),
                ('image_sous_categorie', models.ImageField(blank=True, default='images/default.jpg', null=True, upload_to='images/')),
                ('level_language', models.CharField(choices=[('A1-', 'A1-'), ('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], default='A1-', max_length=3)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platforme.categorie')),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='sous_categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platforme.sous_categorie'),
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_video', models.CharField(max_length=100)),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platforme.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='Vocabulaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('translation', models.CharField(max_length=100)),
                ('type_word', models.CharField(max_length=100)),
                ('definition', models.TextField()),
                ('example', models.TextField()),
                ('example_translation', models.TextField()),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platforme.lesson')),
            ],
        ),
    ]
