# Generated by Django 5.0.4 on 2024-07-04 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforme', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocabulaire',
            name='rewiewed',
            field=models.BooleanField(default=False),
        ),
    ]
