# Generated by Django 5.0.4 on 2024-07-03 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforme', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sous_categorie',
            name='level_language',
        ),
        migrations.AddField(
            model_name='lesson',
            name='level_language',
            field=models.CharField(choices=[('A1-', 'A1-'), ('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], default='A1-', max_length=3),
        ),
    ]
