# Generated by Django 5.0.4 on 2024-07-03 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforme', '0002_remove_sous_categorie_level_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='number_activity',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='activity',
            field=models.ForeignKey(blank=True, limit_choices_to={'type_activity': 'Video'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='platforme.activity'),
        ),
        migrations.AddField(
            model_name='vocabulaire',
            name='activity',
            field=models.ForeignKey(blank=True, limit_choices_to={'type_activity': 'Vocabulaire'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='platforme.activity'),
        ),
    ]
