# Generated by Django 5.0.4 on 2024-07-04 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforme', '0003_activity_number_activity_video_activity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='name_lesson',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='number_activity',
        ),
        migrations.RemoveField(
            model_name='vocabulaire',
            name='lesson',
        ),
        migrations.CreateModel(
            name='Exercice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_exercice', models.CharField(max_length=100)),
                ('exercice', models.FileField(blank=True, null=True, upload_to='exercices/')),
                ('activity', models.ForeignKey(blank=True, limit_choices_to={'type_activity': 'Exercice'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='platforme.activity')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platforme.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_test', models.CharField(max_length=100)),
                ('test', models.FileField(blank=True, null=True, upload_to='tests/')),
                ('activity', models.ForeignKey(blank=True, limit_choices_to={'type_activity': 'Test'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='platforme.activity')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platforme.lesson')),
            ],
        ),
    ]
