# Generated by Django 5.1.10 on 2025-08-18 19:55

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEventTypeCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Category name', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Category description')),
                ('color', models.IntegerField(default=0, help_text='Color index for category display', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(11)])),
                ('icon', models.CharField(blank=True, help_text='Icon class for category', max_length=50)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Calendar Event Type Category',
                'verbose_name_plural': 'Calendar Event Type Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CalendarAlarm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Alarm display name', max_length=200)),
                ('alarm_type', models.CharField(choices=[('notification', 'Notification'), ('email', 'Email')], default='notification', help_text='Type of alarm notification', max_length=20)),
                ('duration', models.PositiveIntegerField(help_text="Duration value (e.g. 15 for '15 minutes before')", validators=[django.core.validators.MinValueValidator(1)])),
                ('duration_unit', models.CharField(choices=[('minutes', 'Minutes'), ('hours', 'Hours'), ('days', 'Days'), ('weeks', 'Weeks')], default='minutes', help_text='Unit for duration', max_length=10)),
                ('active', models.BooleanField(default=True)),
                ('default_for_user', models.BooleanField(default=False, help_text='Is this a default alarm for the user?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Calendar Alarm',
                'verbose_name_plural': 'Calendar Alarms',
                'ordering': ['duration', 'duration_unit'],
                'unique_together': {('name', 'duration', 'duration_unit')},
            },
        ),
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Event title', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Event description (supports HTML)')),
                ('location', models.CharField(blank=True, help_text='Event location', max_length=500)),
                ('videocall_location', models.URLField(blank=True, help_text='Video call URL')),
                ('start', models.DateTimeField(help_text='Event start datetime')),
                ('stop', models.DateTimeField(help_text='Event end datetime')),
                ('allday', models.BooleanField(default=False, help_text='All day event')),
                ('duration', models.FloatField(default=0.0, help_text='Duration in minutes', validators=[django.core.validators.MinValueValidator(0)])),
                ('privacy', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('confidential', 'Confidential')], default='public', max_length=20)),
                ('show_as', models.CharField(choices=[('free', 'Free'), ('busy', 'Busy')], default='busy', max_length=10)),
                ('state', models.CharField(choices=[('open', 'Unconfirmed'), ('done', 'Confirmed')], default='open', max_length=10)),
                ('active', models.BooleanField(default=True)),
                ('recurrency', models.BooleanField(default=False, help_text='Is this a recurring event')),
                ('color', models.IntegerField(default=0, help_text='Color index for calendar display (0-11)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(11)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alarm_ids', models.ManyToManyField(blank=True, help_text='Alarms/notifications for this event', related_name='events', to='calendar_app.calendaralarm')),
                ('user_id', models.ForeignKey(help_text='Event organizer', on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Calendar Event',
                'verbose_name_plural': 'Calendar Events',
                'ordering': ['start', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CalendarAttendee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(help_text='Attendee email address', max_length=254)),
                ('common_name', models.CharField(blank=True, help_text='Display name for the attendee', max_length=200)),
                ('state', models.CharField(choices=[('needsAction', 'Needs Action'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('tentative', 'Tentative')], default='needsAction', help_text='Attendee response status', max_length=20)),
                ('availability', models.CharField(choices=[('free', 'Free'), ('busy', 'Busy')], default='busy', help_text='Attendee availability during event', max_length=10)),
                ('access_token', models.CharField(blank=True, help_text='Unique token for invitation access', max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partner_id', models.ForeignKey(blank=True, help_text='User attending the event', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_attendances', to=settings.AUTH_USER_MODEL)),
                ('event_id', models.ForeignKey(help_text='Associated calendar event', on_delete=django.db.models.deletion.CASCADE, related_name='attendee_ids', to='calendar_app.calendarevent')),
            ],
            options={
                'verbose_name': 'Calendar Attendee',
                'verbose_name_plural': 'Calendar Attendees',
                'ordering': ['common_name', 'email'],
            },
        ),
        migrations.CreateModel(
            name='CalendarAlarmInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trigger_time', models.DateTimeField(help_text='When this alarm should trigger')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('triggered', 'Triggered'), ('sent', 'Sent'), ('failed', 'Failed'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('triggered_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alarm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='calendar_app.calendaralarm')),
                ('user', models.ForeignKey(help_text='User who should receive this alarm', on_delete=django.db.models.deletion.CASCADE, related_name='calendar_alarm_instances', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alarm_instances', to='calendar_app.calendarevent')),
            ],
            options={
                'verbose_name': 'Calendar Alarm Instance',
                'verbose_name_plural': 'Calendar Alarm Instances',
                'ordering': ['trigger_time'],
            },
        ),
        migrations.CreateModel(
            name='CalendarEventType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Event type name', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of this event type')),
                ('color', models.IntegerField(default=0, help_text='Color index for calendar display (0-11)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(11)])),
                ('icon', models.CharField(blank=True, help_text="Icon class (e.g., 'bi-calendar-event', 'bi-briefcase')", max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('is_system', models.BooleanField(default=False, help_text='Is this a system-defined event type?')),
                ('default_duration', models.PositiveIntegerField(default=60, help_text='Default duration in minutes for events of this type')),
                ('default_privacy', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('confidential', 'Confidential')], default='public', help_text='Default privacy setting for events of this type', max_length=20)),
                ('default_show_as', models.CharField(choices=[('free', 'Free'), ('busy', 'Busy')], default='busy', help_text='Default availability setting for events of this type', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_alarm_ids', models.ManyToManyField(blank=True, help_text='Default alarms for events of this type', related_name='default_for_event_types', to='calendar_app.calendaralarm')),
            ],
            options={
                'verbose_name': 'Calendar Event Type',
                'verbose_name_plural': 'Calendar Event Types',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='event_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='calendar_app.calendareventtype'),
        ),
        migrations.CreateModel(
            name='CalendarEventTypeExtension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_featured', models.BooleanField(default=False)),
                ('order_in_category', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_types', to='calendar_app.calendareventtypecategory')),
                ('event_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extension', to='calendar_app.calendareventtype')),
            ],
            options={
                'verbose_name': 'Calendar Event Type Extension',
                'verbose_name_plural': 'Calendar Event Type Extensions',
                'ordering': ['order_in_category'],
            },
        ),
        migrations.CreateModel(
            name='CalendarInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=300)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('bounced', 'Bounced')], default='pending', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('response_user_agent', models.CharField(blank=True, max_length=500)),
                ('response_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='calendar_app.calendarattendee')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='calendar_app.calendarevent')),
            ],
            options={
                'verbose_name': 'Calendar Invitation',
                'verbose_name_plural': 'Calendar Invitations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CalendarRecurrence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Human readable recurrence name', max_length=200)),
                ('rrule_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='weekly', help_text='Type of recurrence', max_length=20)),
                ('interval', models.PositiveIntegerField(default=1, help_text='Repeat every X periods')),
                ('monday', models.BooleanField(default=False)),
                ('tuesday', models.BooleanField(default=False)),
                ('wednesday', models.BooleanField(default=False)),
                ('thursday', models.BooleanField(default=False)),
                ('friday', models.BooleanField(default=False)),
                ('saturday', models.BooleanField(default=False)),
                ('sunday', models.BooleanField(default=False)),
                ('month_by', models.CharField(choices=[('date', 'Date of month'), ('day', 'Day of month')], default='date', help_text='Monthly recurrence pattern', max_length=10)),
                ('day', models.PositiveIntegerField(blank=True, help_text='Day of month (1-31)', null=True)),
                ('weekday', models.CharField(blank=True, choices=[('MO', 'Monday'), ('TU', 'Tuesday'), ('WE', 'Wednesday'), ('TH', 'Thursday'), ('FR', 'Friday'), ('SA', 'Saturday'), ('SU', 'Sunday')], help_text='Weekday for monthly recurrence', max_length=2)),
                ('byday', models.CharField(blank=True, help_text='Week of month (-1 to 5)', max_length=10)),
                ('end_type', models.CharField(choices=[('count', 'Number of repetitions'), ('end_date', 'End date'), ('forever', 'Forever')], default='forever', help_text='How the recurrence ends', max_length=20)),
                ('count', models.PositiveIntegerField(blank=True, help_text='Number of occurrences', null=True)),
                ('until', models.DateTimeField(blank=True, help_text='End date for recurrence', null=True)),
                ('dtstart', models.DateTimeField(help_text='Recurrence start datetime')),
                ('event_tz', models.CharField(default='UTC', help_text='Timezone for the events', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_event_id', models.ForeignKey(help_text='The base event for this recurrence', on_delete=django.db.models.deletion.CASCADE, related_name='base_recurrences', to='calendar_app.calendarevent')),
            ],
            options={
                'verbose_name': 'Calendar Recurrence',
                'verbose_name_plural': 'Calendar Recurrences',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='recurrence_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='calendar_app.calendarrecurrence'),
        ),
        migrations.CreateModel(
            name='CalendarRecurrenceException',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('exception_date', models.DateTimeField(help_text='Date of the exception')),
                ('is_deleted', models.BooleanField(default=False, help_text='Is this occurrence deleted?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recurrence_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='calendar_app.calendarrecurrence')),
                ('replacement_event', models.ForeignKey(blank=True, help_text='Replacement event for modified occurrence', null=True, on_delete=django.db.models.deletion.CASCADE, to='calendar_app.calendarevent')),
            ],
            options={
                'verbose_name': 'Calendar Recurrence Exception',
                'verbose_name_plural': 'Calendar Recurrence Exceptions',
                'ordering': ['exception_date'],
            },
        ),
        migrations.AddIndex(
            model_name='calendarattendee',
            index=models.Index(fields=['email'], name='calendar_ap_email_26b183_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarattendee',
            index=models.Index(fields=['state'], name='calendar_ap_state_edf9fb_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarattendee',
            index=models.Index(fields=['access_token'], name='calendar_ap_access__8095a9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='calendarattendee',
            unique_together={('event_id', 'email')},
        ),
        migrations.AddIndex(
            model_name='calendaralarminstance',
            index=models.Index(fields=['trigger_time', 'status'], name='calendar_ap_trigger_94b90e_idx'),
        ),
        migrations.AddIndex(
            model_name='calendaralarminstance',
            index=models.Index(fields=['user', 'status'], name='calendar_ap_user_id_35e311_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='calendaralarminstance',
            unique_together={('alarm', 'event', 'user')},
        ),
        migrations.AddIndex(
            model_name='calendareventtype',
            index=models.Index(fields=['active'], name='calendar_ap_active_8a319a_idx'),
        ),
        migrations.AddIndex(
            model_name='calendareventtype',
            index=models.Index(fields=['is_system'], name='calendar_ap_is_syst_a953f1_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['start', 'stop'], name='calendar_ap_start_03857d_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['user_id', 'start'], name='calendar_ap_user_id_3077a4_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['recurrency'], name='calendar_ap_recurre_826940_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['active'], name='calendar_ap_active_1f8589_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='calendarrecurrenceexception',
            unique_together={('recurrence_id', 'exception_date')},
        ),
    ]
