# Generated by Django 5.1.10 on 2025-08-18 21:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEmailTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Template name for identification', max_length=100)),
                ('template_type', models.CharField(choices=[('invitation', 'Event Invitation'), ('update', 'Event Update'), ('cancellation', 'Event Cancellation'), ('reminder', 'Event Reminder'), ('response_confirmation', 'Response Confirmation'), ('new_attendee', 'New Attendee Added')], help_text='Type of email template', max_length=50)),
                ('language', models.CharField(choices=[('en', 'English'), ('fr', 'Français'), ('es', 'Español'), ('de', 'Deutsch'), ('it', 'Italiano')], default='en', help_text='Language for this template', max_length=5)),
                ('subject_template', models.CharField(help_text='Email subject template (supports Django template syntax)', max_length=200)),
                ('body_html_template', models.TextField(help_text='HTML email body template (supports Django template syntax)')),
                ('body_text_template', models.TextField(blank=True, help_text='Plain text email body template (auto-generated from HTML if empty)')),
                ('active', models.BooleanField(default=True, help_text='Is this template active?')),
                ('is_default', models.BooleanField(default=False, help_text='Is this the default template for this type?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='User who created this template', on_delete=django.db.models.deletion.CASCADE, related_name='created_email_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Calendar Email Template',
                'verbose_name_plural': 'Calendar Email Templates',
                'db_table': 'calendar_email_template',
            },
        ),
        migrations.CreateModel(
            name='CalendarEmailLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('recipient_name', models.CharField(blank=True, max_length=100)),
                ('subject', models.CharField(max_length=200)),
                ('body_html', models.TextField(blank=True)),
                ('body_text', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('bounced', 'Bounced')], default='pending', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('email_provider_id', models.CharField(blank=True, help_text='Provider-specific message ID', max_length=100)),
                ('opens_count', models.IntegerField(default=0)),
                ('clicks_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to='calendar_app.calendarevent')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to='calendar_app.calendaremailtemplate')),
            ],
            options={
                'verbose_name': 'Calendar Email Log',
                'verbose_name_plural': 'Calendar Email Logs',
                'db_table': 'calendar_email_log',
            },
        ),
        migrations.AddIndex(
            model_name='calendaremailtemplate',
            index=models.Index(fields=['template_type', 'language', 'active'], name='calendar_em_templat_6bcd3f_idx'),
        ),
        migrations.AddIndex(
            model_name='calendaremailtemplate',
            index=models.Index(fields=['is_default', 'active'], name='calendar_em_is_defa_c0b005_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='calendaremailtemplate',
            unique_together={('template_type', 'language', 'is_default')},
        ),
        migrations.AddIndex(
            model_name='calendaremaillog',
            index=models.Index(fields=['event', 'recipient_email'], name='calendar_em_event_i_0bf39b_idx'),
        ),
        migrations.AddIndex(
            model_name='calendaremaillog',
            index=models.Index(fields=['status', 'sent_at'], name='calendar_em_status_da178c_idx'),
        ),
        migrations.AddIndex(
            model_name='calendaremaillog',
            index=models.Index(fields=['created_at'], name='calendar_em_created_979cc2_idx'),
        ),
    ]
