# Generated by Django 5.0.4 on 2024-05-23 22:22

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses_languages',
            fields=[
                ('course_languages_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_languages_title', models.CharField(max_length=100)),
                ('course_description', models.TextField(max_length=500)),
                ('course_image', models.ImageField(blank=True, null=True, upload_to='course_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Courses_languages_categories',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100)),
                ('category_description', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Grammar',
            fields=[
                ('grammar_id', models.AutoField(primary_key=True, serialize=False)),
                ('grammar_title', models.CharField(max_length=100)),
                ('grammar_description', models.TextField(max_length=500)),
                ('grammar_example', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('revision_id', models.AutoField(primary_key=True, serialize=False)),
                ('revision_title', models.CharField(max_length=100)),
                ('revision_description', models.TextField(max_length=500)),
                ('word', models.CharField(max_length=100)),
                ('translation', models.CharField(max_length=100)),
                ('last_revision_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('theme_name', models.CharField(max_length=100)),
                ('theme_description', models.TextField(max_length=500)),
                ('theme_image', models.ImageField(blank=True, null=True, upload_to='theme_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('vocabulary_id', models.AutoField(primary_key=True, serialize=False)),
                ('vocabulary_title', models.CharField(max_length=100)),
                ('word', models.CharField(max_length=500)),
                ('translation', models.CharField(max_length=500)),
                ('example_sentence', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Courses_subcategories',
            fields=[
                ('subcategory_id', models.AutoField(primary_key=True, serialize=False)),
                ('subcategory_title', models.CharField(choices=[('Vocabulary', 'Vocabulary'), ('Grammar', 'Grammar')], max_length=100)),
                ('subcategory_description', models.TextField(max_length=500)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='linguify.courses_languages_categories')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('quiz_id', models.AutoField(primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=100)),
                ('correct_translation', models.CharField(max_length=100)),
                ('options', models.JSONField(default=list)),
                ('correct_answer', models.CharField(max_length=100)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('flashcard_id', models.AutoField(primary_key=True, serialize=False)),
                ('flashcard_title', models.CharField(max_length=100)),
                ('image_flashcard', models.ImageField(blank=True, null=True, upload_to='flashcard_images/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='linguify.theme')),
                ('vocabulary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='linguify.vocabulary')),
            ],
        ),
        migrations.CreateModel(
            name='Units',
            fields=[
                ('unit_id', models.AutoField(primary_key=True, serialize=False)),
                ('unit_title', models.CharField(max_length=100)),
                ('unit_description', models.TextField(max_length=500)),
                ('unit_type', models.CharField(max_length=100)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='linguify.courses_languages')),
                ('subcategory_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='linguify.courses_subcategories')),
            ],
        ),
        migrations.CreateModel(
            name='UserFlashcardProgress',
            fields=[
                ('user_flashcard_progress_id', models.AutoField(primary_key=True, serialize=False)),
                ('statut', models.CharField(choices=[('Not started', 'Not started'), ('In progress', 'In progress'), ('Completed', 'Completed')], max_length=100)),
                ('percentage_completion', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('score_flashcard', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('time_study', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('flashcard_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='linguify.flashcard')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserLessonProgress',
            fields=[
                ('user_lesson_progress_id', models.AutoField(primary_key=True, serialize=False)),
                ('statut', models.CharField(max_length=100)),
                ('percentage_completion', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('time_study', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('score_revision', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('score_exercise', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('score_quiz', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='linguify.courses_languages')),
                ('unit_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='linguify.units')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserRevisionProgress',
            fields=[
                ('user_revision_progress_id', models.AutoField(primary_key=True, serialize=False)),
                ('statut', models.CharField(choices=[('Not started', 'Not started'), ('In progress', 'In progress'), ('Completed', 'Completed')], default='Not started', max_length=100)),
                ('percentage_completion', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('time_study', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('score_revision', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('words_succeeded', models.IntegerField(default=0)),
                ('words_failed', models.IntegerField(default=0)),
                ('words_to_review', models.IntegerField(default=0)),
                ('revision_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='linguify.revision')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
