# Generated by Django 5.0.4 on 2024-05-12 22:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses_languages_categories',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100)),
                ('category_description', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Courses_languages',
            fields=[
                ('course_languages_id', models.AutoField(primary_key=True, serialize=False)),
                ('level_target_language', models.CharField(blank=True, choices=[('A1', 'A1 - Beginner'), ('A2', 'A2 - Elementary'), ('B1', 'B1 - Intermediate'), ('B2', 'B2 - Upper Intermediate'), ('C1', 'C1 - Advanced'), ('C2', 'C2 - Proficient')], max_length=168, null=True)),
                ('course_languages_title', models.CharField(max_length=100)),
                ('course_description', models.TextField(max_length=500)),
                ('course_image', models.ImageField(blank=True, null=True, upload_to='course_images/')),
                ('language_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.language')),
            ],
        ),
        migrations.CreateModel(
            name='Courses_subcategories',
            fields=[
                ('subcategory_id', models.AutoField(primary_key=True, serialize=False)),
                ('subcategory_title', models.CharField(choices=[('Vocabulary', 'Vocabulary'), ('Grammar', 'Grammar')], max_length=100)),
                ('subcategory_description', models.TextField(max_length=500)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='linguify.courses_languages_categories')),
            ],
        ),
        migrations.CreateModel(
            name='Flashcards',
            fields=[
                ('flashcard_id', models.AutoField(primary_key=True, serialize=False)),
                ('level_target_language', models.CharField(blank=True, choices=[('A1', 'A1 - Beginner'), ('A2', 'A2 - Elementary'), ('B1', 'B1 - Intermediate'), ('B2', 'B2 - Upper Intermediate'), ('C1', 'C1 - Advanced'), ('C2', 'C2 - Proficient')], max_length=168, null=True)),
                ('flashcard_title', models.CharField(max_length=100)),
                ('word', models.CharField(max_length=500)),
                ('translation', models.CharField(max_length=500)),
                ('example_sentence', models.TextField(max_length=500)),
                ('language_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.language')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Grammar',
            fields=[
                ('grammar_id', models.AutoField(primary_key=True, serialize=False)),
                ('level_target_language', models.CharField(blank=True, choices=[('A1', 'A1 - Beginner'), ('A2', 'A2 - Elementary'), ('B1', 'B1 - Intermediate'), ('B2', 'B2 - Upper Intermediate'), ('C1', 'C1 - Advanced'), ('C2', 'C2 - Proficient')], max_length=168, null=True)),
                ('grammar_title', models.CharField(max_length=100)),
                ('grammar_description', models.TextField(max_length=500)),
                ('grammar_example', models.TextField(max_length=500)),
                ('language_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.language')),
            ],
        ),
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('revision_id', models.AutoField(primary_key=True, serialize=False)),
                ('level_target_language', models.CharField(blank=True, choices=[('A1', 'A1 - Beginner'), ('A2', 'A2 - Elementary'), ('B1', 'B1 - Intermediate'), ('B2', 'B2 - Upper Intermediate'), ('C1', 'C1 - Advanced'), ('C2', 'C2 - Proficient')], max_length=168, null=True)),
                ('revision_title', models.CharField(max_length=100)),
                ('revision_description', models.TextField(max_length=500)),
                ('word', models.CharField(max_length=100)),
                ('translation', models.CharField(max_length=100)),
                ('last_revision_date', models.DateTimeField(auto_now=True)),
                ('language_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.language')),
            ],
        ),
        migrations.CreateModel(
            name='Units',
            fields=[
                ('unit_id', models.AutoField(primary_key=True, serialize=False)),
                ('unit_title', models.CharField(max_length=100)),
                ('unit_description', models.TextField(max_length=500)),
                ('unit_type', models.CharField(max_length=100)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='linguify.courses_languages')),
                ('subcategory_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='linguify.courses_subcategories')),
            ],
        ),
        migrations.CreateModel(
            name='User_Flashcard_Progress',
            fields=[
                ('user_flashcard_progress_id', models.AutoField(primary_key=True, serialize=False)),
                ('statut', models.CharField(choices=[('Not started', 'Not started'), ('In progress', 'In progress'), ('Completed', 'Completed')], max_length=100)),
                ('pourcentage_completion', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('score_flashcard', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('time_study', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('flashcard_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='linguify.flashcards')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='User_Lesson_Progress',
            fields=[
                ('user_lesson_progress_id', models.AutoField(primary_key=True, serialize=False)),
                ('statut', models.CharField(max_length=100)),
                ('pourcentage_completion', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('time_study', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('score_revision', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('score_exercise', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('score_quiz', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='linguify.courses_languages')),
                ('unit_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='linguify.units')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='User_Revision_Progress',
            fields=[
                ('user_revision_progress_id', models.AutoField(primary_key=True, serialize=False)),
                ('statut', models.CharField(max_length=100)),
                ('pourcentage_completion', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('time_study', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('score_revision', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('revision_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='linguify.revision')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('vocabulary_id', models.AutoField(primary_key=True, serialize=False)),
                ('level_target_language', models.CharField(blank=True, choices=[('A1', 'A1 - Beginner'), ('A2', 'A2 - Elementary'), ('B1', 'B1 - Intermediate'), ('B2', 'B2 - Upper Intermediate'), ('C1', 'C1 - Advanced'), ('C2', 'C2 - Proficient')], max_length=168, null=True)),
                ('vocabulary_title', models.CharField(max_length=100)),
                ('word', models.CharField(max_length=500)),
                ('translation', models.CharField(max_length=500)),
                ('example_sentence', models.TextField(max_length=500)),
                ('language_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.language')),
            ],
        ),
    ]
