# Generated by Django 5.0.4 on 2024-10-24 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linguify', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userflashcardprogress',
            name='flashcard_id',
        ),
        migrations.RemoveField(
            model_name='userflashcardprogress',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='Flashcard',
        ),
        migrations.DeleteModel(
            name='UserFlashcardProgress',
        ),
    ]
