# Generated by Django 5.0.4 on 2024-11-03 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linguify', '0002_remove_userflashcardprogress_flashcard_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses_languages',
            name='category_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='linguify.courses_languages_categories'),
            preserve_default=False,
        ),
    ]
