# Generated by Django 5.1.2 on 2024-11-06 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linguify', '0003_courses_languages_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses_languages_categories',
            name='category_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
