# Generated by Django 5.1.2 on 2024-11-07 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linguify', '0004_alter_courses_languages_categories_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses_languages_categories',
            name='category_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
