# Generated by Django 5.1.2 on 2024-11-07 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linguify', '0005_alter_courses_languages_categories_category_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses_languages',
            old_name='category_id',
            new_name='category',
        ),
    ]
