# Generated by Django 5.1.2 on 2024-11-07 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linguify', '0006_rename_category_id_courses_languages_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('language', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
