# Generated by Django 5.1.2 on 2025-03-10 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='daily_goal',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='user',
            name='email_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='interface_language',
            field=models.CharField(default='en', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='listening_exercises',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='public_profile',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='push_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='reading_exercises',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='reminder_time',
            field=models.CharField(default='18:00', max_length=5),
        ),
        migrations.AddField(
            model_name='user',
            name='share_activity',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='share_progress',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='speaking_exercises',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='weekday_reminders',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='weekend_reminders',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='writing_exercises',
            field=models.BooleanField(default=True),
        ),
    ]
