# Generated by Django 5.1.2 on 2025-03-31 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_daily_goal_user_email_notifications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='theme',
            field=models.CharField(default='light', max_length=10),
        ),
    ]
