# Generated by Django 5.2.6 on 2025-09-21 01:04

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20250910_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachprofile',
            name='coaching_languages',
            field=models.CharField(choices=[('EN', 'English'), ('FR', 'French'), ('NL', 'Dutch'), ('ES', 'Spanish')], default='EN', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='daily_goal',
            field=models.IntegerField(default=15, help_text='[DEPRECATED - Use learning_profile]', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='language_level',
            field=models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], default='A1', help_text='[DEPRECATED - Use learning_profile] Your language level', max_length=2),
        ),
        migrations.AlterField(
            model_name='user',
            name='listening_exercises',
            field=models.BooleanField(default=True, help_text='[DEPRECATED - Use learning_profile]'),
        ),
        migrations.AlterField(
            model_name='user',
            name='native_language',
            field=models.CharField(choices=[('EN', 'English'), ('FR', 'French'), ('NL', 'Dutch'), ('ES', 'Spanish')], default='EN', help_text='[DEPRECATED - Use learning_profile] Your native language', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='objectives',
            field=models.CharField(choices=[('Travel', 'Travel'), ('Business', 'Business'), ('Live Abroad', 'Live Abroad'), ('Exam', 'Exam'), ('For Fun', 'For Fun'), ('Work', 'Work'), ('School', 'School'), ('Study', 'Study'), ('Personal', 'Personal')], default='Travel', help_text='[DEPRECATED - Use learning_profile] Your learning objectives', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='reading_exercises',
            field=models.BooleanField(default=True, help_text='[DEPRECATED - Use learning_profile]'),
        ),
        migrations.AlterField(
            model_name='user',
            name='reminder_time',
            field=models.TimeField(default=datetime.time(18, 0), help_text='[DEPRECATED - Use learning_profile]'),
        ),
        migrations.AlterField(
            model_name='user',
            name='speaking_exercises',
            field=models.BooleanField(default=True, help_text='[DEPRECATED - Use learning_profile]'),
        ),
        migrations.AlterField(
            model_name='user',
            name='target_language',
            field=models.CharField(choices=[('EN', 'English'), ('FR', 'French'), ('NL', 'Dutch'), ('ES', 'Spanish')], default='FR', help_text='[DEPRECATED - Use learning_profile] The language you want to learn', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='weekday_reminders',
            field=models.BooleanField(default=True, help_text='[DEPRECATED - Use learning_profile]'),
        ),
        migrations.AlterField(
            model_name='user',
            name='weekend_reminders',
            field=models.BooleanField(default=False, help_text='[DEPRECATED - Use learning_profile]'),
        ),
        migrations.AlterField(
            model_name='user',
            name='writing_exercises',
            field=models.BooleanField(default=True, help_text='[DEPRECATED - Use learning_profile]'),
        ),
    ]
