# Generated by Django 5.2.6 on 2025-09-21 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_coachprofile_coaching_languages_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='daily_goal',
        ),
        migrations.RemoveField(
            model_name='user',
            name='language_level',
        ),
        migrations.RemoveField(
            model_name='user',
            name='listening_exercises',
        ),
        migrations.RemoveField(
            model_name='user',
            name='native_language',
        ),
        migrations.RemoveField(
            model_name='user',
            name='objectives',
        ),
        migrations.RemoveField(
            model_name='user',
            name='reading_exercises',
        ),
        migrations.RemoveField(
            model_name='user',
            name='reminder_time',
        ),
        migrations.RemoveField(
            model_name='user',
            name='speaking_exercises',
        ),
        migrations.RemoveField(
            model_name='user',
            name='target_language',
        ),
        migrations.RemoveField(
            model_name='user',
            name='weekday_reminders',
        ),
        migrations.RemoveField(
            model_name='user',
            name='weekend_reminders',
        ),
        migrations.RemoveField(
            model_name='user',
            name='writing_exercises',
        ),
        migrations.AlterField(
            model_name='coachprofile',
            name='coaching_languages',
            field=models.CharField(help_text='Language codes (e.g., EN, FR, ES)', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='interface_language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'Français'), ('nl', 'Nederlands'), ('es', 'Español')], default='en', max_length=10),
        ),
    ]
