# Generated by Django 5.2.4 on 2025-09-22 13:58

import timezone_field.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_remove_user_daily_goal_remove_user_language_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_device',
            field=models.BooleanField(default=False, help_text='Whether the user is a device or a real user.', verbose_name='device'),
        ),
        migrations.AddField(
            model_name='user',
            name='timezone',
            field=timezone_field.fields.TimeZoneField(choices_display='WITH_GMT_OFFSET', default='Europe/Paris', help_text='The timezone in which the user wants to see times.', use_pytz=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='interface_language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('fr', 'Français'), ('es', 'Español'), ('nl', 'Nederlands')], default='en', help_text='The language in which the user wants to see the interface.', max_length=20, null=True, verbose_name='language'),
        ),
    ]
