# Generated by Django 5.1.2 on 2025-04-20 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_user_birthday_alter_user_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='reminder_time',
            field=models.TimeField(default='18:00', max_length=8),
        ),
    ]
