# Generated by Django 5.1.2 on 2025-04-20 20:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_user_reminder_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='reminder_time',
            field=models.TimeField(default=datetime.time(18, 0)),
        ),
    ]
