# Generated by Django 5.2.6 on 2025-09-23 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_user_is_device_user_timezone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='how_did_you_hear',
            field=models.CharField(blank=True, choices=[('search_engine', 'Search Engine (Google, Bing, etc.)'), ('social_media', 'Social Media'), ('friend_referral', 'Friend or Family'), ('online_ad', 'Online Advertisement'), ('blog_article', 'Blog or Article'), ('app_store', 'App Store'), ('school_university', 'School or University'), ('work_colleague', 'Work or Colleague'), ('other', 'Other')], help_text='How the user heard about the platform', max_length=50, null=True),
        ),
    ]
