# Generated by Django 5.1.2 on 2025-04-20 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_user_reminder_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='target_language',
            field=models.CharField(choices=[('EN', 'English'), ('FR', 'French'), ('NL', 'Dutch'), ('DE', 'German'), ('ES', 'Spanish'), ('IT', 'Italian'), ('PT', 'Portuguese')], default='French', help_text='The language you want to learn', max_length=20),
        ),
    ]
