# Generated by Django 5.0.3 on 2025-09-29 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_update_how_did_you_hear_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Template Name')),
                ('email_type', models.CharField(choices=[('announcement', 'General Announcement'), ('feature', 'New Feature Announcement'), ('survey', 'Survey'), ('feedback', 'Feedback Request'), ('maintenance', 'Maintenance Notice'), ('newsletter', 'Newsletter')], max_length=20, verbose_name='Email Type')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email Template',
                'verbose_name_plural': 'Email Templates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Campaign Name')),
                ('recipient_type', models.CharField(choices=[('all', 'All Users'), ('active', 'Active Users Only'), ('premium', 'Premium Users'), ('custom', 'Custom List')], default='all', max_length=20, verbose_name='Recipients')),
                ('custom_recipients', models.TextField(blank=True, help_text='Email addresses separated by commas (for custom list)')),
                ('test_email', models.EmailField(blank=True, help_text='Send test email to this address before campaign', max_length=254)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed')], default='draft', max_length=20, verbose_name='Status')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='Schedule Send')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Sent At')),
                ('total_recipients', models.IntegerField(default=0, verbose_name='Total Recipients')),
                ('sent_count', models.IntegerField(default=0, verbose_name='Emails Sent')),
                ('failed_count', models.IntegerField(default=0, verbose_name='Failed Emails')),
                ('context_data', models.JSONField(blank=True, default=dict, help_text='JSON data for template variables')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_campaigns', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='authentication.emailtemplate', verbose_name='Email Template')),
            ],
            options={
                'verbose_name': 'Email Campaign',
                'verbose_name_plural': 'Email Campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.EmailField(max_length=254, verbose_name='Recipient')),
                ('subject', models.CharField(max_length=200, verbose_name='Subject')),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('bounced', 'Bounced')], max_length=20, verbose_name='Status')),
                ('error_message', models.TextField(blank=True, verbose_name='Error Message')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Sent At')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='authentication.emailcampaign')),
            ],
            options={
                'verbose_name': 'Email Log',
                'verbose_name_plural': 'Email Logs',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailTemplateTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('fr', 'French'), ('en', 'English'), ('es', 'Spanish'), ('nl', 'Dutch')], max_length=5, verbose_name='Language')),
                ('subject', models.CharField(max_length=200, verbose_name='Subject')),
                ('body_text', models.TextField(help_text='Plain text version', verbose_name='Body (Text)')),
                ('body_html', models.TextField(blank=True, help_text='HTML version (optional)', verbose_name='Body (HTML)')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='authentication.emailtemplate')),
            ],
            options={
                'verbose_name': 'Email Translation',
                'verbose_name_plural': 'Email Translations',
                'ordering': ['language'],
                'unique_together': {('template', 'language')},
            },
        ),
    ]
