# Generated by Django 5.1.2 on 2025-04-20 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_user_target_language'),
    ]

    operations = [
    ]
