# Generated by Django 5.1.2 on 2025-04-20 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_fix_language_data'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='prevent_same_native_and_target_language',
        ),
    ]
