# Generated by Django 5.1.2 on 2025-04-20 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_remove_user_prevent_same_native_and_target_language'),
    ]

    operations = [
    ]
