# Generated by Django 5.0.3 on 2025-10-03 22:50

import apps.authentication.models.models
import apps.authentication.utils.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_enhance_user_feedback_clean'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='userfeedback',
            new_name='authenticat_feedbac_402839_idx',
            old_name='auth_feedb_type_created_idx',
        ),
        migrations.RenameIndex(
            model_name='userfeedback',
            new_name='authenticat_status_e6fbbf_idx',
            old_name='auth_feedb_status_created_idx',
        ),
        migrations.RenameIndex(
            model_name='userfeedback',
            new_name='authenticat_priorit_7a692b_idx',
            old_name='auth_feedb_priority_created_idx',
        ),
        migrations.RenameIndex(
            model_name='userfeedback',
            new_name='authenticat_categor_dd723a_idx',
            old_name='auth_feedb_category_idx',
        ),
        migrations.RenameIndex(
            model_name='userfeedback',
            new_name='authenticat_user_id_b68e61_idx',
            old_name='auth_feedb_user_created_idx',
        ),
        migrations.AlterField(
            model_name='user',
            name='email_notifications',
            field=models.BooleanField(default=True, verbose_name='Receive the notification by emails'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, storage=apps.authentication.utils.storage.ProfileStorage(), upload_to='', validators=[apps.authentication.utils.validators.validate_profile_picture]),
        ),
        migrations.AlterField(
            model_name='user',
            name='push_notifications',
            field=models.BooleanField(default=True, verbose_name='Receive the push notification'),
        ),
        migrations.AlterField(
            model_name='userfeedback',
            name='description',
            field=models.TextField(help_text='Detailed description of the feedback'),
        ),
        migrations.AlterField(
            model_name='userfeedback',
            name='feedback_content',
            field=models.TextField(blank=True, help_text="Legacy field - use 'description' instead", null=True),
        ),
        migrations.AlterField(
            model_name='userfeedback',
            name='feedback_date',
            field=models.DateTimeField(blank=True, help_text="Legacy field - use 'created_at' instead", null=True),
        ),
        migrations.AlterField(
            model_name='userfeedback',
            name='title',
            field=models.CharField(help_text='Brief summary of the feedback', max_length=200),
        ),
    ]
