# Generated by Django 5.1.2 on 2025-04-22 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_auto_20250420_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('N', 'Non-binary'), ('O', 'Other'), ('P', 'Prefer not to say')], max_length=1, null=True),
        ),
    ]
