# Generated by Django 5.0.3 on 2025-10-06 00:43

import apps.authentication.models.models
import apps.authentication.utils.storage
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_rename_auth_feedb_type_created_idx_authenticat_feedbac_402839_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcampaign',
            name='selected_users',
            field=models.ManyToManyField(blank=True, related_name='email_campaigns_received', to=settings.AUTH_USER_MODEL, verbose_name='Selected Users'),
        ),
        migrations.AlterField(
            model_name='emailcampaign',
            name='recipient_type',
            field=models.CharField(choices=[('all', 'All Users'), ('active', 'Active Users Only'), ('premium', 'Premium Users'), ('selected', 'Selected Users'), ('custom', 'Custom List')], default='all', max_length=20, verbose_name='Recipients'),
        ),
    ]
