# Generated by Django 5.1.2 on 2025-05-11 13:51

import apps.authentication.models
import apps.authentication.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_user_terms_acceptance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, storage=apps.authentication.storage.ProfileStorage(), upload_to='profiles', validators=[apps.authentication.models.validate_profile_picture]),
        ),
    ]
