# Generated by Django 5.1.2 on 2025-05-25 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_add_cookie_consent_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='cookieconsent',
            new_name='authenticat_user_id_632a4e_idx',
            old_name='authenticat_user_id_f7d69f_idx',
        ),
        migrations.RenameIndex(
            model_name='cookieconsent',
            new_name='authenticat_session_9fc24d_idx',
            old_name='authenticat_session_4d86e3_idx',
        ),
        migrations.RenameIndex(
            model_name='cookieconsent',
            new_name='authenticat_ip_addr_3ac6be_idx',
            old_name='authenticat_ip_addr_a91c3f_idx',
        ),
        migrations.RenameIndex(
            model_name='cookieconsent',
            new_name='authenticat_version_c6f0e3_idx',
            old_name='authenticat_version_c4b0a9_idx',
        ),
        migrations.RenameIndex(
            model_name='cookieconsent',
            new_name='authenticat_created_4c4232_idx',
            old_name='authenticat_created_4d1e0f_idx',
        ),
        migrations.RenameIndex(
            model_name='cookieconsent',
            new_name='authenticat_is_revo_2ebcdd_idx',
            old_name='authenticat_is_revo_dfe4d3_idx',
        ),
        migrations.RenameIndex(
            model_name='cookieconsentlog',
            new_name='authenticat_consent_61b9e0_idx',
            old_name='authenticat_consent_24b14e_idx',
        ),
        migrations.RenameIndex(
            model_name='cookieconsentlog',
            new_name='authenticat_action_7fe8a1_idx',
            old_name='authenticat_action_85bb12_idx',
        ),
        migrations.RenameIndex(
            model_name='cookieconsentlog',
            new_name='authenticat_created_c998bb_idx',
            old_name='authenticat_created_19b2ad_idx',
        ),
    ]
