# Generated by Django 5.1.10 on 2025-07-14 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_add_phone_number_field'),
        ('authentication', '0021_fix_id_sequence'),
    ]

    operations = [
    ]
