# Generated by Django 5.1.10 on 2025-07-14 12:38

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authentication', '0022_merge_20250714_1418'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='unique_username_case_insensitive',
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Phone number (e.g., +32 123 456 789)', max_length=20, null=True),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('username'), name='unique_username_case_insensitive', violation_error_message='This username is already taken.'),
        ),
    ]
