# Generated by Django 5.1.10 on 2025-07-14 12:56

import apps.authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0023_remove_user_unique_username_case_insensitive_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(db_index=True, max_length=255, unique=True, validators=[apps.authentication.models.validate_username]),
        ),
    ]
