# Generated by Django 5.1.10 on 2025-07-20 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0024_add_username_validation'),
    ]

    operations = [
    ]
