# Generated by Django 5.1.10 on 2025-07-31 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0025_auto_20250720_1359'),
    ]

    operations = [
    ]
