# Generated by Django 5.1.10 on 2025-08-01 21:38

import apps.authentication.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0026_auto_20250731_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(db_index=True, max_length=255, unique=True, validators=[apps.authentication.utils.validators.validate_username_format]),
        ),
    ]
