# Generated by Django 5.1.10 on 2025-08-04 08:35

import apps.authentication.models.models
import apps.authentication.utils.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0027_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, storage=apps.authentication.utils.storage.ProfileStorage(), upload_to='', validators=[apps.authentication.models.models.validate_profile_picture]),
        ),
    ]
