# Generated by Django 5.2.4 on 2025-08-07 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0028_alter_user_profile_picture'),
    ]

    operations = [
    ]
