# Generated by Django 5.1.10 on 2025-08-10 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0030_auto_20250809_2230'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='emailverificationtoken',
            new_name='authenticat_token_e79b2f_idx',
            old_name='authenticat_token_b05041_idx',
        ),
        migrations.RenameIndex(
            model_name='emailverificationtoken',
            new_name='authenticat_user_id_46deae_idx',
            old_name='authenticat_user_id_95e3fc_idx',
        ),
        migrations.RenameIndex(
            model_name='emailverificationtoken',
            new_name='authenticat_expires_ae4371_idx',
            old_name='authenticat_expires_e0ad28_idx',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, error_messages={'unique': 'This email address is already associated with an existing account.'}, max_length=254, unique=True),
        ),
    ]
