# Generated by Django 5.1.10 on 2025-08-27 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0031_rename_authenticat_token_b05041_idx_authenticat_token_e79b2f_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_picture_filename',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_picture_url',
        ),
    ]
