# Generated by Django 5.1.2 on 2025-05-31 23:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_manager', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppDataRetention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disabled_at', models.DateTimeField(help_text='When the app was disabled')),
                ('data_expires_at', models.DateTimeField(help_text='When the user data will be permanently deleted')),
                ('data_deleted', models.BooleanField(default=False, help_text='Whether the data has been permanently deleted')),
                ('data_deleted_at', models.DateTimeField(blank=True, help_text='When the data was permanently deleted', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app', models.ForeignKey(help_text='Application that was disabled', on_delete=django.db.models.deletion.CASCADE, related_name='data_retentions', to='app_manager.app')),
                ('user', models.ForeignKey(help_text='User who disabled the app', on_delete=django.db.models.deletion.CASCADE, related_name='app_data_retentions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'App Data Retention',
                'verbose_name_plural': 'App Data Retentions',
                'ordering': ['-disabled_at'],
                'unique_together': {('user', 'app')},
            },
        ),
    ]
