# Generated by Django 5.1.2 on 2025-06-06 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_manager', '0002_appdataretention'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='category',
            field=models.CharField(default='Uncategorized', help_text='Application category', max_length=100),
        ),
        migrations.AddField(
            model_name='app',
            name='installable',
            field=models.BooleanField(default=True, help_text='Whether the app can be installed'),
        ),
        migrations.AddField(
            model_name='app',
            name='manifest_data',
            field=models.JSONField(blank=True, default=dict, help_text="Additional data from the module's __manifest__.py file"),
        ),
        migrations.AddField(
            model_name='app',
            name='version',
            field=models.CharField(default='1.0.0', help_text='Application version', max_length=20),
        ),
        migrations.AlterField(
            model_name='app',
            name='code',
            field=models.CharField(help_text='Technical code of the application', max_length=50, unique=True),
        ),
    ]
