# Generated by Django 5.1.10 on 2025-08-16 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_manager', '0003_app_category_app_installable_app_manifest_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userappsettings',
            name='app_order',
            field=models.JSONField(blank=True, default=list, help_text='Custom order of apps for this user (array of app display names)'),
        ),
    ]
