# Generated by Django 5.2.4 on 2025-07-23 18:28

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sync_status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Sync'), ('synced', 'Synced'), ('failed', 'Sync Failed')], default='draft', max_length=20)),
                ('backend_id', models.PositiveIntegerField(blank=True, null=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('sync_error', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('suspended', 'Suspendu'), ('rejected', 'Rejeté')], default='pending', max_length=20)),
                ('bio_en', models.TextField(blank=True, help_text='Biography in English')),
                ('bio_fr', models.TextField(blank=True, help_text='Biography in French')),
                ('bio_es', models.TextField(blank=True, help_text='Biography in Spanish')),
                ('bio_nl', models.TextField(blank=True, help_text='Biography in Dutch')),
                ('profile_picture', models.ImageField(blank=True, upload_to='teachers/profiles/')),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('timezone', models.CharField(default='Europe/Paris', max_length=50)),
                ('years_experience', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(50)])),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(10)])),
                ('max_students_per_class', models.PositiveIntegerField(default=1)),
                ('available_for_individual', models.BooleanField(default=True)),
                ('available_for_group', models.BooleanField(default=False)),
                ('bank_account', models.CharField(blank=True, help_text='IBAN', max_length=34)),
                ('tax_id', models.CharField(blank=True, max_length=50)),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_courses_sold', models.PositiveIntegerField(default=0)),
                ('total_hours_taught', models.PositiveIntegerField(default=0)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'teachers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeacherQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('degree', 'Diplôme universitaire'), ('certificate', 'Certificat'), ('teaching_license', "Licence d'enseignement"), ('language_certificate', 'Certificat de langue')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('institution', models.CharField(max_length=200)),
                ('year_obtained', models.PositiveIntegerField()),
                ('certificate_file', models.FileField(blank=True, upload_to='teachers/qualifications/')),
                ('verified', models.BooleanField(default=False)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to='teachers.teacher')),
            ],
            options={
                'db_table': 'teacher_qualifications',
                'ordering': ['-year_obtained'],
            },
        ),
        migrations.CreateModel(
            name='TeacherAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day_of_week', models.IntegerField(choices=[(1, 'Lundi'), (2, 'Mardi'), (3, 'Mercredi'), (4, 'Jeudi'), (5, 'Vendredi'), (6, 'Samedi'), (7, 'Dimanche')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='teachers.teacher')),
            ],
            options={
                'db_table': 'teacher_availability',
                'ordering': ['day_of_week', 'start_time'],
                'unique_together': {('teacher', 'day_of_week', 'start_time')},
            },
        ),
        migrations.CreateModel(
            name='TeacherLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language_code', models.CharField(help_text='Language code (en, fr, es, etc.)', max_length=10)),
                ('language_name', models.CharField(help_text='Language name', max_length=100)),
                ('proficiency', models.CharField(choices=[('native', 'Langue maternelle'), ('fluent', 'Courant'), ('intermediate', 'Intermédiaire'), ('basic', 'Débutant')], max_length=20)),
                ('can_teach', models.BooleanField(default=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='teachers.teacher')),
            ],
            options={
                'db_table': 'teacher_languages',
                'ordering': ['language_name'],
                'unique_together': {('teacher', 'language_code')},
            },
        ),
    ]
