# Generated by Django 5.2.4 on 2025-08-29 18:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('promotion', 'Promotion'), ('new_course', 'Nouveau cours'), ('schedule_change', "Changement d'horaires"), ('general', 'Général'), ('holiday', 'Vacances')], default='general', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('active', 'Actif'), ('expired', 'Expiré'), ('archived', 'Archivé')], default='draft', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('title_en', models.CharField(blank=True, max_length=200)),
                ('title_fr', models.CharField(blank=True, max_length=200)),
                ('title_es', models.CharField(blank=True, max_length=200)),
                ('title_nl', models.CharField(blank=True, max_length=200)),
                ('description_en', models.TextField(blank=True)),
                ('description_fr', models.TextField(blank=True)),
                ('description_es', models.TextField(blank=True)),
                ('description_nl', models.TextField(blank=True)),
                ('discount_percentage', models.PositiveIntegerField(blank=True, help_text='Discount percentage for promotions', null=True)),
                ('special_price', models.DecimalField(blank=True, decimal_places=2, help_text='Special hourly rate', max_digits=6, null=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('languages', models.CharField(blank=True, help_text='Comma-separated language codes (en,fr,es)', max_length=100)),
                ('levels', models.CharField(blank=True, help_text='Comma-separated levels (A1,A2,B1,etc)', max_length=50)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('click_count', models.PositiveIntegerField(default=0)),
                ('booking_count', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('show_on_profile', models.BooleanField(default=True)),
                ('send_notification', models.BooleanField(default=False)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='teachers.teacher')),
            ],
            options={
                'db_table': 'teacher_announcements',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['teacher', 'status'], name='teacher_ann_teacher_f08adb_idx'), models.Index(fields=['start_date', 'end_date'], name='teacher_ann_start_d_4a9fe7_idx'), models.Index(fields=['type', 'is_featured'], name='teacher_ann_type_fba430_idx')],
            },
        ),
    ]
