# Generated by Django 5.0.3 on 2025-10-08 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_teacherannouncement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='last_sync',
        ),
        migrations.AddField(
            model_name='teacher',
            name='last_sync_attempt',
            field=models.DateTimeField(blank=True, help_text='Last time a sync was attempted', null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='last_sync_success',
            field=models.DateTimeField(blank=True, help_text='Last time a sync succeeded', null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='backend_id',
            field=models.CharField(blank=True, help_text='ID of this object in the backend system', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='sync_error',
            field=models.TextField(blank=True, help_text='Last sync error message if sync failed', null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='sync_status',
            field=models.CharField(choices=[('pending', 'Pending Sync'), ('synced', 'Synced'), ('failed', 'Sync Failed'), ('manual', 'Manual Entry')], default='pending', help_text='Current synchronization status with backend', max_length=20),
        ),
        migrations.AlterField(
            model_name='teacherannouncement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='teacheravailability',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='teacherlanguage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='teacherqualification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
