# Generated by Django 4.2.11 on 2024-08-18 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('platforme', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_date', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platforme.activity')),
                ('vocabulaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platforme.vocabulaire')),
            ],
            options={
                'verbose_name': 'Révision',
                'verbose_name_plural': 'Révisions',
            },
        ),
    ]
