# Generated by Django 5.1.2 on 2024-11-12 23:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revision', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revision',
            name='revision_date',
        ),
        migrations.AddField(
            model_name='revision',
            name='know',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='revision',
            name='last_reviewed',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
