# Generated by Django 5.2.4 on 2025-07-27 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentstore', '0002_cmschapter_cmscontentlesson_cmscontentblock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmsunit',
            name='category',
            field=models.CharField(choices=[('popular', '🔥 Populaire'), ('ai_digital', '🤖 IA & Transformation Digitale'), ('sustainability', '🌱 Durabilité'), ('leadership', '👥 Leadership & Compétences Interpersonnelles'), ('business_management', "💼 Management & Stratégie d'Entreprise"), ('data_science', '📊 Data Science & Analyse'), ('education', '🎓 Éducation'), ('finance', '💰 Finance, Investissement & Immobilier'), ('fintech', '🏦 Fintech & Blockchain'), ('healthcare', '⚕️ Santé & Bien-être'), ('hr_talent', '👨\u200d💼 RH & Gestion des Talents'), ('it_cybersecurity', '🔒 IT & Cybersécurité'), ('marketing', '📈 Marketing, Vente & Design'), ('politics_law', '⚖️ Politique, Économie & Droit'), ('project_management', '📋 Gestion de Projet & Supply Chain'), ('languages', '🗣️ Langues'), ('programming', '💻 Programmation'), ('engineering', '🏗️ Ingénierie'), ('sciences', '🔬 Sciences & Maths'), ('creative', '🎨 Arts & Créatif'), ('sports', '🏃 Sport & Fitness'), ('other', '📚 Autre')], default='other', max_length=20),
        ),
    ]
