# Generated by Django 5.0.3 on 2025-10-08 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentstore', '0003_alter_cmsunit_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cmschapter',
            name='last_sync',
        ),
        migrations.RemoveField(
            model_name='cmscontentblock',
            name='last_sync',
        ),
        migrations.RemoveField(
            model_name='cmscontentlesson',
            name='last_sync',
        ),
        migrations.RemoveField(
            model_name='cmslesson',
            name='last_sync',
        ),
        migrations.RemoveField(
            model_name='cmsquizquestion',
            name='last_sync',
        ),
        migrations.RemoveField(
            model_name='cmsresource',
            name='last_sync',
        ),
        migrations.RemoveField(
            model_name='cmstheorycontent',
            name='last_sync',
        ),
        migrations.RemoveField(
            model_name='cmsunit',
            name='last_sync',
        ),
        migrations.RemoveField(
            model_name='cmsvocabularylist',
            name='last_sync',
        ),
        migrations.RemoveField(
            model_name='cmsvocabularyword',
            name='last_sync',
        ),
        migrations.RemoveField(
            model_name='contentlibrary',
            name='last_sync',
        ),
        migrations.RemoveField(
            model_name='courseasset',
            name='last_sync',
        ),
        migrations.RemoveField(
            model_name='coursecontent',
            name='last_sync',
        ),
        migrations.AddField(
            model_name='cmschapter',
            name='language',
            field=models.CharField(default='en', help_text='ISO language code (e.g., en, fr, es, nl)', max_length=10),
        ),
        migrations.AddField(
            model_name='cmschapter',
            name='last_sync_attempt',
            field=models.DateTimeField(blank=True, help_text='Last time a sync was attempted', null=True),
        ),
        migrations.AddField(
            model_name='cmschapter',
            name='last_sync_success',
            field=models.DateTimeField(blank=True, help_text='Last time a sync succeeded', null=True),
        ),
        migrations.AddField(
            model_name='cmscontentblock',
            name='last_sync_attempt',
            field=models.DateTimeField(blank=True, help_text='Last time a sync was attempted', null=True),
        ),
        migrations.AddField(
            model_name='cmscontentblock',
            name='last_sync_success',
            field=models.DateTimeField(blank=True, help_text='Last time a sync succeeded', null=True),
        ),
        migrations.AddField(
            model_name='cmscontentlesson',
            name='language',
            field=models.CharField(default='en', help_text='ISO language code (e.g., en, fr, es, nl)', max_length=10),
        ),
        migrations.AddField(
            model_name='cmscontentlesson',
            name='last_sync_attempt',
            field=models.DateTimeField(blank=True, help_text='Last time a sync was attempted', null=True),
        ),
        migrations.AddField(
            model_name='cmscontentlesson',
            name='last_sync_success',
            field=models.DateTimeField(blank=True, help_text='Last time a sync succeeded', null=True),
        ),
        migrations.AddField(
            model_name='cmslesson',
            name='language',
            field=models.CharField(default='en', help_text='ISO language code (e.g., en, fr, es, nl)', max_length=10),
        ),
        migrations.AddField(
            model_name='cmslesson',
            name='last_sync_attempt',
            field=models.DateTimeField(blank=True, help_text='Last time a sync was attempted', null=True),
        ),
        migrations.AddField(
            model_name='cmslesson',
            name='last_sync_success',
            field=models.DateTimeField(blank=True, help_text='Last time a sync succeeded', null=True),
        ),
        migrations.AddField(
            model_name='cmsquizquestion',
            name='last_sync_attempt',
            field=models.DateTimeField(blank=True, help_text='Last time a sync was attempted', null=True),
        ),
        migrations.AddField(
            model_name='cmsquizquestion',
            name='last_sync_success',
            field=models.DateTimeField(blank=True, help_text='Last time a sync succeeded', null=True),
        ),
        migrations.AddField(
            model_name='cmsresource',
            name='last_sync_attempt',
            field=models.DateTimeField(blank=True, help_text='Last time a sync was attempted', null=True),
        ),
        migrations.AddField(
            model_name='cmsresource',
            name='last_sync_success',
            field=models.DateTimeField(blank=True, help_text='Last time a sync succeeded', null=True),
        ),
        migrations.AddField(
            model_name='cmstheorycontent',
            name='language',
            field=models.CharField(default='en', help_text='ISO language code (e.g., en, fr, es, nl)', max_length=10),
        ),
        migrations.AddField(
            model_name='cmstheorycontent',
            name='last_sync_attempt',
            field=models.DateTimeField(blank=True, help_text='Last time a sync was attempted', null=True),
        ),
        migrations.AddField(
            model_name='cmstheorycontent',
            name='last_sync_success',
            field=models.DateTimeField(blank=True, help_text='Last time a sync succeeded', null=True),
        ),
        migrations.AddField(
            model_name='cmsunit',
            name='language',
            field=models.CharField(default='en', help_text='ISO language code (e.g., en, fr, es, nl)', max_length=10),
        ),
        migrations.AddField(
            model_name='cmsunit',
            name='last_sync_attempt',
            field=models.DateTimeField(blank=True, help_text='Last time a sync was attempted', null=True),
        ),
        migrations.AddField(
            model_name='cmsunit',
            name='last_sync_success',
            field=models.DateTimeField(blank=True, help_text='Last time a sync succeeded', null=True),
        ),
        migrations.AddField(
            model_name='cmsvocabularylist',
            name='language',
            field=models.CharField(default='en', help_text='ISO language code (e.g., en, fr, es, nl)', max_length=10),
        ),
        migrations.AddField(
            model_name='cmsvocabularylist',
            name='last_sync_attempt',
            field=models.DateTimeField(blank=True, help_text='Last time a sync was attempted', null=True),
        ),
        migrations.AddField(
            model_name='cmsvocabularylist',
            name='last_sync_success',
            field=models.DateTimeField(blank=True, help_text='Last time a sync succeeded', null=True),
        ),
        migrations.AddField(
            model_name='cmsvocabularyword',
            name='last_sync_attempt',
            field=models.DateTimeField(blank=True, help_text='Last time a sync was attempted', null=True),
        ),
        migrations.AddField(
            model_name='cmsvocabularyword',
            name='last_sync_success',
            field=models.DateTimeField(blank=True, help_text='Last time a sync succeeded', null=True),
        ),
        migrations.AddField(
            model_name='contentlibrary',
            name='last_sync_attempt',
            field=models.DateTimeField(blank=True, help_text='Last time a sync was attempted', null=True),
        ),
        migrations.AddField(
            model_name='contentlibrary',
            name='last_sync_success',
            field=models.DateTimeField(blank=True, help_text='Last time a sync succeeded', null=True),
        ),
        migrations.AddField(
            model_name='courseasset',
            name='last_sync_attempt',
            field=models.DateTimeField(blank=True, help_text='Last time a sync was attempted', null=True),
        ),
        migrations.AddField(
            model_name='courseasset',
            name='last_sync_success',
            field=models.DateTimeField(blank=True, help_text='Last time a sync succeeded', null=True),
        ),
        migrations.AddField(
            model_name='coursecontent',
            name='last_sync_attempt',
            field=models.DateTimeField(blank=True, help_text='Last time a sync was attempted', null=True),
        ),
        migrations.AddField(
            model_name='coursecontent',
            name='last_sync_success',
            field=models.DateTimeField(blank=True, help_text='Last time a sync succeeded', null=True),
        ),
        migrations.AlterField(
            model_name='cmschapter',
            name='backend_id',
            field=models.CharField(blank=True, help_text='ID of this object in the backend system', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cmschapter',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='cmschapter',
            name='sync_error',
            field=models.TextField(blank=True, help_text='Last sync error message if sync failed', null=True),
        ),
        migrations.AlterField(
            model_name='cmschapter',
            name='sync_status',
            field=models.CharField(choices=[('pending', 'Pending Sync'), ('synced', 'Synced'), ('failed', 'Sync Failed'), ('manual', 'Manual Entry')], default='pending', help_text='Current synchronization status with backend', max_length=20),
        ),
        migrations.AlterField(
            model_name='cmscontentblock',
            name='backend_id',
            field=models.CharField(blank=True, help_text='ID of this object in the backend system', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cmscontentblock',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='cmscontentblock',
            name='sync_error',
            field=models.TextField(blank=True, help_text='Last sync error message if sync failed', null=True),
        ),
        migrations.AlterField(
            model_name='cmscontentblock',
            name='sync_status',
            field=models.CharField(choices=[('pending', 'Pending Sync'), ('synced', 'Synced'), ('failed', 'Sync Failed'), ('manual', 'Manual Entry')], default='pending', help_text='Current synchronization status with backend', max_length=20),
        ),
        migrations.AlterField(
            model_name='cmscontentlesson',
            name='backend_id',
            field=models.CharField(blank=True, help_text='ID of this object in the backend system', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cmscontentlesson',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='cmscontentlesson',
            name='sync_error',
            field=models.TextField(blank=True, help_text='Last sync error message if sync failed', null=True),
        ),
        migrations.AlterField(
            model_name='cmscontentlesson',
            name='sync_status',
            field=models.CharField(choices=[('pending', 'Pending Sync'), ('synced', 'Synced'), ('failed', 'Sync Failed'), ('manual', 'Manual Entry')], default='pending', help_text='Current synchronization status with backend', max_length=20),
        ),
        migrations.AlterField(
            model_name='cmslesson',
            name='backend_id',
            field=models.CharField(blank=True, help_text='ID of this object in the backend system', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cmslesson',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='cmslesson',
            name='sync_error',
            field=models.TextField(blank=True, help_text='Last sync error message if sync failed', null=True),
        ),
        migrations.AlterField(
            model_name='cmslesson',
            name='sync_status',
            field=models.CharField(choices=[('pending', 'Pending Sync'), ('synced', 'Synced'), ('failed', 'Sync Failed'), ('manual', 'Manual Entry')], default='pending', help_text='Current synchronization status with backend', max_length=20),
        ),
        migrations.AlterField(
            model_name='cmsquizquestion',
            name='backend_id',
            field=models.CharField(blank=True, help_text='ID of this object in the backend system', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cmsquizquestion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='cmsquizquestion',
            name='sync_error',
            field=models.TextField(blank=True, help_text='Last sync error message if sync failed', null=True),
        ),
        migrations.AlterField(
            model_name='cmsquizquestion',
            name='sync_status',
            field=models.CharField(choices=[('pending', 'Pending Sync'), ('synced', 'Synced'), ('failed', 'Sync Failed'), ('manual', 'Manual Entry')], default='pending', help_text='Current synchronization status with backend', max_length=20),
        ),
        migrations.AlterField(
            model_name='cmsresource',
            name='backend_id',
            field=models.CharField(blank=True, help_text='ID of this object in the backend system', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cmsresource',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='cmsresource',
            name='sync_error',
            field=models.TextField(blank=True, help_text='Last sync error message if sync failed', null=True),
        ),
        migrations.AlterField(
            model_name='cmsresource',
            name='sync_status',
            field=models.CharField(choices=[('pending', 'Pending Sync'), ('synced', 'Synced'), ('failed', 'Sync Failed'), ('manual', 'Manual Entry')], default='pending', help_text='Current synchronization status with backend', max_length=20),
        ),
        migrations.AlterField(
            model_name='cmstheorycontent',
            name='backend_id',
            field=models.CharField(blank=True, help_text='ID of this object in the backend system', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cmstheorycontent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='cmstheorycontent',
            name='sync_error',
            field=models.TextField(blank=True, help_text='Last sync error message if sync failed', null=True),
        ),
        migrations.AlterField(
            model_name='cmstheorycontent',
            name='sync_status',
            field=models.CharField(choices=[('pending', 'Pending Sync'), ('synced', 'Synced'), ('failed', 'Sync Failed'), ('manual', 'Manual Entry')], default='pending', help_text='Current synchronization status with backend', max_length=20),
        ),
        migrations.AlterField(
            model_name='cmsunit',
            name='backend_id',
            field=models.CharField(blank=True, help_text='ID of this object in the backend system', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cmsunit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='cmsunit',
            name='sync_error',
            field=models.TextField(blank=True, help_text='Last sync error message if sync failed', null=True),
        ),
        migrations.AlterField(
            model_name='cmsunit',
            name='sync_status',
            field=models.CharField(choices=[('pending', 'Pending Sync'), ('synced', 'Synced'), ('failed', 'Sync Failed'), ('manual', 'Manual Entry')], default='pending', help_text='Current synchronization status with backend', max_length=20),
        ),
        migrations.AlterField(
            model_name='cmsvocabularylist',
            name='backend_id',
            field=models.CharField(blank=True, help_text='ID of this object in the backend system', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cmsvocabularylist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='cmsvocabularylist',
            name='sync_error',
            field=models.TextField(blank=True, help_text='Last sync error message if sync failed', null=True),
        ),
        migrations.AlterField(
            model_name='cmsvocabularylist',
            name='sync_status',
            field=models.CharField(choices=[('pending', 'Pending Sync'), ('synced', 'Synced'), ('failed', 'Sync Failed'), ('manual', 'Manual Entry')], default='pending', help_text='Current synchronization status with backend', max_length=20),
        ),
        migrations.AlterField(
            model_name='cmsvocabularyword',
            name='backend_id',
            field=models.CharField(blank=True, help_text='ID of this object in the backend system', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cmsvocabularyword',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='cmsvocabularyword',
            name='sync_error',
            field=models.TextField(blank=True, help_text='Last sync error message if sync failed', null=True),
        ),
        migrations.AlterField(
            model_name='cmsvocabularyword',
            name='sync_status',
            field=models.CharField(choices=[('pending', 'Pending Sync'), ('synced', 'Synced'), ('failed', 'Sync Failed'), ('manual', 'Manual Entry')], default='pending', help_text='Current synchronization status with backend', max_length=20),
        ),
        migrations.AlterField(
            model_name='contentlibrary',
            name='backend_id',
            field=models.CharField(blank=True, help_text='ID of this object in the backend system', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contentlibrary',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='contentlibrary',
            name='sync_error',
            field=models.TextField(blank=True, help_text='Last sync error message if sync failed', null=True),
        ),
        migrations.AlterField(
            model_name='contentlibrary',
            name='sync_status',
            field=models.CharField(choices=[('pending', 'Pending Sync'), ('synced', 'Synced'), ('failed', 'Sync Failed'), ('manual', 'Manual Entry')], default='pending', help_text='Current synchronization status with backend', max_length=20),
        ),
        migrations.AlterField(
            model_name='courseasset',
            name='backend_id',
            field=models.CharField(blank=True, help_text='ID of this object in the backend system', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='courseasset',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='courseasset',
            name='sync_error',
            field=models.TextField(blank=True, help_text='Last sync error message if sync failed', null=True),
        ),
        migrations.AlterField(
            model_name='courseasset',
            name='sync_status',
            field=models.CharField(choices=[('pending', 'Pending Sync'), ('synced', 'Synced'), ('failed', 'Sync Failed'), ('manual', 'Manual Entry')], default='pending', help_text='Current synchronization status with backend', max_length=20),
        ),
        migrations.AlterField(
            model_name='coursecontent',
            name='backend_id',
            field=models.CharField(blank=True, help_text='ID of this object in the backend system', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='coursecontent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='coursecontent',
            name='sync_error',
            field=models.TextField(blank=True, help_text='Last sync error message if sync failed', null=True),
        ),
        migrations.AlterField(
            model_name='coursecontent',
            name='sync_status',
            field=models.CharField(choices=[('pending', 'Pending Sync'), ('synced', 'Synced'), ('failed', 'Sync Failed'), ('manual', 'Manual Entry')], default='pending', help_text='Current synchronization status with backend', max_length=20),
        ),
        migrations.AlterField(
            model_name='coursesettings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
