# Generated by Django 5.2.6 on 2025-09-21 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('info', 'Informational'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error'), ('lesson_reminder', 'Lesson Reminder'), ('flashcard', 'Flashcard Reminder'), ('revision_reminder', 'Revision Reminder'), ('streak', 'Streak'), ('achievement', 'Achievement'), ('system', 'System'), ('progress', 'Progress'), ('terms', 'Terms & Conditions'), ('action_required', 'Action Required'), ('calendar_reminder', 'Event Reminder'), ('calendar_invitation', 'Event Invitation'), ('calendar_update', 'Event Update'), ('calendar_cancellation', 'Event Cancellation'), ('calendar_response', 'Event Response'), ('calendar_sync', 'Calendar Sync')], default='info', max_length=30),
        ),
    ]
