# Generated by Django 5.1.2 on 2025-05-07 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_user_id_543da6_idx',
            old_name='notificatio_user_id_f18226_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_user_id_8ddc07_idx',
            old_name='notificatio_user_id_b86e44_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_user_id_1e4d79_idx',
            old_name='notificatio_user_id_3e44eb_idx',
        ),
        migrations.RenameIndex(
            model_name='notificationdevice',
            new_name='notificatio_user_id_76b6d0_idx',
            old_name='notificatio_user_id_a0ca64_idx',
        ),
        migrations.RenameIndex(
            model_name='notificationsetting',
            new_name='notificatio_user_id_b1a2f4_idx',
            old_name='notificatio_user_id_06a9b0_idx',
        ),
    ]
