# Generated by Django 5.1.2 on 2025-06-16 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_rename_notificatio_user_id_f18226_idx_notificatio_user_id_543da6_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('info', 'Informational'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error'), ('lesson_reminder', 'Lesson Reminder'), ('flashcard', 'Flashcard Reminder'), ('streak', 'Streak'), ('achievement', 'Achievement'), ('system', 'System'), ('progress', 'Progress'), ('terms', 'Terms & Conditions')], default='info', max_length=20),
        ),
    ]
