# Generated by Django 5.1.10 on 2025-08-18 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_alter_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationsetting',
            name='calendar_invitations',
            field=models.BooleanField(default=True, help_text='Event invitations'),
        ),
        migrations.AddField(
            model_name='notificationsetting',
            name='calendar_reminders',
            field=models.BooleanField(default=True, help_text='Event reminders'),
        ),
        migrations.AddField(
            model_name='notificationsetting',
            name='calendar_responses',
            field=models.BooleanField(default=True, help_text='RSVP responses from attendees'),
        ),
        migrations.AddField(
            model_name='notificationsetting',
            name='calendar_sync_notifications',
            field=models.BooleanField(default=False, help_text='Calendar sync status notifications'),
        ),
        migrations.AddField(
            model_name='notificationsetting',
            name='calendar_updates',
            field=models.BooleanField(default=True, help_text='Event updates and changes'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('info', 'Informational'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error'), ('lesson_reminder', 'Lesson Reminder'), ('flashcard', 'Flashcard Reminder'), ('streak', 'Streak'), ('achievement', 'Achievement'), ('system', 'System'), ('progress', 'Progress'), ('terms', 'Terms & Conditions'), ('calendar_reminder', 'Event Reminder'), ('calendar_invitation', 'Event Invitation'), ('calendar_update', 'Event Update'), ('calendar_cancellation', 'Event Cancellation'), ('calendar_response', 'Event Response'), ('calendar_sync', 'Calendar Sync')], default='info', max_length=30),
        ),
    ]
