# Generated by Django 5.1.2 on 2025-01-17 19:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grammar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('example', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GrammarRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(default='Grammar rule title', max_length=255)),
                ('title_fr', models.CharField(default='Grammar rule title', max_length=255)),
                ('title_es', models.CharField(default='Grammar rule title', max_length=255)),
                ('title_nl', models.CharField(default='Grammar rule title', max_length=255)),
                ('content', models.TextField(default='Grammar rule content', help_text='Explication de la règle de grammaire')),
                ('examples', models.JSONField(default=list, help_text="Exemples sous forme JSON. Exemple : [{'en': 'I eat', 'fr': 'Je mange'}]")),
                ('special_cases', models.TextField(blank=True, help_text='Notes sur les cas particuliers ou exceptions (optionnel)', null=True)),
                ('related_tenses', models.JSONField(blank=True, help_text="Liste des temps liés. Exemple : ['Present Simple', 'Past Perfect']", null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_type', models.CharField(choices=[('theory', 'Theory'), ('vocabulary', 'Vocabulary'), ('grammar', 'Grammar'), ('pronunciation', 'Pronunciation'), ('listening', 'Listening'), ('speaking', 'Speaking'), ('reading', 'Reading'), ('writing', 'Writing'), ('test', 'Test')], max_length=100)),
                ('title_en', models.CharField(max_length=255)),
                ('title_fr', models.CharField(max_length=255)),
                ('title_es', models.CharField(max_length=255)),
                ('title_nl', models.CharField(max_length=255)),
                ('description_en', models.TextField()),
                ('description_fr', models.TextField()),
                ('description_es', models.TextField()),
                ('description_nl', models.TextField()),
                ('estimated_duration', models.IntegerField(help_text='In minutes')),
                ('order', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=100)),
                ('title_fr', models.CharField(max_length=100)),
                ('title_es', models.CharField(max_length=100)),
                ('title_nl', models.CharField(max_length=100)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('description_fr', models.TextField(blank=True, null=True)),
                ('description_es', models.TextField(blank=True, null=True)),
                ('description_nl', models.TextField(blank=True, null=True)),
                ('level', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], max_length=2)),
                ('order', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Writing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GrammarRuleContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theory', models.TextField()),
                ('example', models.TextField()),
                ('example_fr', models.TextField()),
                ('example_es', models.TextField()),
                ('example_de', models.TextField()),
                ('example_it', models.TextField()),
                ('example_translation', models.TextField()),
                ('example_translation_fr', models.TextField()),
                ('example_translation_es', models.TextField()),
                ('example_translation_de', models.TextField()),
                ('example_translation_it', models.TextField()),
                ('grammar_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.grammarrule')),
            ],
        ),
        migrations.CreateModel(
            name='GrammarRuleExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('correct_answer', models.CharField(max_length=100)),
                ('incorrect_answers', models.TextField(help_text='Separate the answers with a comma.')),
                ('passing_score', models.FloatField(default=0.8)),
                ('grammar_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.grammarrule')),
            ],
        ),
        migrations.CreateModel(
            name='GrammarRulePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('rule', models.TextField()),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.lesson')),
            ],
        ),
        migrations.AddField(
            model_name='grammarrule',
            name='lesson',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='grammar_rules', to='course.lesson'),
        ),
        migrations.CreateModel(
            name='GrammarModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('is_locked', models.BooleanField(default=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseVocabularyMultipleChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(help_text='Question based on example sentence')),
                ('correct_answer', models.CharField(help_text='Correct answer from vocabulary', max_length=255)),
                ('incorrect_answers', models.JSONField(help_text='List of incorrect answers')),
                ('explanation', models.TextField(blank=True, help_text='Explanation for the correct answer', null=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseVocabularyFillBlank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence_fill_blank_en', models.TextField(help_text='Sentence with a blank space')),
                ('sentence_fill_blank_fr', models.TextField(help_text='Sentence with a blank space')),
                ('sentence_fill_blank_es', models.TextField(help_text='Sentence with a blank space')),
                ('sentence_fill_blank_nl', models.TextField(help_text='Sentence with a blank space')),
                ('correct_answer_en', models.CharField(help_text='Correct answer for the blank space', max_length=255)),
                ('correct_answer_fr', models.CharField(max_length=255)),
                ('correct_answer_es', models.CharField(max_length=255)),
                ('correct_answer_nl', models.CharField(max_length=255)),
                ('explanation_en', models.TextField(blank=True, null=True)),
                ('explanation_fr', models.TextField(blank=True, null=True)),
                ('explanation_es', models.TextField(blank=True, null=True)),
                ('explanation_nl', models.TextField(blank=True, null=True)),
                ('hint_en', models.TextField(blank=True, null=True)),
                ('hint_fr', models.TextField(blank=True, null=True)),
                ('hint_es', models.TextField(blank=True, null=True)),
                ('hint_nl', models.TextField(blank=True, null=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseGrammarReordering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence_en', models.TextField(help_text='Sentence to reorder')),
                ('sentence_fr', models.TextField(help_text='Sentence to reorder')),
                ('sentence_es', models.TextField(help_text='Sentence to reorder')),
                ('sentence_nl', models.TextField(help_text='Sentence to reorder')),
                ('correct_order', models.JSONField(help_text='List of words in the correct order')),
                ('explanation', models.TextField(blank=True, help_text='Explanation for the correct order', null=True)),
                ('hint', models.TextField(blank=True, help_text='Hint to help the user', null=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='ContentLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('Theory', 'Theory'), ('Vocabulary', 'Vocabulary'), ('Grammar', 'Grammar'), ('Multiple choice', 'Multiple choice'), ('Reordering', 'Reordering'), ('Matching', 'Matching'), ('Question and answer', 'Question and answer'), ('fill_blank', 'Fill in the blanks'), ('True or False', 'True or False'), ('Test', 'Test')], db_index=True, max_length=100)),
                ('title_en', models.CharField(max_length=255)),
                ('title_fr', models.CharField(max_length=255)),
                ('title_es', models.CharField(max_length=255)),
                ('title_nl', models.CharField(max_length=255)),
                ('instruction_en', models.TextField(default='Text of the instruction')),
                ('instruction_fr', models.TextField(default='Text of the instruction')),
                ('instruction_es', models.TextField(default='Text of the instruction')),
                ('instruction_nl', models.TextField(default='Text of the instruction')),
                ('estimated_duration', models.IntegerField(help_text='Duration in minutes', validators=[django.core.validators.MinValueValidator(1)])),
                ('order', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_lessons', to='course.lesson')),
            ],
            options={
                'verbose_name': 'Content Lesson',
                'verbose_name_plural': 'Content Lessons',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TestRecap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('question', models.TextField()),
                ('correct_answer', models.CharField(max_length=100)),
                ('incorrect_answers', models.TextField(help_text='Separate the answers with a comma.')),
                ('passing_score', models.FloatField(default=0.8)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='TestRecapAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('attempt_date', models.DateTimeField(auto_now_add=True)),
                ('test_recap_passed', models.BooleanField()),
                ('test_recap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.testrecap')),
            ],
        ),
        migrations.CreateModel(
            name='TestRecapExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1)),
                ('test_recap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.testrecap')),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='course.unit'),
        ),
        migrations.CreateModel(
            name='VocabularyList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_en', models.CharField(max_length=100)),
                ('word_fr', models.CharField(max_length=100)),
                ('word_es', models.CharField(max_length=100)),
                ('word_nl', models.CharField(max_length=100)),
                ('definition_en', models.TextField()),
                ('definition_fr', models.TextField()),
                ('definition_es', models.TextField()),
                ('definition_nl', models.TextField()),
                ('example_sentence_en', models.TextField(blank=True, null=True)),
                ('example_sentence_fr', models.TextField(blank=True, null=True)),
                ('example_sentence_es', models.TextField(blank=True, null=True)),
                ('example_sentence_nl', models.TextField(blank=True, null=True)),
                ('word_type_en', models.CharField(max_length=100)),
                ('word_type_fr', models.CharField(max_length=100)),
                ('word_type_es', models.CharField(max_length=100)),
                ('word_type_nl', models.CharField(max_length=100)),
                ('synonymous_en', models.TextField(blank=True, null=True)),
                ('synonymous_fr', models.TextField(blank=True, null=True)),
                ('synonymous_es', models.TextField(blank=True, null=True)),
                ('synonymous_nl', models.TextField(blank=True, null=True)),
                ('antonymous_en', models.TextField(blank=True, null=True)),
                ('antonymous_fr', models.TextField(blank=True, null=True)),
                ('antonymous_es', models.TextField(blank=True, null=True)),
                ('antonymous_nl', models.TextField(blank=True, null=True)),
                ('content_lesson', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vocabulary_lists', to='course.contentlesson')),
            ],
        ),
        migrations.AddIndex(
            model_name='contentlesson',
            index=models.Index(fields=['content_type'], name='course_cont_content_77d501_idx'),
        ),
        migrations.AddIndex(
            model_name='contentlesson',
            index=models.Index(fields=['order'], name='course_cont_order_0ae4d7_idx'),
        ),
    ]
