# Generated by Django 5.1.10 on 2025-08-04 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
    ]
