# Generated by Django 5.1.2 on 2025-02-04 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultipleChoiceQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_en', models.CharField(max_length=255)),
                ('question_fr', models.CharField(max_length=255)),
                ('question_es', models.CharField(max_length=255)),
                ('question_nl', models.CharField(max_length=255)),
                ('correct_answer_en', models.CharField(max_length=255)),
                ('fake_answer1_en', models.CharField(max_length=255)),
                ('fake_answer2_en', models.CharField(max_length=255)),
                ('fake_answer3_en', models.CharField(max_length=255)),
                ('fake_answer4_en', models.CharField(max_length=255)),
                ('hint_answer_en', models.CharField(blank=True, max_length=255, null=True)),
                ('correct_answer_fr', models.CharField(max_length=255)),
                ('fake_answer1_fr', models.CharField(max_length=255)),
                ('fake_answer2_fr', models.CharField(max_length=255)),
                ('fake_answer3_fr', models.CharField(max_length=255)),
                ('fake_answer4_fr', models.CharField(max_length=255)),
                ('hint_answer_fr', models.CharField(blank=True, max_length=255, null=True)),
                ('correct_answer_es', models.CharField(max_length=255)),
                ('fake_answer1_es', models.CharField(max_length=255)),
                ('fake_answer2_es', models.CharField(max_length=255)),
                ('fake_answer3_es', models.CharField(max_length=255)),
                ('fake_answer4_es', models.CharField(max_length=255)),
                ('hint_answer_es', models.CharField(blank=True, max_length=255, null=True)),
                ('correct_answer_nl', models.CharField(max_length=255)),
                ('fake_answer1_nl', models.CharField(max_length=255)),
                ('fake_answer2_nl', models.CharField(max_length=255)),
                ('fake_answer3_nl', models.CharField(max_length=255)),
                ('fake_answer4_nl', models.CharField(max_length=255)),
                ('hint_answer_nl', models.CharField(blank=True, max_length=255, null=True)),
                ('content_lesson', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='multiple_choices', to='course.contentlesson')),
            ],
        ),
    ]
