# Generated by Django 5.1.2 on 2025-02-04 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_multiplechoicequestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentlesson',
            name='content_type',
            field=models.CharField(choices=[('Theory', 'Theory'), ('Vocabulary', 'Vocabulary'), ('Grammar', 'Grammar'), ('Multiple choice', 'Multiple choice'), ('Numbers', 'Numbers'), ('Reordering', 'Reordering'), ('Matching', 'Matching'), ('Question and answer', 'Question and answer'), ('fill_blank', 'Fill in the blanks'), ('True or False', 'True or False'), ('Test', 'Test')], db_index=True, max_length=100),
        ),
        migrations.CreateModel(
            name='Numbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=255)),
                ('number_en', models.CharField(max_length=255)),
                ('number_fr', models.CharField(max_length=255)),
                ('number_es', models.CharField(max_length=255)),
                ('number_nl', models.CharField(max_length=255)),
                ('content_lesson', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='numbers', to='course.contentlesson')),
            ],
        ),
    ]
