# Generated by Django 5.1.10 on 2025-08-09 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20250804_1053'),
    ]

    operations = [
        # Add missing is_completed column if it doesn't exist
        migrations.RunSQL(
            "ALTER TABLE course_chapter_progress ADD COLUMN IF NOT EXISTS is_completed BOOLEAN DEFAULT FALSE;",
            reverse_sql="ALTER TABLE course_chapter_progress DROP COLUMN IF EXISTS is_completed;"
        ),
        # Add missing time_spent column if it doesn't exist
        migrations.RunSQL(
            "ALTER TABLE course_chapter_progress ADD COLUMN IF NOT EXISTS time_spent INTEGER DEFAULT 0;",
            reverse_sql="ALTER TABLE course_chapter_progress DROP COLUMN IF EXISTS time_spent;"
        ),
        # Add missing lessons_completed column if it doesn't exist
        migrations.RunSQL(
            "ALTER TABLE course_chapter_progress ADD COLUMN IF NOT EXISTS lessons_completed INTEGER DEFAULT 0;",
            reverse_sql="ALTER TABLE course_chapter_progress DROP COLUMN IF EXISTS lessons_completed;"
        ),
    ]
