# Generated by Django 5.1.10 on 2025-08-09 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20250809_2155'),
    ]

    operations = [
        # Add missing time_spent column if it doesn't exist
        migrations.RunSQL(
            "ALTER TABLE course_chapter_progress ADD COLUMN IF NOT EXISTS time_spent INTEGER DEFAULT 0;",
            reverse_sql="ALTER TABLE course_chapter_progress DROP COLUMN IF EXISTS time_spent;"
        ),
        # Add missing lessons_completed column if it doesn't exist
        migrations.RunSQL(
            "ALTER TABLE course_chapter_progress ADD COLUMN IF NOT EXISTS lessons_completed INTEGER DEFAULT 0;",
            reverse_sql="ALTER TABLE course_chapter_progress DROP COLUMN IF EXISTS lessons_completed;"
        ),
    ]
