# Generated by Django 5.1.2 on 2025-02-04 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_contentlesson_content_type_numbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='numbers',
            name='is_reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
