# Generated by Django 5.1.2 on 2025-02-05 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_numbers_is_reviewed'),
    ]

    operations = [
        migrations.CreateModel(
            name='TheoryContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_en', models.TextField()),
                ('content_fr', models.TextField()),
                ('content_es', models.TextField()),
                ('content_nl', models.TextField()),
                ('explication_en', models.TextField()),
                ('explication_fr', models.TextField()),
                ('explication_es', models.TextField()),
                ('explication_nl', models.TextField()),
                ('formula_en', models.TextField(blank=True, null=True)),
                ('formula_fr', models.TextField(blank=True, null=True)),
                ('formula_es', models.TextField(blank=True, null=True)),
                ('formula_nl', models.TextField(blank=True, null=True)),
                ('exception_en', models.TextField(blank=True, null=True)),
                ('exception_fr', models.TextField(blank=True, null=True)),
                ('exception_es', models.TextField(blank=True, null=True)),
                ('exception_nl', models.TextField(blank=True, null=True)),
                ('example_en', models.TextField(blank=True, null=True)),
                ('example_fr', models.TextField(blank=True, null=True)),
                ('example_es', models.TextField(blank=True, null=True)),
                ('example_nl', models.TextField(blank=True, null=True)),
                ('content_lesson', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='theory_content', to='course.contentlesson')),
            ],
        ),
    ]
