# Generated by Django 5.1.10 on 2025-08-10 10:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20250809_2157'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='unit',
            old_name='teacher_cms_id',
            new_name='cms_unit_id',
        ),
        migrations.RenameField(
            model_name='unitprogress',
            old_name='completion_date',
            new_name='completed_at',
        ),
        migrations.RenameField(
            model_name='unitprogress',
            old_name='enrollment_date',
            new_name='started_at',
        ),
        migrations.RemoveField(
            model_name='contentlesson',
            name='content_data',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='professional_field',
        ),
        migrations.RemoveField(
            model_name='unitprogress',
            name='current_lesson',
        ),
        migrations.RemoveField(
            model_name='unitprogress',
            name='is_completed',
        ),
        migrations.AddField(
            model_name='chapter',
            name='is_checkpoint_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contentlesson',
            name='audio_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contentlesson',
            name='text_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contentlesson',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='contentlesson',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='last_sync',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='teacher_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unitprogress',
            name='chapters_completed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='unitprogress',
            name='last_accessed',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='unitprogress',
            name='status',
            field=models.CharField(default='not_started', max_length=20),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='points_reward',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='style',
            field=models.CharField(choices=[('Open Linguify', 'Open Linguify Style'), ('OpenLinguify', 'OpenLinguify Style'), ('custom', 'Custom Style')], default='Open Linguify', max_length=20),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='theme',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='title_en',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='title_es',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='title_fr',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='title_nl',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='contentlesson',
            name='content_type',
            field=models.CharField(choices=[('text', 'Text'), ('video', 'Video'), ('audio', 'Audio'), ('interactive', 'Interactive'), ('mixed', 'Mixed')], default='text', max_length=20),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='estimated_duration',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(choices=[('vocabulary', 'Vocabulary'), ('grammar', 'Grammar'), ('culture', 'Culture'), ('professional', 'Professional')], default='vocabulary', max_length=20),
        ),
        migrations.AlterField(
            model_name='lessonprogress',
            name='best_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='lessonprogress',
            index=models.Index(fields=['user', 'completed_at'], name='course_less_user_id_b7bd96_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonprogress',
            index=models.Index(fields=['lesson', 'completed_at'], name='course_less_lesson__f29cc8_idx'),
        ),
    ]
