# Generated by Django 5.1.2 on 2025-02-10 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_theorycontent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercisegrammarreordering',
            name='correct_order',
        ),
        migrations.RemoveField(
            model_name='exercisegrammarreordering',
            name='lesson',
        ),
        migrations.AddField(
            model_name='exercisegrammarreordering',
            name='content_lesson',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reordering', to='course.contentlesson'),
        ),
    ]
