# Generated by Django 5.1.2 on 2025-03-05 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_remove_exercisegrammarreordering_correct_order_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='vocabularylist',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='unit',
            name='is_started',
            field=models.BooleanField(default=False),
        ),
    ]
