# Generated by Django 5.1.2 on 2025-03-05 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_alter_lesson_options_alter_vocabularylist_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='is_started',
        ),
    ]
