# Generated by Django 5.1.2 on 2025-03-24 12:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_remove_unit_is_started'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grammarrule',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='grammarrulecontent',
            name='grammar_rule',
        ),
        migrations.RemoveField(
            model_name='grammarruleexercise',
            name='grammar_rule',
        ),
        migrations.CreateModel(
            name='FillBlankExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1, help_text="Ordre d'affichage de l'exercice", validators=[django.core.validators.MinValueValidator(1)])),
                ('instructions', models.JSONField(default=dict, help_text='Instructions dans différentes langues')),
                ('sentences', models.JSONField(help_text="Phrases avec emplacement marqué pour le trou (utiliser ___ pour indiquer l'emplacement)")),
                ('answer_options', models.JSONField(help_text='Options de réponse pour chaque langue')),
                ('correct_answers', models.JSONField(help_text='Réponse correcte pour chaque langue')),
                ('hints', models.JSONField(blank=True, help_text='Indices optionnels', null=True)),
                ('explanations', models.JSONField(blank=True, help_text='Explications pour la réponse correcte', null=True)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('tags', models.JSONField(blank=True, default=list, help_text="Tags pour catégoriser l'exercice")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fill_blank_exercises', to='course.contentlesson')),
            ],
            options={
                'verbose_name': 'Fill in the Blank Exercise',
                'verbose_name_plural': 'Fill in the Blank Exercises',
                'ordering': ['content_lesson', 'order'],
            },
        ),
        migrations.DeleteModel(
            name='GrammarModule',
        ),
        migrations.DeleteModel(
            name='GrammarRuleContent',
        ),
        migrations.DeleteModel(
            name='GrammarRule',
        ),
        migrations.DeleteModel(
            name='GrammarRuleExercise',
        ),
        migrations.AddIndex(
            model_name='fillblankexercise',
            index=models.Index(fields=['content_lesson', 'order'], name='course_fill_content_294243_idx'),
        ),
        migrations.AddIndex(
            model_name='fillblankexercise',
            index=models.Index(fields=['difficulty'], name='course_fill_difficu_1cfbaf_idx'),
        ),
    ]
