# Generated by Django 5.1.2 on 2025-03-26 19:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_remove_grammarrule_lesson_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchingExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', help_text="Niveau de difficulté de l'exercice", max_length=10, verbose_name='Difficulté')),
                ('order', models.PositiveIntegerField(default=1, help_text="Position de l'exercice dans la séquence de leçon", validators=[django.core.validators.MinValueValidator(1)], verbose_name='Ordre')),
                ('title_en', models.CharField(default='Match words with their translations', max_length=255, verbose_name='Titre (EN)')),
                ('title_fr', models.CharField(default='Associez les mots à leurs traductions', max_length=255, verbose_name='Titre (FR)')),
                ('title_es', models.CharField(default='Relaciona las palabras con sus traducciones', max_length=255, verbose_name='Titre (ES)')),
                ('title_nl', models.CharField(default='Koppel woorden aan hun vertalingen', max_length=255, verbose_name='Titre (NL)')),
                ('pairs_count', models.PositiveIntegerField(default=8, help_text='Nombre maximal de paires mot-traduction à afficher', validators=[django.core.validators.MinValueValidator(4), django.core.validators.MaxValueValidator(20)], verbose_name='Nombre de paires')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('content_lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matching_exercises', to='course.contentlesson', verbose_name='Leçon associée')),
                ('vocabulary_words', models.ManyToManyField(help_text='Sélectionnez les mots à inclure dans cet exercice', related_name='used_in_matching_exercises', to='course.vocabularylist', verbose_name='Mots de vocabulaire')),
            ],
            options={
                'verbose_name': "Exercice d'association",
                'verbose_name_plural': "Exercices d'association",
                'ordering': ['content_lesson', 'order'],
            },
        ),
        migrations.DeleteModel(
            name='ExerciseVocabularyFillBlank',
        ),
        migrations.AddIndex(
            model_name='matchingexercise',
            index=models.Index(fields=['content_lesson', 'order'], name='course_matc_content_9c0187_idx'),
        ),
        migrations.AddIndex(
            model_name='matchingexercise',
            index=models.Index(fields=['difficulty'], name='course_matc_difficu_2934f9_idx'),
        ),
    ]
