# Generated by Django 5.1.2 on 2025-04-01 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_matchingexercise_delete_exercisevocabularyfillblank_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='estimated_duration',
            field=models.IntegerField(default=0, editable=False, help_text='In minutes'),
        ),
    ]
