# Generated by Django 5.1.2 on 2025-04-06 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_alter_lesson_estimated_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentlesson',
            name='content_type',
            field=models.CharField(choices=[('Theory', 'Theory'), ('Vocabulary', 'Vocabulary'), ('Grammar', 'Grammar'), ('Multiple choice', 'Multiple choice'), ('Numbers', 'Numbers'), ('Reordering', 'Reordering'), ('Matching', 'Matching'), ('Speaking', 'Speaking'), ('Question and answer', 'Question and answer'), ('fill_blank', 'Fill in the blanks'), ('True or False', 'True or False'), ('Test', 'Test')], db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='estimated_duration',
            field=models.IntegerField(default=0, help_text='In minutes'),
        ),
    ]
