# Generated by Django 5.1.2 on 2025-04-06 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_alter_contentlesson_content_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeakingExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speaking_exercises', to='course.contentlesson')),
                ('vocabulary_items', models.ManyToManyField(help_text='Vocabulary items to practice speaking', related_name='speaking_exercises', to='course.vocabularylist', verbose_name='Vocabulary Items')),
            ],
            options={
                'verbose_name': 'Speaking Exercise',
                'verbose_name_plural': 'Speaking Exercises',
                'ordering': ['content_lesson', 'id'],
            },
        ),
    ]
