# Generated by Django 5.1.2 on 2025-04-07 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_speakingexercise'),
    ]

    operations = [
        migrations.AddField(
            model_name='theorycontent',
            name='available_languages',
            field=models.JSONField(blank=True, default=list, help_text='Liste des codes de langue pour lesquelles ce contenu est disponible'),
        ),
        migrations.AddField(
            model_name='theorycontent',
            name='language_specific_content',
            field=models.JSONField(blank=True, default=dict, help_text="Contenu spécifique à une langue qui n'existe pas dans les autres langues"),
        ),
        migrations.AddField(
            model_name='theorycontent',
            name='using_json_format',
            field=models.BooleanField(default=False, help_text='Indique si cette théorie utilise le nouveau format JSON'),
        ),
    ]
