# Generated by Django 5.1.2 on 2025-04-13 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0014_theorycontent_available_languages_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testrecap',
            name='lesson',
        ),
        migrations.AddField(
            model_name='lesson',
            name='professional_field',
            field=models.CharField(blank=True, choices=[('business', 'Business'), ('medical', 'Medical'), ('dentistry', 'Dentistry'), ('advocacy', 'Advocacy'), ('accounting', 'Accounting'), ('business_law', 'Business Law'), ('real_estate', 'Real Estate')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='testrecap',
            name='content_lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_recap', to='course.contentlesson'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(choices=[('vocabulary', 'Vocabulary'), ('grammar', 'Grammar'), ('culture', 'Culture'), ('professional', 'Professional')], max_length=100),
        ),
    ]
