# Generated by Django 5.1.2 on 2025-04-13 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0015_remove_testrecap_lesson_lesson_professional_field_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentlesson',
            name='content_type',
            field=models.CharField(choices=[('Theory', 'Theory'), ('VocabularyList', 'VocabularyList'), ('Grammar', 'Grammar'), ('Multiple choice', 'Multiple choice'), ('Numbers', 'Numbers'), ('Reordering', 'Reordering'), ('Matching', 'Matching'), ('Speaking', 'Speaking'), ('Question and answer', 'Question and answer'), ('fill_blank', 'Fill in the blanks'), ('True or False', 'True or False'), ('Test', 'Test')], db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='description_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='description_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='description_nl',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='professional_field',
            field=models.CharField(blank=True, choices=[('medical_doctor', 'Medical Doctor'), ('nursing', 'Nursing'), ('dentistry', 'Dentistry'), ('pharmacy', 'Pharmacy'), ('physiotherapy', 'Physiotherapy'), ('psychology', 'Psychology'), ('psychiatry', 'Psychiatry'), ('veterinary', 'Veterinary Medicine'), ('optometry', 'Optometry'), ('radiology', 'Radiology'), ('surgery', 'Surgery'), ('public_health', 'Public Health'), ('nutrition', 'Nutrition'), ('law', 'Law'), ('criminal_law', 'Criminal Law'), ('civil_law', 'Civil Law'), ('corporate_law', 'Corporate Law'), ('international_law', 'International Law'), ('intellectual_property', 'Intellectual Property'), ('legal_assistance', 'Legal Assistance'), ('notary', 'Notary'), ('accounting', 'Accounting'), ('auditing', 'Auditing'), ('financial_analysis', 'Financial Analysis'), ('banking', 'Banking'), ('investment', 'Investment'), ('insurance', 'Insurance'), ('tax_consulting', 'Tax Consulting'), ('financial_planning', 'Financial Planning'), ('business_management', 'Business Management'), ('marketing', 'Marketing'), ('sales', 'Sales'), ('human_resources', 'Human Resources'), ('consulting', 'Consulting'), ('entrepreneurship', 'Entrepreneurship'), ('project_management', 'Project Management'), ('operations_management', 'Operations Management'), ('supply_chain', 'Supply Chain Management'), ('real_estate', 'Real Estate'), ('architecture', 'Architecture'), ('civil_engineering', 'Civil Engineering'), ('construction', 'Construction'), ('interior_design', 'Interior Design'), ('urban_planning', 'Urban Planning'), ('property_management', 'Property Management'), ('software_development', 'Software Development'), ('web_development', 'Web Development'), ('data_science', 'Data Science'), ('cybersecurity', 'Cybersecurity'), ('network_administration', 'Network Administration'), ('database_administration', 'Database Administration'), ('it_support', 'IT Support'), ('artificial_intelligence', 'Artificial Intelligence'), ('cloud_computing', 'Cloud Computing'), ('mechanical_engineering', 'Mechanical Engineering'), ('electrical_engineering', 'Electrical Engineering'), ('chemical_engineering', 'Chemical Engineering'), ('aerospace_engineering', 'Aerospace Engineering'), ('industrial_engineering', 'Industrial Engineering'), ('biomedical_engineering', 'Biomedical Engineering'), ('environmental_engineering', 'Environmental Engineering'), ('teaching', 'Teaching'), ('university_professor', 'University Professor'), ('early_childhood_education', 'Early Childhood Education'), ('special_education', 'Special Education'), ('educational_administration', 'Educational Administration'), ('adult_education', 'Adult Education'), ('language_instruction', 'Language Instruction'), ('journalism', 'Journalism'), ('public_relations', 'Public Relations'), ('publishing', 'Publishing'), ('advertising', 'Advertising'), ('broadcasting', 'Broadcasting'), ('film_and_tv_production', 'Film and TV Production'), ('social_media_management', 'Social Media Management'), ('graphic_design', 'Graphic Design'), ('music', 'Music'), ('fine_arts', 'Fine Arts'), ('fashion_design', 'Fashion Design'), ('photography', 'Photography'), ('game_design', 'Game Design'), ('performing_arts', 'Performing Arts'), ('hospitality', 'Hospitality'), ('culinary_arts', 'Culinary Arts'), ('tourism', 'Tourism'), ('event_planning', 'Event Planning'), ('beauty_and_wellness', 'Beauty and Wellness'), ('fitness_and_sports', 'Fitness and Sports'), ('customer_service', 'Customer Service'), ('aviation', 'Aviation'), ('maritime', 'Maritime'), ('logistics', 'Logistics'), ('transportation', 'Transportation'), ('shipping', 'Shipping'), ('railway', 'Railway'), ('biology', 'Biology'), ('chemistry', 'Chemistry'), ('physics', 'Physics'), ('astronomy', 'Astronomy'), ('geology', 'Geology'), ('meteorology', 'Meteorology'), ('oceanography', 'Oceanography'), ('environmental_science', 'Environmental Science'), ('government', 'Government'), ('public_administration', 'Public Administration'), ('diplomacy', 'Diplomacy'), ('military', 'Military'), ('law_enforcement', 'Law Enforcement'), ('firefighting', 'Firefighting'), ('emergency_services', 'Emergency Services'), ('agriculture', 'Agriculture'), ('forestry', 'Forestry'), ('fishing', 'Fishing'), ('conservation', 'Conservation'), ('renewable_energy', 'Renewable Energy'), ('horticulture', 'Horticulture'), ('manufacturing', 'Manufacturing'), ('automotive', 'Automotive'), ('textiles', 'Textiles'), ('food_production', 'Food Production'), ('petroleum', 'Petroleum'), ('mining', 'Mining'), ('pharmaceuticals', 'Pharmaceuticals'), ('social_work', 'Social Work'), ('counseling', 'Counseling'), ('community_development', 'Community Development'), ('non_profit', 'Non-Profit'), ('religious', 'Religious'), ('volunteer_management', 'Volunteer Management'), ('research', 'Research'), ('translation', 'Translation'), ('interpretation', 'Interpretation'), ('museum_and_heritage', 'Museum and Heritage'), ('library_science', 'Library Science'), ('career_counseling', 'Career Counseling')], max_length=100, null=True),
        ),
    ]
