# Generated by Django 5.1.2 on 2025-04-13 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0016_alter_contentlesson_content_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matchingexercise',
            options={'ordering': ['content_lesson', 'order'], 'verbose_name': 'Matching Exercise', 'verbose_name_plural': 'Matching Exercises'},
        ),
    ]
