# Generated by Django 5.1.2 on 2025-04-24 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0018_lesson_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Dernière modification'),
        ),
    ]
