# Generated by Django 5.1.2 on 2025-05-06 22:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0020_fix_duplicate_lesson_orders'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['unit__level', 'unit__order', 'order']},
        ),
        migrations.AlterField(
            model_name='lesson',
            name='estimated_duration',
            field=models.IntegerField(default=0, help_text='In minutes', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['lesson_type'], name='course_less_lesson__d52c8d_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['unit', 'order'], name='course_less_unit_id_147b85_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['professional_field'], name='course_less_profess_8bd9cc_idx'),
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.UniqueConstraint(fields=('unit', 'order'), name='unique_lesson_order_per_unit'),
        ),
    ]