# Generated by Django 5.1.2 on 2025-05-15 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0023_create_testrecap_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testrecapexercise',
            name='test_recap',
        ),
        migrations.AlterField(
            model_name='testrecap',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='testrecap',
            name='title_en',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='testrecap',
            name='title_es',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='testrecap',
            name='title_fr',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='testrecap',
            name='title_nl',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='testrecap',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.DeleteModel(
            name='TestRecapAttempt',
        ),
        migrations.DeleteModel(
            name='TestRecapExercise',
        ),
    ]
