# Generated by Django 5.1.2 on 2025-05-15 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0023_create_testrecap_models'),
    ]

    operations = [
        # No operations - TestRecap models already properly configured
    ]
