# Generated by Django 5.1.2 on 2025-05-15 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0024_remove_testrecapexercise_test_recap_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # No operations - TestRecap models already exist
    ]
