# Generated by Django 5.1.2 on 2025-05-17 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0027_merge_20250515_1514'),
    ]

    operations = [
        # Keep only ContentLesson changes
        migrations.AlterField(
            model_name='contentlesson',
            name='content_type',
            field=models.CharField(choices=[('Theory', 'Theory'), ('VocabularyList', 'VocabularyList'), ('Grammar', 'Grammar'), ('Multiple choice', 'Multiple choice'), ('Numbers', 'Numbers'), ('Reordering', 'Reordering'), ('Matching', 'Matching'), ('Speaking', 'Speaking'), ('Question and answer', 'Question and answer'), ('fill_blank', 'Fill in the blanks'), ('True or False', 'True or False'), ('Test', 'Test'), ('test_recap', 'Test Recap')], db_index=True, max_length=100),
        ),
    ]
