# Generated by Django 5.1.2 on 2025-05-17 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0028_alter_testrecap_correct_answer'),
        ('course', '0029_add_testrecap_fields'),
    ]

    operations = [
    ]
