# Generated by Django 5.1.2 on 2025-05-18 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0030_merge_20250518_0154'),
    ]

    operations = [
    ]
