# Generated by Django 5.1.2 on 2025-05-18 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0031_auto_20250518_0220'),
    ]

    operations = [
        # No operations - TestRecap models already configured
    ]
