# Generated by Django 5.1.2 on 2025-05-27 01:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0032_remove_testrecap_correct_answer_testrecap_question'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testrecapexercise',
            name='test_recap',
        ),
        migrations.AlterModelOptions(
            name='testrecap',
            options={'ordering': ['lesson', 'id'], 'verbose_name': 'Test Recap', 'verbose_name_plural': 'Test Recaps'},
        ),
        migrations.RemoveField(
            model_name='testrecap',
            name='content_lesson',
        ),
        migrations.RemoveField(
            model_name='testrecap',
            name='correct_answer',
        ),
        migrations.RemoveField(
            model_name='testrecap',
            name='incorrect_answers',
        ),
        migrations.AddField(
            model_name='testrecap',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='testrecap',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testrecap',
            name='description_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testrecap',
            name='description_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testrecap',
            name='description_nl',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testrecap',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='testrecap',
            name='lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recap_tests', to='course.lesson'),
        ),
        migrations.AddField(
            model_name='testrecap',
            name='time_limit',
            field=models.PositiveIntegerField(default=600, help_text='Time limit in seconds (0 = no limit)'),
        ),
        migrations.AddField(
            model_name='testrecap',
            name='title_en',
            field=models.CharField(default='Test Recap', max_length=255),
        ),
        migrations.AddField(
            model_name='testrecap',
            name='title_es',
            field=models.CharField(default='Resumen del test', max_length=255),
        ),
        migrations.AddField(
            model_name='testrecap',
            name='title_fr',
            field=models.CharField(default='Récapitulatif du test', max_length=255),
        ),
        migrations.AddField(
            model_name='testrecap',
            name='title_nl',
            field=models.CharField(default='Test samenvatting', max_length=255),
        ),
        migrations.AddField(
            model_name='testrecap',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='testrecap',
            name='passing_score',
            field=models.FloatField(default=0.7, help_text='Minimum score to pass (0.0-1.0)'),
        ),
        migrations.AlterField(
            model_name='testrecap',
            name='question',
            field=models.CharField(default='Test', max_length=255),
        ),
        migrations.AlterField(
            model_name='testrecap',
            name='title',
            field=models.CharField(default='Test Recap', max_length=255),
        ),
        migrations.CreateModel(
            name='TestRecapQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('fill_blank', 'Fill in the Blank'), ('matching', 'Matching'), ('reordering', 'Reordering'), ('speaking', 'Speaking'), ('vocabulary', 'Vocabulary')], max_length=50)),
                ('multiple_choice_id', models.IntegerField(blank=True, null=True)),
                ('fill_blank_id', models.IntegerField(blank=True, null=True)),
                ('matching_id', models.IntegerField(blank=True, null=True)),
                ('reordering_id', models.IntegerField(blank=True, null=True)),
                ('speaking_id', models.IntegerField(blank=True, null=True)),
                ('vocabulary_id', models.IntegerField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=1, help_text='Order in which this question appears in the test')),
                ('points', models.PositiveIntegerField(default=1, help_text='Points awarded for correctly answering this question')),
                ('test_recap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='course.testrecap')),
            ],
            options={
                'verbose_name': 'Test Recap Question',
                'verbose_name_plural': 'Test Recap Questions',
                'ordering': ['test_recap', 'order'],
            },
        ),
        migrations.CreateModel(
            name='TestRecapResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(help_text='Score as percentage (0-100)')),
                ('passed', models.BooleanField(default=False)),
                ('time_spent', models.PositiveIntegerField(help_text='Time spent in seconds')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('detailed_results', models.JSONField(blank=True, default=dict, help_text="Format: {question_id: {correct: bool, time_spent: seconds, answer: user's answer}}")),
                ('test_recap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_results', to='course.testrecap')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Test Recap Result',
                'verbose_name_plural': 'Test Recap Results',
                'ordering': ['-completed_at'],
                'unique_together': {('user', 'test_recap', 'completed_at')},
            },
        ),
        migrations.DeleteModel(
            name='TestRecapAttempt',
        ),
        migrations.DeleteModel(
            name='TestRecapExercise',
        ),
    ]
