# Generated by Django 5.1.10 on 2025-06-22 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0033_remove_testrecapexercise_test_recap_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=100)),
                ('title_fr', models.CharField(max_length=100)),
                ('title_es', models.CharField(max_length=100)),
                ('title_nl', models.CharField(max_length=100)),
                ('theme', models.CharField(help_text="Theme like 'Introductions', 'Greetings', etc.", max_length=50)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('description_fr', models.TextField(blank=True, null=True)),
                ('description_es', models.TextField(blank=True, null=True)),
                ('description_nl', models.TextField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('is_checkpoint_required', models.BooleanField(default=True, help_text='Requires checkpoint test to unlock next chapter')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='course.unit')),
            ],
            options={
                'ordering': ['unit__order', 'order'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='chapter',
            unique_together={('unit', 'order')},
        ),
        migrations.AddField(
            model_name='lesson',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='course.chapter'),
        ),
    ]