# Generated by Django 5.1.10 on 2025-06-22 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0034_add_chapter_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='style',
            field=models.CharField(
                choices=[
                    ('Open Linguify', 'Open Linguify Style (Chapter 1: Introductions)'),
                    ('OpenLinguify', 'OpenLinguify Style (Décrire une maison)'),
                    ('custom', 'Custom Style')
                ],
                default='Open Linguify',
                max_length=20
            ),
        ),
        migrations.AddField(
            model_name='chapter',
            name='points_reward',
            field=models.PositiveIntegerField(
                default=100,
                help_text='Points awarded for completing this chapter'
            ),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='theme',
            field=models.CharField(
                help_text="Theme like 'Introductions', 'Describing house', etc.",
                max_length=50
            ),
        ),
    ]