# Generated by Django 5.1.10 on 2025-07-14 12:42

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0036_auto_20250622_2032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercisevocabularymultiplechoice',
            name='lesson',
        ),
        migrations.DeleteModel(
            name='Grammar',
        ),
        migrations.RemoveField(
            model_name='grammarrulepoint',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='numbers',
            name='content_lesson',
        ),
        migrations.DeleteModel(
            name='Reading',
        ),
        migrations.DeleteModel(
            name='Writing',
        ),
        migrations.AlterModelOptions(
            name='contentlesson',
            options={'ordering': ['lesson__unit__order', 'lesson__order', 'order']},
        ),
        migrations.AlterModelOptions(
            name='fillblankexercise',
            options={'ordering': ['content_lesson__lesson__unit__order', 'content_lesson__lesson__order', 'order']},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['unit__order', 'order']},
        ),
        migrations.AlterModelOptions(
            name='matchingexercise',
            options={'ordering': ['content_lesson__lesson__unit__order', 'content_lesson__lesson__order', 'order']},
        ),
        migrations.AlterModelOptions(
            name='speakingexercise',
            options={},
        ),
        migrations.AlterModelOptions(
            name='testrecap',
            options={'ordering': ['lesson__unit__order', 'lesson__order']},
        ),
        migrations.AlterModelOptions(
            name='testrecapquestion',
            options={'ordering': ['test_recap', 'order']},
        ),
        migrations.AlterModelOptions(
            name='testrecapresult',
            options={'ordering': ['-completed_at']},
        ),
        migrations.AlterModelOptions(
            name='theorycontent',
            options={'verbose_name': 'Theory Content', 'verbose_name_plural': 'Theory Contents'},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='vocabularylist',
            options={'ordering': ['content_lesson__lesson__unit__order', 'content_lesson__lesson__order', 'content_lesson__order']},
        ),
        migrations.RemoveConstraint(
            model_name='lesson',
            name='unique_lesson_order_per_unit',
        ),
        migrations.RemoveIndex(
            model_name='contentlesson',
            name='course_cont_content_77d501_idx',
        ),
        migrations.RemoveIndex(
            model_name='contentlesson',
            name='course_cont_order_0ae4d7_idx',
        ),
        migrations.RemoveIndex(
            model_name='fillblankexercise',
            name='course_fill_content_294243_idx',
        ),
        migrations.RemoveIndex(
            model_name='fillblankexercise',
            name='course_fill_difficu_1cfbaf_idx',
        ),
        migrations.RemoveIndex(
            model_name='lesson',
            name='course_less_lesson__d52c8d_idx',
        ),
        migrations.RemoveIndex(
            model_name='lesson',
            name='course_less_unit_id_147b85_idx',
        ),
        migrations.RemoveIndex(
            model_name='lesson',
            name='course_less_profess_8bd9cc_idx',
        ),
        migrations.RemoveIndex(
            model_name='matchingexercise',
            name='course_matc_content_9c0187_idx',
        ),
        migrations.RemoveIndex(
            model_name='matchingexercise',
            name='course_matc_difficu_2934f9_idx',
        ),
        migrations.AlterUniqueTogether(
            name='testrecapresult',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('unit', 'order')},
        ),
        migrations.RemoveField(
            model_name='matchingexercise',
            name='vocabulary_words',
        ),
        migrations.RemoveField(
            model_name='testrecap',
            name='question',
        ),
        migrations.RemoveField(
            model_name='testrecap',
            name='title',
        ),
        migrations.AlterUniqueTogether(
            name='testrecapquestion',
            unique_together={('test_recap', 'order')},
        ),
        migrations.RemoveField(
            model_name='theorycontent',
            name='example_en',
        ),
        migrations.RemoveField(
            model_name='theorycontent',
            name='example_es',
        ),
        migrations.RemoveField(
            model_name='theorycontent',
            name='example_fr',
        ),
        migrations.RemoveField(
            model_name='theorycontent',
            name='example_nl',
        ),
        migrations.RemoveField(
            model_name='theorycontent',
            name='exception_en',
        ),
        migrations.RemoveField(
            model_name='theorycontent',
            name='exception_es',
        ),
        migrations.RemoveField(
            model_name='theorycontent',
            name='exception_fr',
        ),
        migrations.RemoveField(
            model_name='theorycontent',
            name='exception_nl',
        ),
        migrations.RemoveField(
            model_name='theorycontent',
            name='explication_en',
        ),
        migrations.RemoveField(
            model_name='theorycontent',
            name='explication_es',
        ),
        migrations.RemoveField(
            model_name='theorycontent',
            name='explication_fr',
        ),
        migrations.RemoveField(
            model_name='theorycontent',
            name='explication_nl',
        ),
        migrations.RemoveField(
            model_name='theorycontent',
            name='formula_en',
        ),
        migrations.RemoveField(
            model_name='theorycontent',
            name='formula_es',
        ),
        migrations.RemoveField(
            model_name='theorycontent',
            name='formula_fr',
        ),
        migrations.RemoveField(
            model_name='theorycontent',
            name='formula_nl',
        ),
        migrations.RemoveField(
            model_name='theorycontent',
            name='language_specific_content',
        ),
        migrations.RemoveField(
            model_name='theorycontent',
            name='using_json_format',
        ),
        migrations.AddField(
            model_name='matchingexercise',
            name='vocabulary_items',
            field=models.ManyToManyField(blank=True, to='course.vocabularylist'),
        ),
        migrations.AddField(
            model_name='testrecapquestion',
            name='custom_question_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='testrecapquestion',
            name='matching_exercise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.matchingexercise'),
        ),
        migrations.AddField(
            model_name='testrecapquestion',
            name='multiple_choice_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.multiplechoicequestion'),
        ),
        migrations.AddField(
            model_name='testrecapquestion',
            name='vocabulary_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.vocabularylist'),
        ),
        migrations.AddField(
            model_name='theorycontent',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='theorycontent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='contentlesson',
            name='content_type',
            field=models.CharField(choices=[('vocabulary', 'Vocabulary'), ('grammar', 'Grammar'), ('theory', 'Theory'), ('multiple_choice', 'Multiple Choice'), ('matching', 'Matching'), ('fill_blank', 'Fill in the Blank'), ('speaking', 'Speaking'), ('Test Recap', 'Test Recap'), ('reordering', 'Reordering')], max_length=20),
        ),
        migrations.AlterField(
            model_name='contentlesson',
            name='estimated_duration',
            field=models.PositiveIntegerField(default=5, help_text='Estimated duration in minutes'),
        ),
        migrations.AlterField(
            model_name='contentlesson',
            name='instruction_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contentlesson',
            name='instruction_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contentlesson',
            name='instruction_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contentlesson',
            name='instruction_nl',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contentlesson',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='contentlesson',
            name='title_en',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contentlesson',
            name='title_es',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contentlesson',
            name='title_fr',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contentlesson',
            name='title_nl',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='exercisegrammarreordering',
            name='content_lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grammar_reordering_exercises', to='course.contentlesson'),
        ),
        migrations.AlterField(
            model_name='exercisegrammarreordering',
            name='explanation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exercisegrammarreordering',
            name='hint',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exercisegrammarreordering',
            name='sentence_en',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='exercisegrammarreordering',
            name='sentence_es',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='exercisegrammarreordering',
            name='sentence_fr',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='exercisegrammarreordering',
            name='sentence_nl',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='fillblankexercise',
            name='answer_options',
            field=models.JSONField(default=dict, help_text='Multiple choice options for each language'),
        ),
        migrations.AlterField(
            model_name='fillblankexercise',
            name='correct_answers',
            field=models.JSONField(default=dict, help_text='Correct answers for each language'),
        ),
        migrations.AlterField(
            model_name='fillblankexercise',
            name='difficulty',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20),
        ),
        migrations.AlterField(
            model_name='fillblankexercise',
            name='explanations',
            field=models.JSONField(blank=True, default=dict, help_text='Optional explanations for each language'),
        ),
        migrations.AlterField(
            model_name='fillblankexercise',
            name='hints',
            field=models.JSONField(blank=True, default=dict, help_text='Optional hints for each language'),
        ),
        migrations.AlterField(
            model_name='fillblankexercise',
            name='instructions',
            field=models.JSONField(default=dict, help_text='Instructions in multiple languages'),
        ),
        migrations.AlterField(
            model_name='fillblankexercise',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='fillblankexercise',
            name='sentences',
            field=models.JSONField(default=dict, help_text='Sentences with blanks in multiple languages'),
        ),
        migrations.AlterField(
            model_name='fillblankexercise',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='Tags for categorization'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='estimated_duration',
            field=models.PositiveIntegerField(default=10, help_text='Estimated duration in minutes'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(choices=[('vocabulary', 'Vocabulary'), ('grammar', 'Grammar'), ('culture', 'Culture'), ('professional', 'Professional')], default='vocabulary', max_length=20),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title_en',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title_es',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title_fr',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title_nl',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='matchingexercise',
            name='content_lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matching_exercises', to='course.contentlesson'),
        ),
        migrations.AlterField(
            model_name='matchingexercise',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='matchingexercise',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=10),
        ),
        migrations.AlterField(
            model_name='matchingexercise',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='matchingexercise',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='matchingexercise',
            name='pairs_count',
            field=models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(15)]),
        ),
        migrations.AlterField(
            model_name='matchingexercise',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='matchingexercise',
            name='title_es',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='matchingexercise',
            name='title_fr',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='matchingexercise',
            name='title_nl',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='matchingexercise',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='multiplechoicequestion',
            name='content_lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multiple_choice_questions', to='course.contentlesson'),
        ),
        migrations.AlterField(
            model_name='multiplechoicequestion',
            name='correct_answer_en',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='multiplechoicequestion',
            name='correct_answer_es',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='multiplechoicequestion',
            name='correct_answer_fr',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='multiplechoicequestion',
            name='correct_answer_nl',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='multiplechoicequestion',
            name='fake_answer1_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='multiplechoicequestion',
            name='fake_answer1_es',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='multiplechoicequestion',
            name='fake_answer1_fr',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='multiplechoicequestion',
            name='fake_answer1_nl',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='multiplechoicequestion',
            name='fake_answer2_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='multiplechoicequestion',
            name='fake_answer2_es',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='multiplechoicequestion',
            name='fake_answer2_fr',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='multiplechoicequestion',
            name='fake_answer2_nl',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='multiplechoicequestion',
            name='fake_answer3_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='multiplechoicequestion',
            name='fake_answer3_es',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='multiplechoicequestion',
            name='fake_answer3_fr',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='multiplechoicequestion',
            name='fake_answer3_nl',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='multiplechoicequestion',
            name='fake_answer4_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='multiplechoicequestion',
            name='fake_answer4_es',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='multiplechoicequestion',
            name='fake_answer4_fr',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='multiplechoicequestion',
            name='fake_answer4_nl',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='multiplechoicequestion',
            name='hint_answer_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='multiplechoicequestion',
            name='hint_answer_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='multiplechoicequestion',
            name='hint_answer_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='multiplechoicequestion',
            name='hint_answer_nl',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='multiplechoicequestion',
            name='question_en',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='multiplechoicequestion',
            name='question_es',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='multiplechoicequestion',
            name='question_fr',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='multiplechoicequestion',
            name='question_nl',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='speakingexercise',
            name='vocabulary_items',
            field=models.ManyToManyField(blank=True, to='course.vocabularylist'),
        ),
        migrations.AlterField(
            model_name='testrecap',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='testrecap',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_recaps', to='course.lesson'),
        ),
        migrations.AlterField(
            model_name='testrecap',
            name='passing_score',
            field=models.FloatField(default=0.6, help_text='Minimum score to pass (0.0 to 1.0)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='testrecap',
            name='time_limit',
            field=models.PositiveIntegerField(default=10, help_text='Time limit in minutes'),
        ),
        migrations.AlterField(
            model_name='testrecap',
            name='title_en',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='testrecap',
            name='title_es',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='testrecap',
            name='title_fr',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='testrecap',
            name='title_nl',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='testrecapquestion',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='testrecapquestion',
            name='points',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='testrecapquestion',
            name='question_type',
            field=models.CharField(choices=[('vocabulary', 'Vocabulary'), ('multiple_choice', 'Multiple Choice'), ('matching', 'Matching'), ('fill_blank', 'Fill in the Blank')], max_length=20),
        ),
        migrations.AlterField(
            model_name='testrecapresult',
            name='completed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='testrecapresult',
            name='detailed_results',
            field=models.JSONField(default=dict, help_text='Detailed results per question'),
        ),
        migrations.AlterField(
            model_name='testrecapresult',
            name='test_recap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='course.testrecap'),
        ),
        migrations.AlterField(
            model_name='theorycontent',
            name='available_languages',
            field=models.JSONField(default=list, help_text='List of available languages for this theory'),
        ),
        migrations.AlterField(
            model_name='theorycontent',
            name='content_en',
            field=models.JSONField(default=dict, help_text='Theory content in English'),
        ),
        migrations.AlterField(
            model_name='theorycontent',
            name='content_es',
            field=models.JSONField(default=dict, help_text='Theory content in Spanish'),
        ),
        migrations.AlterField(
            model_name='theorycontent',
            name='content_fr',
            field=models.JSONField(default=dict, help_text='Theory content in French'),
        ),
        migrations.AlterField(
            model_name='theorycontent',
            name='content_lesson',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='theory_content', to='course.contentlesson'),
        ),
        migrations.AlterField(
            model_name='theorycontent',
            name='content_nl',
            field=models.JSONField(default=dict, help_text='Theory content in Dutch'),
        ),
        migrations.AlterField(
            model_name='vocabularylist',
            name='antonymous_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vocabularylist',
            name='antonymous_es',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vocabularylist',
            name='antonymous_fr',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vocabularylist',
            name='antonymous_nl',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vocabularylist',
            name='content_lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocabulary_lists', to='course.contentlesson'),
        ),
        migrations.AlterField(
            model_name='vocabularylist',
            name='definition_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vocabularylist',
            name='definition_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vocabularylist',
            name='definition_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vocabularylist',
            name='definition_nl',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vocabularylist',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='vocabularylist',
            name='synonymous_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vocabularylist',
            name='synonymous_es',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vocabularylist',
            name='synonymous_fr',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vocabularylist',
            name='synonymous_nl',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vocabularylist',
            name='word_type_en',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vocabularylist',
            name='word_type_es',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vocabularylist',
            name='word_type_fr',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vocabularylist',
            name='word_type_nl',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='contentlesson',
            unique_together={('lesson', 'order')},
        ),
        migrations.DeleteModel(
            name='ExerciseVocabularyMultipleChoice',
        ),
        migrations.DeleteModel(
            name='GrammarRulePoint',
        ),
        migrations.DeleteModel(
            name='Numbers',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='professional_field',
        ),
        migrations.RemoveField(
            model_name='testrecapquestion',
            name='fill_blank_id',
        ),
        migrations.RemoveField(
            model_name='testrecapquestion',
            name='matching_id',
        ),
        migrations.RemoveField(
            model_name='testrecapquestion',
            name='multiple_choice_id',
        ),
        migrations.RemoveField(
            model_name='testrecapquestion',
            name='reordering_id',
        ),
        migrations.RemoveField(
            model_name='testrecapquestion',
            name='speaking_id',
        ),
        migrations.RemoveField(
            model_name='testrecapquestion',
            name='vocabulary_id',
        ),
    ]
