# Generated by Django 5.1.10 on 2025-07-26 11:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0037_remove_exercisevocabularymultiplechoice_lesson_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='cms_unit_id',
            field=models.PositiveIntegerField(blank=True, help_text='ID du cours dans le CMS', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='unit',
            name='is_free',
            field=models.BooleanField(default=False, help_text='Cours gratuit accessible à tous'),
        ),
        migrations.AddField(
            model_name='unit',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Cours publié et visible dans le marketplace'),
        ),
        migrations.AddField(
            model_name='unit',
            name='last_sync',
            field=models.DateTimeField(blank=True, help_text='Dernière synchronisation avec le CMS', null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Prix du cours', max_digits=8),
        ),
        migrations.AddField(
            model_name='unit',
            name='teacher_id',
            field=models.PositiveIntegerField(blank=True, help_text='ID du professeur dans le CMS', null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='teacher_name',
            field=models.CharField(blank=True, help_text='Nom du professeur qui a créé ce cours', max_length=200),
        ),
        migrations.AddField(
            model_name='unit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
