# Generated by Django 5.1.10 on 2025-09-04 23:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('content', models.TextField(blank=True, verbose_name='Contenu')),
                ('content_type', models.CharField(choices=[('markdown', 'Markdown'), ('html', 'HTML'), ('plaintext', 'Texte simple')], default='markdown', max_length=20, verbose_name='Type de contenu')),
                ('visibility', models.CharField(choices=[('private', 'Privé'), ('shared', 'Partagé'), ('public', 'Public')], default='private', max_length=10, verbose_name='Visibilité')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('language', models.CharField(blank=True, max_length=10, verbose_name='Langue du document')),
                ('difficulty_level', models.CharField(blank=True, choices=[('A1', 'A1 - Débutant'), ('A2', 'A2 - Élémentaire'), ('B1', 'B1 - Intermédiaire'), ('B2', 'B2 - Intermédiaire supérieur'), ('C1', 'C1 - Avancé'), ('C2', 'C2 - Maîtrise')], max_length=2, verbose_name='Niveau de difficulté')),
                ('tags', models.CharField(blank=True, help_text='Tags séparés par des virgules', max_length=500, verbose_name='Tags')),
                ('last_edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_edited_documents', to=settings.AUTH_USER_MODEL, verbose_name='Dernière modification par')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_documents', to=settings.AUTH_USER_MODEL, verbose_name='Propriétaire')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-updated_at'],
                'permissions': [('share_document', 'Can share document')],
            },
        ),
        migrations.CreateModel(
            name='DocumentComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Commentaire')),
                ('position_start', models.IntegerField(blank=True, null=True, verbose_name='Position de début')),
                ('position_end', models.IntegerField(blank=True, null=True, verbose_name='Position de fin')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Résolu')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Résolu le')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_comments', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='documents.document', verbose_name='Document')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='documents.documentcomment', verbose_name='Commentaire parent')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_comments', to=settings.AUTH_USER_MODEL, verbose_name='Résolu par')),
            ],
            options={
                'verbose_name': 'Commentaire de document',
                'verbose_name_plural': 'Commentaires de documents',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_level', models.CharField(choices=[('view', 'Lecture seule'), ('edit', 'Édition'), ('admin', 'Administration')], default='view', max_length=10, verbose_name='Niveau de permission')),
                ('shared_at', models.DateTimeField(auto_now_add=True, verbose_name='Partagé le')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expire le')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='documents.document', verbose_name='Document')),
                ('shared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_documents_by', to=settings.AUTH_USER_MODEL, verbose_name='Partagé par')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_shares', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Partage de document',
                'verbose_name_plural': 'Partages de documents',
                'ordering': ['-shared_at'],
                'unique_together': {('document', 'user')},
            },
        ),
        migrations.AddField(
            model_name='document',
            name='collaborators',
            field=models.ManyToManyField(blank=True, related_name='shared_documents', through='documents.DocumentShare', to=settings.AUTH_USER_MODEL, verbose_name='Collaborateurs'),
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom du dossier')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_folders', to=settings.AUTH_USER_MODEL, verbose_name='Propriétaire')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subfolders', to='documents.folder', verbose_name='Dossier parent')),
            ],
            options={
                'verbose_name': 'Dossier',
                'verbose_name_plural': 'Dossiers',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='documents.folder', verbose_name='Dossier'),
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Contenu de la version')),
                ('version_number', models.PositiveIntegerField(verbose_name='Numéro de version')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('notes', models.TextField(blank=True, verbose_name='Notes de version')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='documents.document', verbose_name='Document')),
            ],
            options={
                'verbose_name': 'Version de document',
                'verbose_name_plural': 'Versions de documents',
                'ordering': ['-version_number'],
                'unique_together': {('document', 'version_number')},
            },
        ),
    ]
