# Generated by Django 5.2.6 on 2025-09-21 01:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='collaborators',
            field=models.ManyToManyField(blank=True, related_name='shared_documents', through='documents.DocumentShare', through_fields=('document', 'user'), to=settings.AUTH_USER_MODEL, verbose_name='Collaborateurs'),
        ),
    ]
