# Generated by Django 5.1.2 on 2025-02-08 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revision', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashcarddeck',
            name='user',
        ),
        migrations.AddField(
            model_name='flashcard',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='flashcarddeck',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
