# Generated by Django 5.1.2 on 2025-03-02 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revision', '0002_remove_flashcarddeck_user_flashcard_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flashcarddeck',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='flashcard_decks', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='flashcarddeck',
            unique_together={('user', 'name')},
        ),
        migrations.AddIndex(
            model_name='flashcard',
            index=models.Index(fields=['user', 'deck'], name='revision_fl_user_id_d84c9a_idx'),
        ),
        migrations.AddIndex(
            model_name='flashcard',
            index=models.Index(fields=['next_review'], name='revision_fl_next_re_5ff7dc_idx'),
        ),
        migrations.AddIndex(
            model_name='flashcarddeck',
            index=models.Index(fields=['user', 'is_active'], name='revision_fl_user_id_62bfb1_idx'),
        ),
    ]
