# Generated by Django 5.0.3 on 2025-10-05 17:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revision', '0002_cardmastery_cardperformance'),
    ]

    operations = [
        migrations.AddField(
            model_name='revisionsession',
            name='cards_completed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='revisionsession',
            name='cards_correct',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='revisionsession',
            name='last_milestone',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='revisionsession',
            name='milestone_interval',
            field=models.PositiveIntegerField(default=7),
        ),
        migrations.AddField(
            model_name='revisionsession',
            name='session_id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, help_text='ID unique de la session', null=True),
        ),
        migrations.AddField(
            model_name='revisionsession',
            name='total_cards',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
