# Generated by Django 5.1.2 on 2025-04-09 22:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revision', '0003_flashcard_user_flashcarddeck_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcarddeck',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flashcarddeck',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='flashcarddeck',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='flashcarddeck',
            index=models.Index(fields=['is_public'], name='revision_fl_is_publ_9c2fde_idx'),
        ),
        migrations.AddIndex(
            model_name='flashcarddeck',
            index=models.Index(fields=['is_archived'], name='revision_fl_is_arch_d10194_idx'),
        ),
        migrations.AddIndex(
            model_name='flashcarddeck',
            index=models.Index(fields=['expiration_date'], name='revision_fl_expirat_2ffa58_idx'),
        ),
    ]
