# Generated by Django 5.0.3 on 2025-10-05 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revision', '0003_revisionsession_cards_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='revisionsettings',
            name='shortcut_audio',
            field=models.CharField(default='a', help_text='Raccourci pour lecture audio (défaut: A)', max_length=10),
        ),
        migrations.AddField(
            model_name='revisionsettings',
            name='shortcut_difficult',
            field=models.CharField(default='3', help_text='Raccourci pour marquer comme difficile (défaut: 3)', max_length=10),
        ),
        migrations.AddField(
            model_name='revisionsettings',
            name='shortcut_easy',
            field=models.CharField(default='1', help_text='Raccourci pour marquer comme facile (défaut: 1)', max_length=10),
        ),
        migrations.AddField(
            model_name='revisionsettings',
            name='shortcut_edit',
            field=models.CharField(default='e', help_text='Raccourci pour éditer (défaut: E)', max_length=10),
        ),
        migrations.AddField(
            model_name='revisionsettings',
            name='shortcut_flip',
            field=models.CharField(default='Space', help_text='Raccourci pour retourner la carte (défaut: Espace)', max_length=10),
        ),
        migrations.AddField(
            model_name='revisionsettings',
            name='shortcut_medium',
            field=models.CharField(default='2', help_text='Raccourci pour marquer comme moyen (défaut: 2)', max_length=10),
        ),
        migrations.AddField(
            model_name='revisionsettings',
            name='shortcut_next',
            field=models.CharField(default='ArrowRight', help_text='Raccourci pour carte suivante (défaut: →)', max_length=10),
        ),
        migrations.AddField(
            model_name='revisionsettings',
            name='shortcut_previous',
            field=models.CharField(default='ArrowLeft', help_text='Raccourci pour carte précédente (défaut: ←)', max_length=10),
        ),
        migrations.AddField(
            model_name='revisionsettings',
            name='shortcut_shuffle',
            field=models.CharField(default='h', help_text='Raccourci pour mélanger (défaut: H)', max_length=10),
        ),
        migrations.AddField(
            model_name='revisionsettings',
            name='shortcut_star',
            field=models.CharField(default='s', help_text="Raccourci pour marquer d'une étoile (défaut: S)", max_length=10),
        ),
    ]
