# Generated by Django 5.1.2 on 2025-06-16 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revision', '0004_flashcarddeck_expiration_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcarddeck',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
