# Generated by Django 5.2.6 on 2025-10-09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('revision', '0004_revisionsettings_shortcut_audio_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Fichier uploadé (PDF, image, texte)', upload_to='revision/documents/%Y/%m/%d/')),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField(help_text='Taille du fichier en octets')),
                ('document_type', models.CharField(choices=[('pdf', 'PDF'), ('image', 'Image'), ('text', 'Texte'), ('other', 'Autre')], default='other', max_length=10)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En traitement'), ('completed', 'Terminé'), ('failed', 'Échoué')], default='pending', max_length=20)),
                ('extracted_text', models.TextField(blank=True, help_text='Texte extrait du document')),
                ('text_extraction_method', models.CharField(blank=True, help_text='Méthode utilisée (PyMuPDF, OCR, etc.)', max_length=50)),
                ('flashcards_generated_count', models.PositiveIntegerField(default=0, help_text='Nombre de flashcards générées à partir de ce document')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_at', models.DateTimeField(blank=True, help_text='Date de fin de traitement', null=True)),
                ('error_message', models.TextField(blank=True, help_text="Message d'erreur en cas d'échec")),
                ('generation_params', models.JSONField(blank=True, default=dict, help_text="Paramètres utilisés pour la génération (modèle IA, température, etc.)")),
                ('deck', models.ForeignKey(help_text='Deck cible pour les flashcards générées', on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_documents', to='revision.flashcarddeck')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revision_document_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='documentupload',
            index=models.Index(fields=['user', 'status'], name='revision_doc_user_id_f8c9a1_idx'),
        ),
        migrations.AddIndex(
            model_name='documentupload',
            index=models.Index(fields=['deck'], name='revision_doc_deck_id_a4b2c3_idx'),
        ),
        migrations.AddIndex(
            model_name='documentupload',
            index=models.Index(fields=['created_at'], name='revision_doc_created_d5e6f7_idx'),
        ),
        migrations.AddIndex(
            model_name='documentupload',
            index=models.Index(fields=['status', 'created_at'], name='revision_doc_status_g8h9i0_idx'),
        ),
    ]
