# Generated by Django 5.1.2 on 2025-06-16 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revision', '0005_alter_flashcarddeck_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcarddeck',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
