# Generated by Django 5.1.10 on 2025-07-09 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revision', '0007_add_learning_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcarddeck',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
