# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revision', '0008_auto_20250709_0507'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='front_language',
            field=models.CharField(blank=True, help_text="Code de langue pour le recto (ex: 'fr', 'en', 'es')", max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='back_language',
            field=models.CharField(blank=True, help_text="Code de langue pour le verso (ex: 'fr', 'en', 'es')", max_length=10, null=True),
        ),
    ]