# Generated by Django 5.1.10 on 2025-08-01 21:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revision', '0013_alter_revisionsessionconfig_options_and_more'),
    ]

    operations = [
        # Drop and recreate the table to match the model exactly
        migrations.RunSQL(
            sql=[
                # Drop the existing table if it exists
                "DROP TABLE IF EXISTS revision_revisionsettings;",
                # Create table with all the fields from the model
                """
                CREATE TABLE revision_revisionsettings (
                    id SERIAL PRIMARY KEY,
                    user_id INTEGER NOT NULL REFERENCES authentication_user(id) ON DELETE CASCADE,
                    default_study_mode VARCHAR(20) DEFAULT 'spaced',
                    default_difficulty VARCHAR(20) DEFAULT 'normal',
                    default_session_duration INTEGER DEFAULT 20,
                    cards_per_session INTEGER DEFAULT 20,
                    auto_advance BOOLEAN DEFAULT true,
                    spaced_repetition_enabled BOOLEAN DEFAULT true,
                    initial_interval_easy INTEGER DEFAULT 4,
                    initial_interval_normal INTEGER DEFAULT 2,
                    initial_interval_hard INTEGER DEFAULT 1,
                    required_reviews_to_learn INTEGER DEFAULT 3,
                    reset_on_wrong_answer BOOLEAN DEFAULT false,
                    show_progress_stats BOOLEAN DEFAULT true,
                    daily_reminder_enabled BOOLEAN DEFAULT true,
                    reminder_time TIME DEFAULT '18:00:00',
                    notification_frequency VARCHAR(20) DEFAULT 'daily',
                    enable_animations BOOLEAN DEFAULT true,
                    auto_play_audio BOOLEAN DEFAULT false,
                    keyboard_shortcuts_enabled BOOLEAN DEFAULT true,
                    show_word_stats BOOLEAN DEFAULT true,
                    stats_display_mode VARCHAR(20) DEFAULT 'detailed',
                    hide_learned_words BOOLEAN DEFAULT false,
                    group_by_deck BOOLEAN DEFAULT false,
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    UNIQUE(user_id)
                );
                """,
                # Add indexes
                "CREATE INDEX revision_revisionsettings_user_id_idx ON revision_revisionsettings (user_id);",
                # Also create RevisionSessionConfig table that was missing
                """
                CREATE TABLE IF NOT EXISTS revision_revisionsessionconfig (
                    id SERIAL PRIMARY KEY,
                    user_id INTEGER NOT NULL REFERENCES authentication_user(id) ON DELETE CASCADE,
                    name VARCHAR(100) NOT NULL,
                    session_type VARCHAR(20) DEFAULT 'standard',
                    duration_minutes INTEGER DEFAULT 20,
                    target_cards INTEGER DEFAULT 20,
                    include_new_cards BOOLEAN DEFAULT true,
                    include_review_cards BOOLEAN DEFAULT true,
                    include_difficult_cards BOOLEAN DEFAULT true,
                    tags_filter JSONB DEFAULT '[]'::jsonb,
                    difficulty_filter JSONB DEFAULT '[]'::jsonb,
                    is_default BOOLEAN DEFAULT false,
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    UNIQUE(user_id, name)
                );
                """,
                "CREATE INDEX revision_revisionsessionconfig_user_id_idx ON revision_revisionsessionconfig (user_id);",
            ],
            reverse_sql=[
                "DROP TABLE IF EXISTS revision_revisionsessionconfig;",
                "DROP TABLE IF EXISTS revision_revisionsettings;",
            ]
        ),
        migrations.AlterField(
            model_name='revisionsessionconfig',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=20, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(120)]),
        ),
        migrations.AlterField(
            model_name='revisionsessionconfig',
            name='target_cards',
            field=models.PositiveIntegerField(default=20, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(200)]),
        ),
    ]
