# Generated by Django 5.1.10 on 2025-08-01 21:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revision', '0013_alter_revisionsessionconfig_options_and_more'),
    ]

    operations = [
        # First check if the table exists, if not create it with all fields
        migrations.RunSQL(
            sql=[
                # Create table if it doesn't exist with all the necessary fields
                """
                CREATE TABLE IF NOT EXISTS revision_revisionsettings (
                    id SERIAL PRIMARY KEY,
                    user_id INTEGER NOT NULL REFERENCES authentication_user(id) ON DELETE CASCADE,
                    cards_per_session INTEGER DEFAULT 10,
                    difficulty_level VARCHAR(20) DEFAULT 'normal',
                    study_mode VARCHAR(20) DEFAULT 'spaced',
                    daily_goal INTEGER DEFAULT 10,
                    enable_notifications BOOLEAN DEFAULT true,
                    notification_frequency VARCHAR(20) DEFAULT 'daily',
                    preferred_time_hour INTEGER DEFAULT 9,
                    preferred_time_minute INTEGER DEFAULT 0,
                    timezone VARCHAR(50) DEFAULT 'UTC',
                    auto_advance BOOLEAN DEFAULT true,
                    show_pronunciation BOOLEAN DEFAULT true,
                    show_examples BOOLEAN DEFAULT true,
                    randomize_order BOOLEAN DEFAULT true,
                    review_failed_cards BOOLEAN DEFAULT true,
                    group_by_deck BOOLEAN DEFAULT false,
                    hide_learned_words BOOLEAN DEFAULT false,
                    show_word_stats BOOLEAN DEFAULT true,
                    stats_display_mode VARCHAR(20) DEFAULT 'detailed',
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    UNIQUE(user_id)
                );
                """,
                # Add indexes
                "CREATE INDEX IF NOT EXISTS revision_revisionsettings_user_id_idx ON revision_revisionsettings (user_id);",
            ],
            reverse_sql=[
                "DROP TABLE IF EXISTS revision_revisionsettings;",
            ]
        ),
        migrations.AlterField(
            model_name='revisionsessionconfig',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=20, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(120)]),
        ),
        migrations.AlterField(
            model_name='revisionsessionconfig',
            name='target_cards',
            field=models.PositiveIntegerField(default=20, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(200)]),
        ),
    ]
