# Generated by Django 5.1.10 on 2025-08-01 21:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revision', '0014_add_word_stats_settings'),
    ]

    operations = [
        # Note: group_by_deck, hide_learned_words, show_word_stats, and stats_display_mode
        # were already added in migration 0014 via raw SQL. 
        # Only adding them to Django's migration state for consistency.
        migrations.RunSQL(
            sql=[
                # Ensure all columns exist (idempotent operations)
                "ALTER TABLE revision_revisionsettings ADD COLUMN IF NOT EXISTS group_by_deck BOOLEAN DEFAULT false;",
                "ALTER TABLE revision_revisionsettings ADD COLUMN IF NOT EXISTS hide_learned_words BOOLEAN DEFAULT false;", 
                "ALTER TABLE revision_revisionsettings ADD COLUMN IF NOT EXISTS show_word_stats BOOLEAN DEFAULT true;",
                "ALTER TABLE revision_revisionsettings ADD COLUMN IF NOT EXISTS stats_display_mode VARCHAR(20) DEFAULT 'detailed';",
            ],
            reverse_sql=[
                "ALTER TABLE revision_revisionsettings DROP COLUMN IF EXISTS group_by_deck;",
                "ALTER TABLE revision_revisionsettings DROP COLUMN IF EXISTS hide_learned_words;",
                "ALTER TABLE revision_revisionsettings DROP COLUMN IF EXISTS show_word_stats;", 
                "ALTER TABLE revision_revisionsettings DROP COLUMN IF EXISTS stats_display_mode;",
            ]
        ),
        migrations.AlterField(
            model_name='revisionsessionconfig',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=20, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(120)]),
        ),
        migrations.AlterField(
            model_name='revisionsessionconfig',
            name='target_cards',
            field=models.PositiveIntegerField(default=20, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(200)]),
        ),
    ]
