# Generated by Django 5.1.10 on 2025-08-10 10:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revision', '0014_revisionsettings_group_by_deck_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='revisionsettings',
            name='group_by_deck',
            field=models.BooleanField(default=False, help_text='Grouper les statistiques par deck'),
        ),
        migrations.AddField(
            model_name='revisionsettings',
            name='hide_learned_words',
            field=models.BooleanField(default=False, help_text='Masquer les mots déjà appris dans les statistiques'),
        ),
        migrations.AddField(
            model_name='revisionsettings',
            name='show_word_stats',
            field=models.BooleanField(default=True, help_text='Afficher les statistiques de mots'),
        ),
        migrations.AddField(
            model_name='revisionsettings',
            name='stats_display_mode',
            field=models.CharField(choices=[('detailed', 'Détaillé'), ('summary', 'Résumé'), ('minimal', 'Minimal')], default='detailed', help_text="Mode d'affichage des statistiques", max_length=20),
        ),
        migrations.AddIndex(
            model_name='flashcard',
            index=models.Index(fields=['user', 'learned'], name='revision_fl_user_id_ae920f_idx'),
        ),
        migrations.AddIndex(
            model_name='flashcard',
            index=models.Index(fields=['deck', 'learned'], name='revision_fl_deck_id_5c9014_idx'),
        ),
        migrations.AddIndex(
            model_name='flashcard',
            index=models.Index(fields=['user', 'last_reviewed'], name='revision_fl_user_id_5297c5_idx'),
        ),
        migrations.AddIndex(
            model_name='flashcard',
            index=models.Index(fields=['deck', 'next_review'], name='revision_fl_deck_id_078e65_idx'),
        ),
    ]
