# Generated by Django 5.1.10 on 2025-08-01 21:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revision', '0014_add_word_stats_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='revisionsettings',
            name='group_by_deck',
            field=models.BooleanField(default=False, help_text='Grouper les statistiques par deck'),
        ),
        migrations.AddField(
            model_name='revisionsettings',
            name='hide_learned_words',
            field=models.BooleanField(default=False, help_text='Masquer les mots déjà appris dans les statistiques'),
        ),
        migrations.AddField(
            model_name='revisionsettings',
            name='show_word_stats',
            field=models.BooleanField(default=True, help_text='Afficher les statistiques de mots'),
        ),
        migrations.AddField(
            model_name='revisionsettings',
            name='stats_display_mode',
            field=models.CharField(choices=[('detailed', 'Détaillé'), ('summary', 'Résumé'), ('minimal', 'Minimal')], default='detailed', help_text="Mode d'affichage des statistiques", max_length=20),
        ),
        migrations.AlterField(
            model_name='revisionsessionconfig',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=20, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(120)]),
        ),
        migrations.AlterField(
            model_name='revisionsessionconfig',
            name='target_cards',
            field=models.PositiveIntegerField(default=20, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(200)]),
        ),
    ]
