# Generated by Django 5.1.10 on 2025-08-10 14:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revision', '0015_revisionsettings_group_by_deck_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='revisionsettings',
            name='audio_enabled',
            field=models.BooleanField(default=True, help_text='Activer la synthèse vocale'),
        ),
        migrations.AddField(
            model_name='revisionsettings',
            name='audio_speed',
            field=models.FloatField(default=0.9, help_text='Vitesse de la synthèse vocale (0.5 à 2.0)', validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(2.0)]),
        ),
        migrations.AddField(
            model_name='revisionsettings',
            name='preferred_voice_english',
            field=models.CharField(blank=True, help_text="Nom de la voix préférée pour l'anglais", max_length=200),
        ),
        migrations.AddField(
            model_name='revisionsettings',
            name='preferred_voice_french',
            field=models.CharField(blank=True, help_text='Nom de la voix préférée pour le français', max_length=200),
        ),
        migrations.AddField(
            model_name='revisionsettings',
            name='preferred_voice_german',
            field=models.CharField(blank=True, help_text="Nom de la voix préférée pour l'allemand", max_length=200),
        ),
        migrations.AddField(
            model_name='revisionsettings',
            name='preferred_voice_italian',
            field=models.CharField(blank=True, help_text="Nom de la voix préférée pour l'italien", max_length=200),
        ),
        migrations.AddField(
            model_name='revisionsettings',
            name='preferred_voice_spanish',
            field=models.CharField(blank=True, help_text="Nom de la voix préférée pour l'espagnol", max_length=200),
        ),
    ]
