# Generated by Django 5.1.10 on 2025-08-10 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revision', '0016_add_audio_settings_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revisionsettings',
            name='preferred_voice_english',
        ),
        migrations.RemoveField(
            model_name='revisionsettings',
            name='preferred_voice_french',
        ),
        migrations.RemoveField(
            model_name='revisionsettings',
            name='preferred_voice_german',
        ),
        migrations.RemoveField(
            model_name='revisionsettings',
            name='preferred_voice_italian',
        ),
        migrations.RemoveField(
            model_name='revisionsettings',
            name='preferred_voice_spanish',
        ),
        migrations.AddField(
            model_name='revisionsettings',
            name='preferred_voice_english_female',
            field=models.CharField(blank=True, help_text='Voix féminine anglaise préférée', max_length=200),
        ),
        migrations.AddField(
            model_name='revisionsettings',
            name='preferred_voice_english_male',
            field=models.CharField(blank=True, help_text='Voix masculine anglaise préférée', max_length=200),
        ),
        migrations.AddField(
            model_name='revisionsettings',
            name='preferred_voice_french_female',
            field=models.CharField(blank=True, help_text='Voix féminine française préférée', max_length=200),
        ),
        migrations.AddField(
            model_name='revisionsettings',
            name='preferred_voice_french_male',
            field=models.CharField(blank=True, help_text='Voix masculine française préférée', max_length=200),
        ),
        migrations.AddField(
            model_name='revisionsettings',
            name='preferred_voice_german_female',
            field=models.CharField(blank=True, help_text='Voix féminine allemande préférée', max_length=200),
        ),
        migrations.AddField(
            model_name='revisionsettings',
            name='preferred_voice_german_male',
            field=models.CharField(blank=True, help_text='Voix masculine allemande préférée', max_length=200),
        ),
        migrations.AddField(
            model_name='revisionsettings',
            name='preferred_voice_italian_female',
            field=models.CharField(blank=True, help_text='Voix féminine italienne préférée', max_length=200),
        ),
        migrations.AddField(
            model_name='revisionsettings',
            name='preferred_voice_italian_male',
            field=models.CharField(blank=True, help_text='Voix masculine italienne préférée', max_length=200),
        ),
        migrations.AddField(
            model_name='revisionsettings',
            name='preferred_voice_spanish_female',
            field=models.CharField(blank=True, help_text='Voix féminine espagnole préférée', max_length=200),
        ),
        migrations.AddField(
            model_name='revisionsettings',
            name='preferred_voice_spanish_male',
            field=models.CharField(blank=True, help_text='Voix masculine espagnole préférée', max_length=200),
        ),
    ]
