# Generated by Django 5.1.10 on 2025-08-10 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revision', '0017_add_gender_specific_voices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revisionsettings',
            name='preferred_voice_english_female',
        ),
        migrations.RemoveField(
            model_name='revisionsettings',
            name='preferred_voice_english_male',
        ),
        migrations.RemoveField(
            model_name='revisionsettings',
            name='preferred_voice_french_female',
        ),
        migrations.RemoveField(
            model_name='revisionsettings',
            name='preferred_voice_french_male',
        ),
        migrations.RemoveField(
            model_name='revisionsettings',
            name='preferred_voice_german_female',
        ),
        migrations.RemoveField(
            model_name='revisionsettings',
            name='preferred_voice_german_male',
        ),
        migrations.RemoveField(
            model_name='revisionsettings',
            name='preferred_voice_italian_female',
        ),
        migrations.RemoveField(
            model_name='revisionsettings',
            name='preferred_voice_italian_male',
        ),
        migrations.RemoveField(
            model_name='revisionsettings',
            name='preferred_voice_spanish_female',
        ),
        migrations.RemoveField(
            model_name='revisionsettings',
            name='preferred_voice_spanish_male',
        ),
        migrations.AddField(
            model_name='revisionsettings',
            name='preferred_gender_english',
            field=models.CharField(choices=[('male', 'Masculin'), ('female', 'Féminin'), ('auto', 'Automatique')], default='auto', help_text="Genre de voix préféré pour l'anglais", max_length=10),
        ),
        migrations.AddField(
            model_name='revisionsettings',
            name='preferred_gender_french',
            field=models.CharField(choices=[('male', 'Masculin'), ('female', 'Féminin'), ('auto', 'Automatique')], default='auto', help_text='Genre de voix préféré pour le français', max_length=10),
        ),
        migrations.AddField(
            model_name='revisionsettings',
            name='preferred_gender_german',
            field=models.CharField(choices=[('male', 'Masculin'), ('female', 'Féminin'), ('auto', 'Automatique')], default='auto', help_text="Genre de voix préféré pour l'allemand", max_length=10),
        ),
        migrations.AddField(
            model_name='revisionsettings',
            name='preferred_gender_italian',
            field=models.CharField(choices=[('male', 'Masculin'), ('female', 'Féminin'), ('auto', 'Automatique')], default='auto', help_text="Genre de voix préféré pour l'italien", max_length=10),
        ),
        migrations.AddField(
            model_name='revisionsettings',
            name='preferred_gender_spanish',
            field=models.CharField(choices=[('male', 'Masculin'), ('female', 'Féminin'), ('auto', 'Automatique')], default='auto', help_text="Genre de voix préféré pour l'espagnol", max_length=10),
        ),
    ]
