# Generated by Django 5.1.10 on 2025-08-10 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revision', '0018_replace_voice_names_with_gender_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcarddeck',
            name='default_back_language',
            field=models.CharField(blank=True, default='', help_text="Langue par défaut pour le verso des cartes (ex: 'fr', 'en', 'es'). Vide pour détection automatique.", max_length=10),
        ),
        migrations.AddField(
            model_name='flashcarddeck',
            name='default_front_language',
            field=models.CharField(blank=True, default='', help_text="Langue par défaut pour le recto des cartes (ex: 'fr', 'en', 'es'). Vide pour détection automatique.", max_length=10),
        ),
    ]
