# Generated by Django 5.1.10 on 2025-08-12 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revision', '0019_add_deck_language_fields'),
    ]

    operations = [
        # Ces champs ont déjà été ajoutés dans la migration 0014
        # Cette migration est maintenant vide pour éviter les conflits
        # Les champs suivants existent déjà :
        # - group_by_deck
        # - hide_learned_words  
        # - show_word_stats
        # - stats_display_mode
    ]
