# Generated by Django 5.0.3 on 2025-08-15 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revision', '0020_revisionsettings_group_by_deck_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='revisionsettings',
            name='group_by_deck',
            field=models.BooleanField(default=False, help_text='Grouper les statistiques par deck'),
        ),
        migrations.AddField(
            model_name='revisionsettings',
            name='hide_learned_words',
            field=models.BooleanField(default=False, help_text='Masquer les mots déjà appris dans les statistiques'),
        ),
        migrations.AddField(
            model_name='revisionsettings',
            name='show_word_stats',
            field=models.BooleanField(default=True, help_text='Afficher les statistiques de mots'),
        ),
        migrations.AddField(
            model_name='revisionsettings',
            name='stats_display_mode',
            field=models.CharField(choices=[('detailed', 'Détaillé'), ('summary', 'Résumé'), ('minimal', 'Minimal')], default='detailed', help_text="Mode d'affichage des statistiques", max_length=20),
        ),
    ]
