# Generated by Django 5.1.10 on 2025-08-27 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('revision', '0021_revisionsettings_group_by_deck_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createrevisionlist',
            name='user',
        ),
        migrations.DeleteModel(
            name='AddField',
        ),
        migrations.DeleteModel(
            name='CreateRevisionList',
        ),
    ]
