# Generated by Django 5.1.10 on 2025-07-12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VoicePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_voice_speed', models.CharField(choices=[('slow', 'Lent (120 mots/min)'), ('normal', 'Normal (180 mots/min)'), ('fast', 'Rapide (240 mots/min)')], default='normal', max_length=10)),
                ('preferred_voice_pitch', models.IntegerField(default=50, help_text='Hauteur de voix (0-100)')),
                ('tts_enabled', models.BooleanField(default=True, help_text='Activer la synthèse vocale')),
                ('auto_listen', models.BooleanField(default=False, help_text='Écoute automatique activée')),
                ('noise_suppression', models.BooleanField(default=True, help_text='Suppression du bruit')),
                ('sensitivity', models.IntegerField(default=70, help_text='Sensibilité du micro (0-100)')),
                ('preferred_accent', models.CharField(blank=True, help_text='Accent préféré (ex: en-US, en-GB)', max_length=10)),
                ('voice_commands_enabled', models.BooleanField(default=True, help_text='Commandes vocales activées')),
                ('pronunciation_feedback', models.BooleanField(default=True, help_text='Feedback de prononciation')),
                ('conversation_mode', models.BooleanField(default=False, help_text='Mode conversation continue')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='voice_preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VoiceInteraction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('interaction_type', models.CharField(choices=[('speech_to_text', 'Speech to Text'), ('text_to_speech', 'Text to Speech'), ('voice_command', 'Voice Command'), ('pronunciation', 'Pronunciation Practice')], max_length=20)),
                ('command_type', models.CharField(blank=True, choices=[('navigation', 'Navigation'), ('learning', 'Learning'), ('practice', 'Practice'), ('quiz', 'Quiz'), ('general', 'General')], max_length=20, null=True)),
                ('input_text', models.TextField(blank=True, help_text="Texte de l'entrée utilisateur")),
                ('output_text', models.TextField(blank=True, help_text='Texte de la réponse générée')),
                ('audio_duration', models.FloatField(blank=True, help_text='Durée audio en secondes', null=True)),
                ('confidence_score', models.FloatField(blank=True, help_text='Score de confiance (0-1)', null=True)),
                ('language_code', models.CharField(help_text='Code de langue (ex: fr-FR)', max_length=10)),
                ('session_id', models.CharField(blank=True, help_text='ID de session de conversation', max_length=100)),
                ('context_data', models.JSONField(blank=True, default=dict, help_text='Données de contexte JSON')),
                ('response_time', models.FloatField(blank=True, help_text='Temps de réponse en millisecondes', null=True)),
                ('success', models.BooleanField(default=True, help_text="Si l'interaction a réussi")),
                ('error_message', models.TextField(blank=True, help_text="Message d'erreur si échec")),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VoiceCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_phrase', models.CharField(help_text='Phrase qui déclenche la commande', max_length=200)),
                ('action_type', models.CharField(help_text="Type d'action à exécuter", max_length=50)),
                ('action_params', models.JSONField(default=dict, help_text="Paramètres de l'action")),
                ('is_active', models.BooleanField(default=True)),
                ('usage_count', models.IntegerField(default=0, help_text="Nombre d'utilisations")),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_commands', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'trigger_phrase')},
            },
        ),
        migrations.CreateModel(
            name='ConversationSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_type', models.CharField(choices=[('practice', 'Pratique'), ('lesson', 'Leçon'), ('quiz', 'Quiz'), ('free_talk', 'Conversation libre')], max_length=20)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('topic', models.CharField(blank=True, help_text='Sujet de conversation', max_length=100)),
                ('language_practiced', models.CharField(help_text='Langue pratiquée', max_length=10)),
                ('total_interactions', models.IntegerField(default=0)),
                ('total_duration', models.IntegerField(default=0, help_text='Durée totale en secondes')),
                ('average_confidence', models.FloatField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='voiceinteraction',
            index=models.Index(fields=['user', '-created_at'], name='vocal_voice_user_id_e9b623_idx'),
        ),
        migrations.AddIndex(
            model_name='voiceinteraction',
            index=models.Index(fields=['interaction_type', '-created_at'], name='vocal_voice_interac_a5a607_idx'),
        ),
        migrations.AddIndex(
            model_name='voiceinteraction',
            index=models.Index(fields=['session_id'], name='vocal_voice_session_cf3c62_idx'),
        ),
    ]