# Generated by Django 5.1.10 on 2025-07-14 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocal', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='voiceinteraction',
            new_name='vocal_voice_user_id_f0651e_idx',
            old_name='vocal_voice_user_id_e9b623_idx',
        ),
        migrations.RenameIndex(
            model_name='voiceinteraction',
            new_name='vocal_voice_interac_327082_idx',
            old_name='vocal_voice_interac_a5a607_idx',
        ),
        migrations.RenameIndex(
            model_name='voiceinteraction',
            new_name='vocal_voice_session_b76915_idx',
            old_name='vocal_voice_session_cf3c62_idx',
        ),
    ]
