"""
Manifest for Language Learning app
Auto-generated by create_complete_app.py
"""
from django.utils.translation import gettext_lazy as _

__manifest__ = {
    # Basic Information
    'name': _('Language Learning'),
    'display_name': 'Linguify Learn',
    'version': '1.0.0',
    'category': 'Education',
    'author': 'Linguify',
    'description': _('Learn languages with interactive lessons, personalized exercises and advanced progress tracking.'),
    'summary': _('Your complete language learning platform - Compete with Duolingo and Babbel'),
    
    # App Configuration
    'application': True,  # This is a user application (visible in App Store)
    'installable': True,  # Ready for development use
    'auto_install': False,  # Don't install automatically
    'sequence': 100,  # Display order
    
    # Dependencies
    'depends': [
        'base',
        'authentication',
    ],
    
    # Data files and assets
    'data': [
        # Add any default data files here
    ],
    
    # Frontend components
    'frontend_components': {
        'static_icon': '/static/language_learning/description/icon.png',
        'color': '#10b981',  # Vert émeraude pour l'apprentissage
        'display_category': 'education',
        'category_label': _('Education'),
        'category_icon': 'bi-mortarboard',
        'routes': {
            'home': '/language-learning/',
            'create': '/language-learning/create/',
            'api': '/language-learning/api/',
        },
        'menu_items': [
            {
                'name': 'home',
                'label': 'Mes Langues',
                'url': '/language-learning/',
                'icon': 'bi-globe'
            },
            {
                'name': 'lessons',
                'label': 'Leçons',
                'url': '/language-learning/lessons/',
                'icon': 'bi-book'
            },
            {
                'name': 'practice',
                'label': 'Pratique',
                'url': '/language-learning/practice/',
                'icon': 'bi-lightning'
            }
        ]
    },
    
    # Features and capabilities
    'features': [
        'interactive_lessons',
        'progress_tracking',
        'gamification',
        'speech_recognition',
        'personalized_learning',
        'vocabulary_builder',
        'grammar_exercises',
        'conversation_practice',
        'achievement_system',
        'streak_tracking'
    ],
    
    # Technical information
    'django_app': True,
    'has_models': True,
    'has_views': True,
    'has_templates': True,
    'has_static': True,
    'has_api': True,
    'has_tests': True,
}
