# Generated by Django 5.1.10 on 2025-09-04 23:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('es', 'Spanish'), ('de', 'German'), ('it', 'Italian'), ('pt', 'Portuguese'), ('nl', 'Dutch'), ('ja', 'Japanese'), ('ko', 'Korean'), ('zh', 'Chinese')], max_length=5, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('native_name', models.CharField(blank=True, max_length=50)),
                ('flag_emoji', models.CharField(blank=True, max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LanguagelearningItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('content', models.TextField(blank=True, verbose_name='Contenu')),
                ('difficulty', models.CharField(choices=[('easy', 'Facile'), ('normal', 'Normal'), ('hard', 'Difficile')], default='normal', max_length=10)),
                ('item_type', models.CharField(choices=[('lesson', 'Leçon'), ('exercise', 'Exercice'), ('vocabulary', 'Vocabulaire'), ('grammar', 'Grammaire'), ('listening', 'Écoute'), ('speaking', 'Expression orale')], default='lesson', max_length=15)),
                ('estimated_duration', models.PositiveIntegerField(default=10, help_text='Durée estimée en minutes')),
                ('order_index', models.PositiveIntegerField(default=0, help_text="Ordre d'affichage")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='language_learning.language')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language_learning_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Language Learning Item',
                'verbose_name_plural': 'Language Learning Items',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LanguageLearningSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_study_time', models.TimeField(default='18:00', help_text='Heure préférée pour étudier')),
                ('daily_goal_minutes', models.PositiveIntegerField(default=15, help_text='Objectif quotidien en minutes', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(300)])),
                ('weekly_goal_days', models.PositiveIntegerField(default=5, help_text='Nombre de jours par semaine', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('reminder_enabled', models.BooleanField(default=True)),
                ('reminder_frequency', models.CharField(choices=[('daily', 'Quotidien'), ('weekdays', 'Jours de semaine'), ('custom', 'Personnalisé')], default='daily', max_length=10)),
                ('streak_notifications', models.BooleanField(default=True)),
                ('achievement_notifications', models.BooleanField(default=True)),
                ('auto_difficulty_adjustment', models.BooleanField(default=True)),
                ('preferred_difficulty', models.CharField(choices=[('easy', 'Facile'), ('normal', 'Normal'), ('hard', 'Difficile'), ('adaptive', 'Adaptatif')], default='adaptive', max_length=10)),
                ('show_pronunciation_hints', models.BooleanField(default=True)),
                ('enable_audio_playback', models.BooleanField(default=True)),
                ('audio_playback_speed', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(2.0)])),
                ('show_progress_animations', models.BooleanField(default=True)),
                ('font_size', models.CharField(choices=[('small', 'Petit'), ('medium', 'Moyen'), ('large', 'Grand')], default='medium', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='language_learning_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Paramètres d'apprentissage des langues",
                'verbose_name_plural': "Paramètres d'apprentissage des langues",
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('elementary', 'Elementary'), ('intermediate', 'Intermediate'), ('upper_intermediate', 'Upper Intermediate'), ('advanced', 'Advanced'), ('proficient', 'Proficient')], max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('estimated_duration', models.PositiveIntegerField(default=10, help_text='Minutes')),
                ('content', models.JSONField(blank=True, default=dict, help_text='Lesson content and exercises')),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='language_learning.language')),
            ],
            options={
                'verbose_name': 'Lesson',
                'verbose_name_plural': 'Lessons',
                'ordering': ['language', 'level', 'order'],
                'unique_together': {('language', 'level', 'order')},
            },
        ),
        migrations.CreateModel(
            name='UserLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proficiency_level', models.CharField(choices=[('beginner', 'Beginner'), ('elementary', 'Elementary'), ('intermediate', 'Intermediate'), ('upper_intermediate', 'Upper Intermediate'), ('advanced', 'Advanced'), ('proficient', 'Proficient')], default='beginner', max_length=20)),
                ('target_level', models.CharField(choices=[('beginner', 'Beginner'), ('elementary', 'Elementary'), ('intermediate', 'Intermediate'), ('upper_intermediate', 'Upper Intermediate'), ('advanced', 'Advanced'), ('proficient', 'Proficient')], default='intermediate', max_length=20)),
                ('daily_goal', models.PositiveIntegerField(default=15, help_text='Minutes per day')),
                ('streak_count', models.PositiveIntegerField(default=0)),
                ('total_time_spent', models.PositiveIntegerField(default=0, help_text='Total minutes spent')),
                ('lessons_completed', models.PositiveIntegerField(default=0)),
                ('progress_percentage', models.FloatField(default=0.0, help_text='Overall progress percentage')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='language_learning.language')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_languages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Language',
                'verbose_name_plural': 'User Languages',
                'ordering': ['-last_activity'],
                'unique_together': {('user', 'language')},
            },
        ),
        migrations.CreateModel(
            name='UserLessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('score', models.FloatField(blank=True, help_text='Lesson score (0-100)', null=True)),
                ('time_spent', models.PositiveIntegerField(default=0, help_text='Minutes spent')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='language_learning.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Lesson Progress',
                'verbose_name_plural': 'User Lesson Progress',
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'lesson')},
            },
        ),
    ]
