# Generated by Django 5.1.10 on 2025-08-27 12:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language_learning', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='languagelearningitem',
            name='content',
            field=models.TextField(blank=True, verbose_name='Contenu'),
        ),
        migrations.AddField(
            model_name='languagelearningitem',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Facile'), ('normal', 'Normal'), ('hard', 'Difficile')], default='normal', max_length=10),
        ),
        migrations.AddField(
            model_name='languagelearningitem',
            name='estimated_duration',
            field=models.PositiveIntegerField(default=10, help_text='Durée estimée en minutes'),
        ),
        migrations.AddField(
            model_name='languagelearningitem',
            name='item_type',
            field=models.CharField(choices=[('lesson', 'Leçon'), ('exercise', 'Exercice'), ('vocabulary', 'Vocabulaire'), ('grammar', 'Grammaire'), ('listening', 'Écoute'), ('speaking', 'Expression orale')], default='lesson', max_length=15),
        ),
        migrations.AddField(
            model_name='languagelearningitem',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='language_learning.language'),
        ),
        migrations.AddField(
            model_name='languagelearningitem',
            name='order_index',
            field=models.PositiveIntegerField(default=0, help_text="Ordre d'affichage"),
        ),
        migrations.AddField(
            model_name='userlanguage',
            name='lessons_completed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userlanguage',
            name='progress_percentage',
            field=models.FloatField(default=0.0, help_text='Overall progress percentage'),
        ),
        migrations.CreateModel(
            name='LanguageLearningSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_study_time', models.TimeField(default='18:00', help_text='Heure préférée pour étudier')),
                ('daily_goal_minutes', models.PositiveIntegerField(default=15, help_text='Objectif quotidien en minutes', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(300)])),
                ('weekly_goal_days', models.PositiveIntegerField(default=5, help_text='Nombre de jours par semaine', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('reminder_enabled', models.BooleanField(default=True)),
                ('reminder_frequency', models.CharField(choices=[('daily', 'Quotidien'), ('weekdays', 'Jours de semaine'), ('custom', 'Personnalisé')], default='daily', max_length=10)),
                ('streak_notifications', models.BooleanField(default=True)),
                ('achievement_notifications', models.BooleanField(default=True)),
                ('auto_difficulty_adjustment', models.BooleanField(default=True)),
                ('preferred_difficulty', models.CharField(choices=[('easy', 'Facile'), ('normal', 'Normal'), ('hard', 'Difficile'), ('adaptive', 'Adaptatif')], default='adaptive', max_length=10)),
                ('show_pronunciation_hints', models.BooleanField(default=True)),
                ('enable_audio_playback', models.BooleanField(default=True)),
                ('audio_playback_speed', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(2.0)])),
                ('show_progress_animations', models.BooleanField(default=True)),
                ('font_size', models.CharField(choices=[('small', 'Petit'), ('medium', 'Moyen'), ('large', 'Grand')], default='medium', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='language_learning_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Paramètres d'apprentissage des langues",
                'verbose_name_plural': "Paramètres d'apprentissage des langues",
            },
        ),
    ]
