# Generated by Django 5.2.6 on 2025-09-21 01:17

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_coachprofile_coaching_languages_and_more'),
        ('language_learning', '0004_fix_target_level_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLearningProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='learning_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('native_language', models.CharField(choices=[('EN', 'English'), ('FR', 'French'), ('NL', 'Dutch'), ('ES', 'Spanish')], default='EN', help_text='Your native language', max_length=20)),
                ('target_language', models.CharField(choices=[('EN', 'English'), ('FR', 'French'), ('NL', 'Dutch'), ('ES', 'Spanish')], default='FR', help_text='The language you want to learn', max_length=20)),
                ('language_level', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], default='A1', help_text='Your current language level', max_length=2)),
                ('objectives', models.CharField(choices=[('Travel', 'Travel'), ('Business', 'Business'), ('Live Abroad', 'Live Abroad'), ('Exam', 'Exam'), ('For Fun', 'For Fun'), ('Work', 'Work'), ('School', 'School'), ('Study', 'Study'), ('Personal', 'Personal')], default='Travel', help_text='Your learning objectives', max_length=20)),
                ('speaking_exercises', models.BooleanField(default=True)),
                ('listening_exercises', models.BooleanField(default=True)),
                ('reading_exercises', models.BooleanField(default=True)),
                ('writing_exercises', models.BooleanField(default=True)),
                ('daily_goal', models.IntegerField(default=15, help_text='Daily goal in minutes', validators=[django.core.validators.MinValueValidator(1)])),
                ('weekday_reminders', models.BooleanField(default=True)),
                ('weekend_reminders', models.BooleanField(default=False)),
                ('reminder_time', models.TimeField(default=datetime.time(18, 0))),
                ('streak_count', models.PositiveIntegerField(default=0)),
                ('total_time_spent', models.PositiveIntegerField(default=0, help_text='Total minutes spent')),
                ('lessons_completed', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_activity', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'User Learning Profile',
                'verbose_name_plural': 'User Learning Profiles',
            },
        ),
        migrations.RemoveField(
            model_name='userlanguage',
            name='proficiency_level',
        ),
        migrations.AddField(
            model_name='userlanguage',
            name='is_native',
            field=models.BooleanField(default=False, help_text="Is this the user's native language?"),
        ),
        migrations.AddField(
            model_name='userlanguage',
            name='language_level',
            field=models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], default='A1', help_text='Your language level', max_length=2),
        ),
        migrations.AlterField(
            model_name='language',
            name='code',
            field=models.CharField(choices=[('EN', 'English'), ('FR', 'French'), ('NL', 'Dutch'), ('ES', 'Spanish')], max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='level',
            field=models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userlanguage',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learners', to='language_learning.language'),
        ),
        migrations.AlterField(
            model_name='userlanguage',
            name='target_level',
            field=models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], default='B2', max_length=2),
        ),
    ]
