# Generated by Django 5.2.6 on 2025-09-21 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language_learning', '0005_add_user_learning_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='code',
            field=models.CharField(choices=[('EN', 'English'), ('FR', 'French'), ('NL', 'Dutch'), ('ES', 'Spanish'), ('DE', 'German'), ('IT', 'Italian'), ('PT', 'Portuguese'), ('RU', 'Russian'), ('ZH', 'Chinese'), ('JA', 'Japanese'), ('AR', 'Arabic')], max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='userlearningprofile',
            name='native_language',
            field=models.CharField(choices=[('EN', 'English'), ('FR', 'French'), ('NL', 'Dutch'), ('ES', 'Spanish'), ('DE', 'German'), ('IT', 'Italian'), ('PT', 'Portuguese'), ('RU', 'Russian'), ('ZH', 'Chinese'), ('JA', 'Japanese'), ('AR', 'Arabic')], default='EN', help_text='Your native language', max_length=20),
        ),
        migrations.AlterField(
            model_name='userlearningprofile',
            name='target_language',
            field=models.CharField(choices=[('EN', 'English'), ('FR', 'French'), ('NL', 'Dutch'), ('ES', 'Spanish'), ('DE', 'German'), ('IT', 'Italian'), ('PT', 'Portuguese'), ('RU', 'Russian'), ('ZH', 'Chinese'), ('JA', 'Japanese'), ('AR', 'Arabic')], default='FR', help_text='The language you want to learn', max_length=20),
        ),
    ]
