services:
  - type: web
    name: openlinguify-docs
    env: python
    repo: https://github.com/openlinguify/linguify
    rootDir: docs
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: gunicorn docs_site.wsgi:application
    plan: free
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: PYTHONPATH
        value: "/opt/render/project/src/docs"