# Generated by Django 5.1.2 on 2024-11-16 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('Vocabulary', 'Vocabulary'), ('Grammar', 'Grammar'), ('Listening', 'Listening'), ('Speaking', 'Speaking'), ('Reading', 'Reading'), ('Writing', 'Writing'), ('Test', 'Test')], max_length=100)),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LearningPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Easy', max_length=10)),
                ('estimated_duration', models.IntegerField(help_text='In minutes')),
            ],
        ),
        migrations.CreateModel(
            name='Grammar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('example', models.TextField()),
                ('activity', models.ForeignKey(limit_choices_to={'activity_type': 'Grammar'}, on_delete=django.db.models.deletion.CASCADE, to='course.activity')),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.lesson'),
        ),
        migrations.CreateModel(
            name='Listening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('audio', models.FileField(upload_to='listening_audio/')),
                ('activity', models.ForeignKey(limit_choices_to={'activity_type': 'Listening'}, on_delete=django.db.models.deletion.CASCADE, to='course.activity')),
            ],
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('activity', models.ForeignKey(limit_choices_to={'activity_type': 'Reading'}, on_delete=django.db.models.deletion.CASCADE, to='course.activity')),
            ],
        ),
        migrations.CreateModel(
            name='Speaking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('audio', models.FileField(upload_to='speaking_audio/')),
                ('activity', models.ForeignKey(limit_choices_to={'activity_type': 'Speaking'}, on_delete=django.db.models.deletion.CASCADE, to='course.activity')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('correct_answer', models.CharField(max_length=100)),
                ('incorrect_answers', models.TextField(help_text='Separate the answers with a comma.')),
                ('activity', models.ForeignKey(limit_choices_to={'activity_type': 'Test'}, on_delete=django.db.models.deletion.CASCADE, to='course.activity')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('level', models.CharField(choices=[('-A1', '-A1'), ('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], max_length=3)),
                ('learning_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.learningpath')),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.unit'),
        ),
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('translation', models.CharField(max_length=100)),
                ('example_sentence', models.TextField()),
                ('activity', models.ForeignKey(limit_choices_to={'activity_type': 'Vocabulary'}, on_delete=django.db.models.deletion.CASCADE, to='course.activity')),
            ],
        ),
        migrations.CreateModel(
            name='Writing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('activity', models.ForeignKey(limit_choices_to={'activity_type': 'Writing'}, on_delete=django.db.models.deletion.CASCADE, to='course.activity')),
            ],
        ),
    ]
