# Generated by Django 5.1.10 on 2025-08-27 11:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_fix_tagrelation_object_id_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='SearchEngineStatus',
        ),
        migrations.DeleteModel(
            name='SEOPageMetrics',
        ),
        migrations.DeleteModel(
            name='SitemapGenerationReport',
        ),
        migrations.DeleteModel(
            name='SitemapLog',
        ),
        migrations.DeleteModel(
            name='SystemManagement',
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['-is_favorite', '-usage_count_total', 'name'], 'verbose_name': 'Tag Global', 'verbose_name_plural': 'Tags Globaux'},
        ),
        migrations.AlterModelOptions(
            name='tagrelation',
            options={'verbose_name': 'Relation Tag', 'verbose_name_plural': 'Relations Tags'},
        ),
        migrations.RemoveConstraint(
            model_name='tag',
            name='unique_tag_per_user',
        ),
        migrations.RemoveConstraint(
            model_name='tagrelation',
            name='unique_tag_object_relation',
        ),
        migrations.RemoveIndex(
            model_name='tag',
            name='core_tag_user_favorite_idx',
        ),
        migrations.RemoveIndex(
            model_name='tag',
            name='core_tag_user_usage_idx',
        ),
        migrations.RemoveIndex(
            model_name='tag',
            name='core_tag_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='tagrelation',
            name='core_tagrel_created_idx',
        ),
        migrations.RenameIndex(
            model_name='tag',
            new_name='core_tag_user_id_74e398_idx',
            old_name='core_tag_user_name_idx',
        ),
        migrations.RenameIndex(
            model_name='tag',
            new_name='core_tag_user_id_aebd03_idx',
            old_name='core_tag_user_active_idx',
        ),
        migrations.RenameIndex(
            model_name='tagrelation',
            new_name='core_tagrel_app_nam_4cba70_idx',
            old_name='core_tagrel_content_idx',
        ),
        migrations.RenameIndex(
            model_name='tagrelation',
            new_name='core_tagrel_tag_id_f7aa38_idx',
            old_name='core_tagrel_tag_app_idx',
        ),
        migrations.RenameIndex(
            model_name='tagrelation',
            new_name='core_tagrel_created_dcf53a_idx',
            old_name='core_tagrel_user_app_idx',
        ),
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(default='#3B82F6', help_text='Couleur hexadécimale du tag', max_length=7),
        ),
        migrations.AlterField(
            model_name='tag',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Description optionnelle du tag (max 200 caractères)', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tag',
            name='is_favorite',
            field=models.BooleanField(default=False, help_text='Tags favoris affichés en premier'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(help_text='Nom du tag (1-50 caractères)', max_length=50, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(50)]),
        ),
        migrations.AlterField(
            model_name='tagrelation',
            name='app_name',
            field=models.CharField(help_text="Nom de l'app (notebook, todo, calendar, etc.)", max_length=50),
        ),
        migrations.AlterField(
            model_name='tagrelation',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tagrelation',
            name='model_name',
            field=models.CharField(help_text='Nom du modèle (Note, Task, Event, etc.)', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('user', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='tagrelation',
            unique_together={('tag', 'app_name', 'model_name', 'object_id')},
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['user', '-usage_count_total'], name='core_tag_user_id_a72cf3_idx'),
        ),
        migrations.AlterModelTable(
            name='tag',
            table=None,
        ),
        migrations.AlterModelTable(
            name='tagrelation',
            table=None,
        ),
    ]
