import type { Metadata } from "next";

import { Navbar } from "./_components/Navbar";

export const metadata: Metadata = {
    title: "Linguify",
    description: "Generated by SoftNet",
  };

export default function RootLayout({
    children,
  }: Readonly<{
    children: React.ReactNode;
  }>) {
    return (
      <html lang="en" suppressHydrationWarning>
        <body>
            <Navbar />
            <div>{children}</div>
        </body>
      </html>
    );
  }