# Generated by Django 5.2.4 on 2025-07-27 13:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contentstore', '0002_cmschapter_cmscontentlesson_cmscontentblock_and_more'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('completed', 'Effectué'), ('failed', 'Échoué')], default='pending', max_length=20)),
                ('bank_account', models.CharField(help_text='IBAN used for payout', max_length=34)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='teachers.teacher')),
            ],
            options={
                'db_table': 'teacher_payouts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student_id', models.PositiveIntegerField(help_text='Student ID from backend')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('platform_commission', models.DecimalField(decimal_places=2, max_digits=8)),
                ('teacher_earnings', models.DecimalField(decimal_places=2, max_digits=8)),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('payment_method', models.CharField(max_length=50)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='teachers.teacher')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='contentstore.cmsunit')),
            ],
            options={
                'db_table': 'teacher_sales',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeacherEarnings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_gross_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_commissions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_net_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_paid_out', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pending_payout', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_sales_count', models.PositiveIntegerField(default=0)),
                ('last_sale_date', models.DateTimeField(blank=True, null=True)),
                ('last_payout_date', models.DateTimeField(blank=True, null=True)),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to='teachers.teacher')),
            ],
            options={
                'db_table': 'teacher_earnings',
            },
        ),
    ]
