# Generated by Django 5.0.3 on 2025-10-08 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monetization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payout',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='teacherearnings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
